### ISSUE TITLE
custom_components/xiaomi_miot/core/xiaomi_cloud.py:448

### ISSUE THREAD

**Issue by arsenal3008** [al-one/hass-xiaomi-miot#1037]
### Device model / 设备型号

imilab v1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Invalid config

### Entity attributes / 实体属性

vacuum.chuangmi_hmi707

### Home Assistant Logs / 系统日志

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.setup
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:448
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 18:40:32 (1 occurrences)
Last logged: 18:40:32

Error during setup of component xiaomi_miot
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa41555d0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sts.api.io.mi.com', port=443): Max retries exceeded with url: /sts?d=TCYG6RM1366FC0PK&ticket=0&pwd=1&p_ts=1677512427000&fid=0&p_lm=1&auth=jRGXm30dPNYOv2mzVgE4RMvYrtqfJb8zPlz%2F4r8tMYkRXWGXaGFA21bY6Zvc4Gh%2B%2FmzkxmFR8JLxESD06pzUb7xOr%2FOFnOFaqDcGHSPpHC9EZzxwFbjE7GCWdXgI%2FT%2Fd4YuCwccHImjzMZKrmN%2BoVjRd2eyoUAR4%2By%2FyUWcZtvw%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=RU&p_idc=Russia&nonce=azqPZJZz4tcBqp0M&_ssign=%2F6tYOJz4N3sfLbTiLpl8%2FbFG1pg%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa41555d0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 213, in async_setup
    if not await mic.async_login():
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 346, in async_login
    ret = await self.hass.async_add_executor_job(self._login_request, captcha)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 368, in _login_request
    response = self._login_step3(location)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 448, in _login_step3
    response = self.session.get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sts.api.io.mi.com', port=443): Max retries exceeded with url: /sts?d=TCYG6RM1366FC0PK&ticket=0&pwd=1&p_ts=1677512427000&fid=0&p_lm=1&auth=jRGXm30dPNYOv2mzVgE4RMvYrtqfJb8zPlz%2F4r8tMYkRXWGXaGFA21bY6Zvc4Gh%2B%2FmzkxmFR8JLxESD06pzUb7xOr%2FOFnOFaqDcGHSPpHC9EZzxwFbjE7GCWdXgI%2FT%2Fd4YuCwccHImjzMZKrmN%2BoVjRd2eyoUAR4%2By%2FyUWcZtvw%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=RU&p_idc=Russia&nonce=azqPZJZz4tcBqp0M&_ssign=%2F6tYOJz4N3sfLbTiLpl8%2FbFG1pg%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa41555d0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by al-one** [comment]
1. Check your dns `nslookup sts.api.io.mi.com`
2. Check your network `ping sts.api.io.mi.com`
