### ISSUE TITLE
不能控制 YEELIGHT䊹玉吸頂燈

### ISSUE THREAD

**Issue by morrislaw715** [al-one/hass-xiaomi-miot#104]
Logger: homeassistant
Source: custom_components/xiaomi_miot/light.py:149
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 22:51:15 (4 occurrences)
Last logged: 22:52:43

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 355, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 404, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 796, in state_attributes
    color_mode = self._light_internal_color_mode
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 646, in _light_internal_color_mode
    if COLOR_MODE_COLOR_TEMP in supported and self.color_temp is not None:
  File "/config/custom_components/xiaomi_miot/light.py", line 137, in color_temp
    return self.translate_mired(self._state_attrs.get(self._prop_color_temp.full_name) or 2700)
  File "/config/custom_components/xiaomi_miot/light.py", line 149, in translate_mired
    return round(1000000 / num)
TypeError: unsupported operand type(s) for /: 'int' and 'str'

**Comment by al-one** [comment]
请提供设备型号(Model)及实体状态属性。
> [🔨 开发者工具](https://my.home-assistant.io/redirect/developer_states) > [ℹ️ 状态](https://my.home-assistant.io/redirect/developer_states) > 🔍 筛选实体

**Comment by morrislaw715** [comment]
model應該是 yeelink.light.ceiling12

以下是實体狀態
restored: true
min_mireds: 154
max_mireds: 370
effect_list:
  - Day
  - Night
supported_color_modes:
  - color_temp
supported_features: 7
friendly_name: YL䊹玉吸頂燈 Light

**Comment by al-one** [comment]
请升级插件到master分支最新版本再试下。
```shell
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=master bash -
```

**Comment by morrislaw715** [comment]
謝謝，成功了！

**Comment by al-one** [comment]
请再提供下实体状态属性。

**Comment by morrislaw715** [comment]
min_mireds: 154
max_mireds: 370
effect_list: Day, Night
supported_color_modes: color_temp
color_mode: color_temp
brightness: 3
color_temp: 370
effect: Day
model: yeelink.light.ceiling12
lan_ip: 
mac_address: 
firmware_version: 2.0.6_0041
hardware_version: 
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling12:1
light.on: true
light.brightness: 1
light.color_temperature: 6500
light.mode: 1
brightness_delta.error: -704030013
light_extension.ct_delta.error: -704030013
light_extension.ct_adjust_alexa.error: -704030013
state_updater: cloud
friendly_name: YL䊹玉吸頂燈 Light
supported_features: 7
