### ISSUE TITLE
小米蓝牙门窗传感器

### ISSUE THREAD

**Issue by dails1987** [al-one/hass-xiaomi-miot#1168]
### Device model / 设备型号

isa.magnet.dw2hl

### Component version / 插件版本

 v0.7.10

### HA core version / HA版本

Home Assistant 2023.6.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米蓝牙门窗传感器，
1.Magnet Sensor无法自动更新开合状态。
2.Magnet Sensor Illumination 显示不可用状态
5月份发生的，具体HA什么办法出现这种问题，并不知道。更新到最新版本问题并未解决。

### Entity attributes / 实体属性

设备信息：isa.magnet.dw2hl
固件：2.1.0_0059

**Comment by SodaWithoutSparkles** [comment]
我有同样的问题。请问如何提取相关的日志档案以协助除错？

**Comment by SodaWithoutSparkles** [comment]
会不会和这个有关系？

```
Logger: homeassistant
Source: components/sensor/__init__.py:585
First occurred: 1:49:42 AM (30 occurrences)
Last logged: 2:04:12 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'weak'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 879, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 577, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.isa_dw2hl_6bb6_illumination_2 has device class 'illuminance', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'weak' (<class 'str'>)
```

**Comment by peerless0828** [comment]
同样的问题

Logger: homeassistant.helpers.entity
Source: components/sensor/__init__.py:585
First occurred: 05:29:32 (56 occurrences)
Last logged: 05:57:01

Update for binary_sensor.isa_dw2hl_41ab_magnet_sensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'weak'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1476, in async_update
    await self.async_update_for_main_entity()
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 193, in async_update_for_main_entity
    await super().async_update_for_main_entity()
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 127, in async_update_for_main_entity
    self._update_sub_entities(['illumination', 'no_motion_duration'], domain='sensor')
  File "/config/custom_components/xiaomi_miot/__init__.py", line 2048, in _update_sub_entities
    self._subs[fnm].update_from_parent()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 2406, in update_from_parent
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.isa_dw2hl_41ab_illumination has device class 'illuminance', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'weak' (<class 'str'>)

**Comment by al-one** [comment]
- #1137 

尝试master分支。

**Comment by SodaWithoutSparkles** [comment]
不过master branch的检查没过？

**Comment by SodaWithoutSparkles** [comment]
應該不行。看起來沒處理strong的情況
```
Logger: homeassistant
Source: components/sensor/__init__.py:585
First occurred: 11:24:06 PM (54 occurrences)
Last logged: 11:52:11 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'strong'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.isa_dw2hl_6bb6_illumination has device class 'illuminance', state class 'None' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'strong' (<class 'str'>)
```

**Comment by SodaWithoutSparkles** [comment]
而且也沒有辦法更新開關情況，和亮度沒關係

**Comment by YikLiu93** [comment]
蓝牙门窗传感器不是因为轮询时间的问题推荐搭配多模网关+getaway3插件吗？

**Comment by SodaWithoutSparkles** [comment]
问题是我是这几天才搞home assistant，不过上个月给我自动更新到了1.5.5_0006所有刷不了telnet

**Comment by SodaWithoutSparkles** [comment]
确认问题了，估计是亮度那里有问题直接把整个流程挂起。如果要门窗感应的，先去home assistant > device > 门窗传感器 > 亮度 > disable
