### ISSUE TITLE
小米温湿度计2获取温湿度信息为Unavailable

### ISSUE THREAD

**Issue by IchinoseHimeki** [al-one/hass-xiaomi-miot#1241]
### Device model / 设备型号

[miaomiaoce.sensor_ht.t2](https://home.miot-spec.com/s/miaomiaoce.sensor_ht.t2)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

通过自动集成及账号可获取该设备，但温度及湿度无法获取，状态为unavailable。根据其他issue尝试切换至master分支，没有解决问题。

### Entity attributes / 实体属性

unit_of_measurement: °C
device_class: temperature
friendly_name: 温湿度计 Temperature Humidity Sensor
supported_features: 0

### Home Assistant Logs / 系统日志

该条错误反复出现
2023-08-06 20:46:10.782 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'unknown'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 880, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 717, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.miaomiaoce_t2_a968_temperature_humidity_sensor has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>)

**Comment by wqhqq1** [comment]
开云端模式试试

**Comment by IchinoseHimeki** [comment]
> 开云端模式试试
已经更新至0.7.11并使用云端模式进行配置，依旧失败

**Comment by al-one** [comment]
尝试master分支。
