### ISSUE TITLE
Yeelight 舒适暖浴霸 (yeelink.bhf_light.v10)在0.7.11更新后不再可用

### ISSUE THREAD

**Issue by Catfish-Y** [al-one/hass-xiaomi-miot#1257]
### Device model / 设备型号

Yeelight 舒适暖浴霸 (yeelink.bhf_light.v10)

### Component version / 插件版本

0.7.11

### HA core version / HA版本

2023.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

插件更新到0.7.11后，浴霸各实体不再可用（PTC Bath Heater除外，可控制开启暖风，设备暖风开启后变为不可用）。
浴霸在0.7.10及之前版本可正常使用、联动

### Entity attributes / 实体属性

hvac_modes: off, dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes: level1, level2
current_temperature: null
fan_mode: level1
hvac_action: off
model: yeelink.bhf_light.v10
lan_ip: 10.0.10.221
mac_address: CC:B5:D1:61:6E:DC
entity_class: MiotClimateEntity
home_room: CCA的家 次卫
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v10:1
ptc_bath_heater.mode: 0
ptc_bath_heater.blow: false
ptc_bath_heater.heating: false
ptc_bath_heater.ventilation: false
ptc_bath_heater.heat_level: 1
light.on: false
light.mode: 1
state_updater: cloud
sub_entities: ptc_bath_heater-3.blow-2, ptc_bath_heater-3.heating-3, ptc_bath_heater-3.ventilation-4, light-2
friendly_name: 次卫浴霸 PTC Bath Heater
supported_features: 8

**Comment by al-one** [comment]
请检查开启暖风后有无产生[报错日志](https://my.home-assistant.io/redirect/logs)。

**Comment by Catfish-Y** [comment]
抱歉，issue中实体属性提交的是回滚0.7.10版本后的，以下是0.7.11下的实体属性：

hvac_modes: off, dry
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes: level1, level2
current_temperature: null
fan_mode: null
hvac_action: drying
model: yeelink.bhf_light.v10
lan_ip: 10.0.10.221
mac_address: CC:B5:D1:61:6E:DC
entity_class: MiotClimateEntity
home_room: CCA的家 次卫
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v10:1
ptc_bath_heater.mode: 1
ptc_bath_heater.blow.error: -4004 Other internal errors
ptc_bath_heater.heating.error: -4004 Other internal errors
ptc_bath_heater.ventilation.error: -4004 Other internal errors
ptc_bath_heater.heat_level.error: -4004 Other internal errors
light.on.error: -4004 Other internal errors
light.mode.error: -4004 Other internal errors
state_updater: lan
sub_entities: ptc_bath_heater-3.blow-2, ptc_bath_heater-3.heating-3, ptc_bath_heater-3.ventilation-4
friendly_name: 次卫浴霸 PTC Bath Heater
supported_features: 8


错误日志等获取后再贴上来

**Comment by Catfish-Y** [comment]
Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1401
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 15:28:00 (2 occurrences)
Last logged: 15:28:28

次卫浴霸(yeelink.bhf_light.v10): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'ptc_bath_heater.mode': {'siid': 3, 'piid': 1}, 'ptc_bath_heater.blow': {'siid': 3, 'piid': 2}, 'ptc_bath_heater.heating': {'siid': 3, 'piid': 3}, 'ptc_bath_heater.ventilation': {'siid': 3, 'piid': 4}, 'ptc_bath_heater.heat_level': {'siid': 3, 'piid': 5}, 'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}}, max_properties: 9/7

@al-one

**Comment by al-one** [comment]
尝试添加自定义属性 `chunk_properties: 1`

https://user-images.githubusercontent.com/4549099/211185592-79daa90d-c5cb-4c9e-829c-12a52fa3eaf0.mp4

**Comment by jianyun8023** [comment]
我也有这个设备，这个设备固件有bug。N/A 表示获取状态时出错了。我想适配，但是我搞不定。
![561691399183_ pic](https://github.com/al-one/hass-xiaomi-miot/assets/18240360/bec164c8-00bb-4dc4-a58e-17ac3d54fab6)

**Comment by Catfish-Y** [comment]
> 

添加 chunk_properties: 1 后恢复正常

**Comment by jianyun8023** [comment]
> > 
> 
> 
> 
> 添加 chunk_properties: 1 后恢复正常

请问你的设备是s2pro吗？固件版本是多少呀

**Comment by Catfish-Y** [comment]
> > > 
> > 
> > 
> > 添加 chunk_properties: 1 后恢复正常
> 
> 请问你的设备是s2pro吗？固件版本是多少呀

是S2 pro，两台固件分别是2.2.1.0005和2.2.1.0003

**Comment by Catfish-Y** [comment]
> > > 
> > 
> > 
> > 添加 chunk_properties: 1 后恢复正常
> 
> 请问你的设备是s2pro吗？固件版本是多少呀

在0.7.10和之前版本的Miot Auto插件下应该都表现正常

**Comment by jianyun8023** [comment]
> 在0.7.10和之前版本的Miot Auto插件下应该都表现正常

我想看下在米家中的版本是多少。你这个问题原因是现在支持本地控制了，这个设备固件有bug，你看看我发的那张表，是本地控制下的情况，只要出现n/a，这个设备就会变成不可用了。例如吹风

**Comment by Catfish-Y** [comment]
> 

上面说了固件号呀，2.2.1.0005和2.2.1.0003

**Comment by jianyun8023** [comment]
@Catfish-Y 抱歉，没看到上一条😂

**Comment by al-one** [comment]
尝试移除`chunk_properties: 1`或将其值改为7，并添加`exclude_miot_services: yl_bath_heater`。

- #1031

**Comment by al-one** [comment]
排除`yl_bath_heater`服务有用吗？

**Comment by Catfish-Y** [comment]
> 排除`yl_bath_heater`服务有用吗？

抱歉这几天都不在家，需要稍后测试

**Comment by Catfish-Y** [comment]
目前测试下来是这样的：

勾选 auto_cloud，miot_local
添加 chunk_properties: 1
恢复正常

只勾选 miot_local
添加 chunk_properties: 1
结果是PTC Bath Heater正常可控制开关，其他的依然不正常

不勾选任何选项，只排除yl_bath_heater服务
问题依旧存在

不勾选任何选项，只添加 chunk_properties: 1
恢复正常

**Comment by jianyun8023** [comment]
@al-one @Catfish-Y 我找客服要到了`2.2.1.0005`的升级， 本地通过python-miio调用，还是存在错误返回的json问题。
出现错误的情况可以看我上面发的图，只要出现错误，这个设备就不可用。**目前看本地控制不可用，只能用云端接入**。
**想本地接入，只能让yeelight修固件bug。**
```
DEBUG:miio.device:Detected model yeelink.bhf_light.v10
DEBUG:miio.miioprotocol:192.168.40.65:54321 >>: {'id': 2, 'method': 'get_properties', 'params': [{'did': '3-1', 'siid': 3, 'piid': 1}]}
DEBUG:miio.protocol:Unable to parse json '{"id":2,"result":[{"did":"3-1","siid":3,"piid":1,"code":0,"value":get_down}],"exe_time":260}': Expecting value: line 1 column 67 (char 66)
DEBUG:miio.click_common:Exception: Unable to parse message payload
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/protocol.py", line 199, in _decode
    return json.loads(decoded)

```

**Comment by al-one** [comment]
插件已默认为该设备添加选项`chunk_properties: 1`和`exclude_miot_services: yl_bath_heater`，如果依然不可用，请勾选`miot_cloud`选项通过云端接入。

`DEBUG:miio.protocol:Unable to parse json '{"id":2,"result":[{"did":"3-1","siid":3,"piid":1,"code":0,"value":get_down}],"exe_time":260}': Expecting value: line 1 column 67 (char 66)`
该日志中设备返回了错误的json，`get_down`应该为字符串但是确没有引号包裹，导致py解析失败并抛出异常。插件对此也无能为力，建议勾选`miot_cloud`云端接入。

**Comment by Catfish-Y** [comment]
> @al-one @Catfish-Y 我找客服要到了`2.2.1.0005`的升级， 本地通过python-miio调用，还是存在错误返回的json问题。 出现错误的情况可以看我上面发的图，只要出现错误，这个设备就不可用。**目前看本地控制不可用，只能用云端接入**。 **想本地接入，只能让yeelight修固件bug。**当然，大佬应该有解决办法吧
> 
> ```
> DEBUG:miio.device:Detected model yeelink.bhf_light.v10
> DEBUG:miio.miioprotocol:192.168.40.65:54321 >>: {'id': 2, 'method': 'get_properties', 'params': [{'did': '3-1', 'siid': 3, 'piid': 1}]}
> DEBUG:miio.protocol:Unable to parse json '{"id":2,"result":[{"did":"3-1","siid":3,"piid":1,"code":0,"value":get_down}],"exe_time":260}': Expecting value: line 1 column 67 (char 66)
> DEBUG:miio.click_common:Exception: Unable to parse message payload
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/miio/protocol.py", line 199, in _decode
>     return json.loads(decoded)
> ```

这个浴霸最烦的就是通过智能多模网关1/2都能在米家本地联动，接入HA一堆问题

**Comment by jianyun8023** [comment]
@Catfish-Y 
> 这个浴霸最烦的就是通过智能多模网关1/2都能在米家本地联动，接入HA一堆问题

同感，我找客服让他们修bug也不理。这个设备的属性在ha里面我也感觉很扭曲，当开关和选择器都比当做恒温器类设备好。

**Comment by al-one** [comment]
尝试添加选项`exclude_miot_properties: ptc_bath_heater.mode`，这个属性实际似乎没多大作用

**Comment by al-one** [comment]
有用吗？

**Comment by kiruya1987** [comment]
还是会掉线变不可用, 过了一段时间后又可用了

**Comment by al-one** [comment]
最新版本还是会掉线吗？

**Comment by jianyun8023** [comment]
> 最新版本还是会掉线吗？

@al-one 我目前看是ok的。
