### ISSUE TITLE
本地模式和自动模式下小米台灯2不可用

### ISSUE THREAD

**Issue by SmileIOT** [al-one/hass-xiaomi-miot#1259]
### Device model / 设备型号

[yeelink.light.lamp4](https://home.miot-spec.com/s/yeelink.light.lamp4)

### Component version / 插件版本

0.7.11

### HA core version / HA版本

2023.7.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

本地模式和自动模式下小米台灯2不可用，云端模式可以正常可用。

### Entity attributes / 实体属性

light.yeelink_lamp4_ae55_light_2

**Comment by al-one** [comment]
尝试给设备断电几分钟。

**Comment by huangqian8** [comment]
同样的问题，改云端模式正常。

**Comment by al-one** [comment]
提供[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by huangqian8** [comment]
日志详细信息( ERROR )
Logger: homeassistant.components.light
Source: helpers/template.py:565
Integration: 灯光 ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 2023年8月25日 20:12:07 (6 occurrences)
Last logged: 23:06:47

xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 563, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2179, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1927, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1609, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input '' when rendering template '{{ value if props.nl_br|int == 0 else props.nl_br|default(value)|int }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1369, in async_update
    results = await self._miio2miot.async_get_miot_props(self.miot_device, local_mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 115, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 140, in get_miot_props
    val = tpl.render({
          ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 532, in render
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 46, in run_callback
    future.set_result(callback(*args))
                      ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 565, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input '' when rendering template '{{ value if props.nl_br|int == 0 else props.nl_br|default(value)|int }}' but no default was specified

**Comment by al-one** [comment]
尝试master分支。

**Comment by huangqian8** [comment]
> 尝试master分支。

问题解决，谢谢。
