### ISSUE TITLE
无法添加米家台灯1S

### ISSUE THREAD

**Issue by jinyu121** [al-one/hass-xiaomi-miot#1303]
### Device model / 设备型号

无实体，我找不到它

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

一直无法添加 米家台灯1S

### Entity attributes / 实体属性

无实体

### Home Assistant Logs / 系统日志

```
2023-09-09 22:27:11.994 ERROR (MainThread) [homeassistant.components.light] xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1946, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1628, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input '' when rendering template '{{ value if props.nl_br|int == 0 else props.nl_br|default(value)|int }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 936, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1369, in async_update
    results = await self._miio2miot.async_get_miot_props(self.miot_device, local_mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 115, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 140, in get_miot_props
    val = tpl.render({
          ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 536, in render
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 44, in run_callback
    future.set_result(callback(*args))
                      ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input '' when rendering template '{{ value if props.nl_br|int == 0 else props.nl_br|default(value)|int }}' but no default was specified

```

**Comment by jinyu121** [comment]
Seems this problem has been solved in master branch.

**Comment by lxz946786639** [comment]
回退到7.11就能解决了

**Comment by lxz946786639** [comment]
新版本依然没提及任何修复。

**Comment by lxz946786639** [comment]
新版本依然没提及任何修复。
