### ISSUE TITLE
Water level missing

### ISSUE THREAD

**Issue by jahnkenneth** [al-one/hass-xiaomi-miot#1363]
### Device model / 设备型号

xiaomi.humidifier.airmx

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.10.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Water level not showing

### Entity attributes / 实体属性

![IMG_3622](https://github.com/al-one/hass-xiaomi-miot/assets/28279147/5485b969-aec3-43dd-9243-7acfc40aaf4d)

### Home Assistant Logs / 系统日志

[home-assistant_2023-10-20T15-57-36.009Z.log](https://github.com/al-one/hass-xiaomi-miot/files/13056159/home-assistant_2023-10-20T15-57-36.009Z.log)

**Comment by jahnkenneth** [comment]
@al-one 
Help please? 
Will gladly make a donation for a reply. :-)

**Comment by ABUAIJUTIE** [comment]
The water-level attribute should be contained in the first entity in your screenshot. It's not an individual entity. 
If you are planing to set up an alert automation, you can access it through attributes selection. 
If you need to make it an entity so you can manage it on a lovelace dashboard, you should try template sensor.

**Comment by jahnkenneth** [comment]
@ABUAIJUTIE Thanks. :-)
Got it. 
However, the value is not correct. 
![image](https://github.com/al-one/hass-xiaomi-miot/assets/28279147/7516d486-32f0-4a7b-8346-a04ffe1866aa)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/28279147/d8252799-2735-4774-9627-c39711f90166)

Also the "clean" function does not work. It just reverts back to "constant humidity" after a few seconds...
![image](https://github.com/al-one/hass-xiaomi-miot/assets/28279147/468d806c-8eab-4782-aa59-699ef8ac3304)

**Comment by ABUAIJUTIE** [comment]
Incorrect values may caused by delay of getting refresh from cloud. 
About Clean mode problem, I don't own this device though.😂  Some logs will help.

**Comment by jahnkenneth** [comment]
> Incorrect values may caused by delay of getting refresh from cloud. 
> 
> About Clean mode problem, I don't own this device though.😂  Some logs will help.

Sure. This happens when selecting "clean mode":

Logger: miio.integrations.humidifier.zhimi.airhumidifier_miot
Source: /usr/local/lib/python3.11/site-packages/miio/integrations/humidifier/zhimi/airhumidifier_miot.py:124
First occurred: 15:03:16 (443 occurrences)
Last logged: 16:53:53

Cannot parse mode: None is not a valid OperationMode
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/integrations/humidifier/zhimi/airhumidifier_miot.py", line 122, in mode
    mode = OperationMode(self.data["mode"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: None is not a valid OperationMode

Logger: miio.miot_device
Source: /usr/local/lib/python3.11/site-packages/miio/miot_device.py:172
First occurred: 15:03:16 (443 occurrences)
Last logged: 16:53:53

Unable to find mapping for xiaomi.humidifier.airmx, falling back to zhimi.humidifier.ca4

This happens when selecting "Descale mode:  

Logger: miio.miot_device
Source: /usr/local/lib/python3.11/site-packages/miio/miot_device.py:172
First occurred: 15:03:16 (457 occurrences)
Last logged: 16:57:23

Unable to find mapping for xiaomi.humidifier.airmx, falling back to zhimi.humidifier.ca4

Logger: miio.integrations.humidifier.zhimi.airhumidifier_miot
Source: /usr/local/lib/python3.11/site-packages/miio/integrations/humidifier/zhimi/airhumidifier_miot.py:124
First occurred: 15:03:16 (457 occurrences)
Last logged: 16:57:23

Cannot parse mode: None is not a valid OperationMode
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/integrations/humidifier/zhimi/airhumidifier_miot.py", line 122, in mode
    mode = OperationMode(self.data["mode"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: None is not a valid OperationMode
