### ISSUE TITLE
Local mode on CGDN1 is not working after upgrade to 0.3.9

### ISSUE THREAD

**Issue by andrey-yantsen** [al-one/hass-xiaomi-miot#139]
I see the following message in the logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/sensor.py", line 123, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 868, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 435, in get_properties_for_mapping
    return self.get_properties(
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 269, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by al-one** [comment]
Thank you ! Please try the latest commiit: https://github.com/al-one/hass-xiaomi-miot/commit/50ef98eea9426ba8e500b28a37b2126db4093363

**Comment by andrey-yantsen** [comment]
Yep, works in 0.3.10, thank you!
