### ISSUE TITLE
摄像机可以获取视频流地址但无法显示画面 型号chuangmi.camera.021a04

### ISSUE THREAD

**Issue by WOAZAA** [al-one/hass-xiaomi-miot#140]
开关控制可用，已添加自定义属性video_attribute: 2，每次预览窗口开启时米家app也会推送有人正在使用带屏音响观看监控的通知，但就是没画面，日志与设备属性截图如下

> 2021-07-23 03:49:33 DEBUG (MainThread) [custom_components.xiaomi_miot.camera] Miot camera: 二楼监控 Camera Control stream: None expired: 0
2021-07-23 03:49:33 DEBUG (SyncWorker_20) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request miot api: miotspec/action {'params': {'did': '1023717579', 'siid': 7, 'aiid': 2, 'in': []}} result: {"code":0,"message":"","result":{"did":"1023717579","miid":0,"siid":7,"aiid":2,"code":0,"exe_time":0,"net_cost":0,"ot_cost":0,"otlocalts":0,"oa_cost":0,"_oa_rpc_cost":0}}
2021-07-23 03:49:33 DEBUG (SyncWorker_20) [custom_components.xiaomi_miot] Call miot action to 二楼监控 Camera Control ({'did': '1023717579', 'siid': 7, 'aiid': 2, 'in': []}), result: {'did': '1023717579', 'miid': 0, 'siid': 7, 'aiid': 2, 'code': 0, 'exe_time': 0, 'net_cost': 0, 'ot_cost': 0, 'otlocalts': 0, 'oa_cost': 0, '_oa_rpc_cost': 0}
2021-07-23 03:49:34 DEBUG (SyncWorker_17) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request miot api: miotspec/action {'params': {'did': '1023717579', 'siid': 7, 'aiid': 1, 'in': [2]}} result: {"code":0,"message":"","result":{"did":"1023717579","miid":0,"siid":7,"aiid":1,"code":0,"out":["https://cn02.livestreaming.io.mi.com/hlstranscoder/GCBmNGEzYjg3NjhiZDU0MjU1OWZkMTMwNDc3OTc3YjA0MRgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8"],"exe_time":0,"net_cost":0,"ot_cost":0,"otlocalts":0,"oa_cost":0,"_oa_rpc_cost":0}}
2021-07-23 03:49:34 DEBUG (SyncWorker_17) [custom_components.xiaomi_miot] Call miot action to 二楼监控 Camera Control ({'did': '1023717579', 'siid': 7, 'aiid': 1, 'in': [2]}), result: {'did': '1023717579', 'miid': 0, 'siid': 7, 'aiid': 1, 'code': 0, 'out': ['https://cn02.livestreaming.io.mi.com/hlstranscoder/GCBmNGEzYjg3NjhiZDU0MjU1OWZkMTMwNDc3OTc3YjA0MRgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8'], 'exe_time': 0, 'net_cost': 0, 'ot_cost': 0, 'otlocalts': 0, 'oa_cost': 0, '_oa_rpc_cost': 0}
2021-07-23 03:49:34 DEBUG (MainThread) [custom_components.xiaomi_miot.camera] Get miot camera stream from cloud for 二楼监控 Camera Control: True
2021-07-23 03:49:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140134795263184] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 605, in ws_camera_stream
    url = await _async_stream_endpoint_url(hass, camera, fmt=msg["format"])
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 743, in _async_stream_endpoint_url
    stream = await camera.create_stream()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 374, in create_stream
    source = await self.stream_source()
  File "/config/custom_components/xiaomi_miot/camera.py", line 188, in stream_source
    odt = self._act_start_stream.out_results(result.get('out')) or {
AttributeError: 'bool' object has no attribute 'get'

> 2021-07-23 03:58:54 DEBUG (MainThread) [custom_components.xiaomi_miot] Got new state from 二楼监控 Camera Control: {'camera_control.on': True, 'camera_control.image_rollover': 180, 'camera_control.night_shot': 2, 'camera_control.wdr_mode': True, 'camera_control.glimmer_full_color': True, 'camera_control.recording_mode': 0, 'camera_control.motion_tracking': False, 'camera_control.time_watermark': True, 'bluetooth.bluetooth_switch.error': -704040002, 'camera_stream_for_amazon_alexa.stream_status': 1, 'camera_stream_for_google_home.stream_status': 1, 'motion_detection': True, 'motion_detection.alarm_interval': 5, 'motion_detection.detection_sensitivity': 1, 'motion_detection.motion_detection_start_time': '00:00:00', 'motion_detection.motion_detection_end_time': '23:59:00', 'memory_card_management.status': 0, 'memory_card_management.storage_total_space': 31145984, 'memory_card_management.storage_free_space': 25378816, 'memory_card_management.storage_used_space': 5767168, 'indicator_light.on': True, 'state_updater': 'cloud', 'sub_entities': ['camera_control.on', 'motion_detection-5.motion_detection-1', 'indicator_light-3']}

<img width="1212" alt="屏幕截图 2021-07-23 035328" src="https://user-images.githubusercontent.com/12210261/126702022-eb44399a-7189-4383-b496-0a13e2376ecb.png">

**Comment by Zeunas** [comment]
Same thing happening here with the new update. Had to revert to previous version of the add-on.

**Comment by Zeunas** [comment]
Is there any update on this? I'm still using version 0.3.8 to be able to see the camera steam. Even the new version 0.3.11 has not fixed the issue.

**Comment by al-one** [comment]
请通过下面的shell命令检查流地址是否可被正常转码：
```shell
ffmpeg -v warning -y -protocol_whitelist file,http,https,rtp,udp,tcp,tls,crypto -i 'https://cn.livestreaming.io.mi.com/hlstranscoder/XXXXXX_H265transH264/playlist.m3u8' -an -c:v mjpeg -f mpjpeg xiaomi_camera_video
```

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166
