### ISSUE TITLE
zhimi.airpurifier.v3 小米空气净化器突然不支持了

### ISSUE THREAD

**Issue by liuxyc** [al-one/hass-xiaomi-miot#1401]
### Device model / 设备型号

zhimi.airpurifier.v3

### Component version / 插件版本

	0.7.13

### HA core version / HA版本

2023.11.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

git pull  master最新代码后重启HA，然后就提示： 集成“xiaomi_miot”不再提供此实体

### Entity attributes / 实体属性

unavailable

### Home Assistant Logs / 系统日志

2023-11-17 00:18:55.657 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-17 17:30:01.141 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing xiaomi_miot/diagnostics.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.xiaomi_miot_bak.diagnostics'
2023-11-17 17:30:01.150 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing xiaomi_miot/recorder.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.xiaomi_miot_bak.recorder'
2023-11-17 17:30:01.156 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing xiaomi_miot/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.xiaomi_miot_bak.media_source'
2023-11-17 17:30:01.161 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing xiaomi_miot/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.xiaomi_miot_bak.logbook'
2023-11-17 17:30:06.730 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:30:41.736 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:31:02.234 WARNING (MainThread) [custom_components.xiaomi_miot_bak.camera] 摄像机2(chuangmi.camera.v6): camera alarm playlist is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'date': '2023-11-17', 'timeStamp': 1700213463010, 'playUnits': []}, 'description': '成功', 'ts': 1700213462222}
2023-11-17 17:31:11.741 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:31:41.741 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:32:02.166 WARNING (MainThread) [custom_components.xiaomi_miot_bak.camera] 摄像机2(chuangmi.camera.v6): camera alarm playlist is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'date': '2023-11-17', 'timeStamp': 1700213523002, 'playUnits': []}, 'description': '成功', 'ts': 1700213522159}
2023-11-17 17:32:11.743 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:32:41.743 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:33:02.217 WARNING (MainThread) [custom_components.xiaomi_miot_bak.camera] 摄像机2(chuangmi.camera.v6): camera alarm playlist is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'date': '2023-11-17', 'timeStamp': 1700213583055, 'playUnits': []}, 'description': '成功', 'ts': 1700213582207}
2023-11-17 17:33:11.744 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:33:41.744 ERROR (MainThread) [custom_components.xiaomi_miot_bak.fan] 空气净化器(zhimi.airpurifier.v3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.234, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/9
2023-11-17 17:34:02.201 WARNING (MainThread) [custom_components.xiaomi_miot_bak.camera] 摄像机2(chuangmi.camera.v6): camera alarm playlist is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'date': '2023-11-17', 'timeStamp': 1700213643025, 'playUnits': []}, 'description': '成功', 'ts': 1700213642190}

**Comment by liuxyc** [comment]
之前一直用的好好的

**Comment by al-one** [comment]
`xiaomi_miot_bak` ?
