### ISSUE TITLE
Climate Error on Home Assistant 2024.1

### ISSUE THREAD

**Issue by aurelmarius** [al-one/hass-xiaomi-miot#1475]
### Device model / 设备型号

zhimi_mc2a_ce26_heater

### HA core version / HA版本

2024.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

After updating to Home Assistant 2024.1, climate entities are unavailable.

### Entity attributes / 实体属性

restored: true
hvac_modes: auto, off
min_temp: 18
max_temp: 28
target_temp_step: 1
friendly_name: Mi Smart Space Heater S Heater
supported_features: 1

### Home Assistant Logs / 系统日志

Error while setting up xiaomi_miot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot/climate.py", line 44, in async_setup_entry
    await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 581, in async_setup_config_entry
    await async_setup_platform(hass, c, async_add_entities)
  File "/config/custom_components/xiaomi_miot/climate.py", line 62, in async_setup_platform
    entities.append(MiotClimateEntity(config, srv))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/climate.py", line 161, in __init__
    HVAC_MODE_OFF:  {'list': ['Off', 'Idle', 'None'], 'action': CURRENT_HVAC_OFF},
    ^^^^^^^^^^^^^
NameError: name 'HVAC_MODE_OFF' is not defined

**Comment by al-one** [comment]
- #1461

Upgrade to master branch.

**Comment by aurelmarius** [comment]
> - #1461
> 
> Upgrade to master branch.

Yep, that fixed it. Thanks

**Comment by al-one** [comment]
Fixed in v0.7.15.
