### ISSUE TITLE
Error handling request - camera

### ISSUE THREAD

**Issue by TheBisk** [al-one/hass-xiaomi-miot#151]
Logger: aiohttp.server
Source: custom_components/xiaomi_miot/camera.py:188
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: July 26, 2021, 12:12:18 (949 occurrences)
Last logged: 18:42:40

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 528, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/xiaomi_miot/camera.py", line 245, in async_camera_image
    url = await self.stream_source()
  File "/config/custom_components/xiaomi_miot/camera.py", line 188, in stream_source
    odt = self._act_start_stream.out_results(result.get('out')) or {
AttributeError: 'bool' object has no attribute 'get'

**Comment by Fryk** [comment]
Got same issue, this happened after adding "video_attribute: 2" (without and with it I have no stream)

**Comment by al-one** [comment]
The `AttributeError` has fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/dd061a90870a51d56dacb21713476423b989fd9d.

**Comment by Fryk** [comment]
I've tried manually uploading files to HA, restart. Still same error. Then I've tried wget install, restart. Also no luck.
I confirmed I have newest file in. But still same AttributeError.

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166

**Comment by al-one** [comment]
Fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/1f96a67ddcba3e592069ef25d1a3fc010059c599
