### ISSUE TITLE
rockrobo.vacuum.v1 integration not working

### ISSUE THREAD

**Issue by johnjoemorgan** [al-one/hass-xiaomi-miot#161]
Integration installed correctly and no errors were given,

After restart the the device shows with 3 entities (vacuum, clean area and clean time)

When I place the vacuum entity into the vacuum card and try to start the vacuum I get a pop up error:

Failed to call service vacuum/start. dictionary update sequence element #0 has length 1; 2 is required

No status is reported in the card and no battery life either.

Logs show:

File "/config/custom_components/xiaomi_miot/vacuum.py", line 171, in start
return self.miot_action(self._act_start.service.iid, self._act_start.iid)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1248, in miot_action
eno = dict(result or {}).get('code', 1)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by al-one** [comment]
Please try again after upgrade to the `master` branch and check for `warning` logs.

**Comment by al-one** [comment]
Is this bug solved ?

**Comment by johnjoemorgan** [comment]
No sorry Still the same

**Comment by al-one** [comment]
Need more [debug](https://github.com/al-one/hass-xiaomi-miot#debug) logs when you start the vacuum.

**Comment by johnjoemorgan** [comment]
`2021-08-18 20:50:59 DEBUG (SyncWorker_2) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request miot api: miotspec/prop/get {'params': [{'did': '403354027', 'siid': 2, 'piid': 1}, {'did': '403354027', 'siid': 2, 'piid': 2}, {'did': '403354027', 'siid': 2, 'piid': 4}, {'did': '403354027', 'siid': 2, 'piid': 5}, {'did': '403354027', 'siid': 15, 'piid': 1}, {'did': '403354027', 'siid': 15, 'piid': 2}, {'did': '403354027', 'siid': 15, 'piid': 3}, {'did': '403354027', 'siid': 15, 'piid': 4}, {'did': '403354027', 'siid': 15, 'piid': 5}, {'did': '403354027', 'siid': 15, 'piid': 6}, {'did': '403354027', 'siid': 15, 'piid': 8}, {'did': '403354027', 'siid': 15, 'piid': 9}, {'did': '403354027', 'siid': 15, 'piid': 10}, {'did': '403354027', 'siid': 15, 'piid': 11}, {'did': '403354027', 'siid': 14, 'piid': 1}, {'did': '403354027', 'siid': 14, 'piid': 2}, {'did': '403354027', 'siid': 14, 'piid': 3}, {'did': '403354027', 'siid': 14, 'piid': 4}, {'did': '403354027', 'siid': 14, 'piid': 5}, {'did': '403354027', 'siid': 13, 'piid': 1}, {'did': '403354027', 'siid': 13, 'piid': 2}, {'did': '403354027', 'siid': 13, 'piid': 3}, {'did': '403354027', 'siid': 13, 'piid': 4}, {'did': '403354027', 'siid': 13, 'piid': 5}, {'did': '403354027', 'siid': 13, 'piid': 6}, {'did': '403354027', 'siid': 13, 'piid': 7}, {'did': '403354027', 'siid': 13, 'piid': 8}, {'did': '403354027', 'siid': 13, 'piid': 9}, {'did': '403354027', 'siid': 12, 'piid': 1}, {'did': '403354027', 'siid': 10, 'piid': 1}, {'did': '403354027', 'siid': 10, 'piid': 2}, {'did': '403354027', 'siid': 10, 'piid': 3}, {'did': '403354027', 'siid': 10, 'piid': 4}, {'did': '403354027', 'siid': 10, 'piid': 5}, {'did': '403354027', 'siid': 10, 'piid': 6}, {'did': '403354027', 'siid': 10, 'piid': 7}, {'did': '403354027', 'siid': 10, 'piid': 8}, {'did': '403354027', 'siid': 10, 'piid': 9}, {'did': '403354027', 'siid': 10, 'piid': 10}, {'did': '403354027', 'siid': 9, 'piid': 1}, {'did': '403354027', 'siid': 9, 'piid': 2}, {'did': '403354027', 'siid': 8, 'piid': 1}, {'did': '403354027', 'siid': 7, 'piid': 1}, {'did': '403354027', 'siid': 6, 'piid': 1}, {'did': '403354027', 'siid': 6, 'piid': 6}, {'did': '403354027', 'siid': 5, 'piid': 1}, {'did': '403354027', 'siid': 4, 'piid': 3}, {'did': '403354027', 'siid': 4, 'piid': 5}, {'did': '403354027', 'siid': 3, 'piid': 6}, {'did': '403354027', 'siid': 3, 'piid': 7}, {'did': '403354027', 'siid': 3, 'piid': 8}]} result: {"code":0,"message":"","result":[{"did":"403354027","siid":2,"piid":1,"code":-704053100},{"did":"403354027","siid":2,"piid":2,"value":true,"code":0,"updateTime":1629286790},{"did":"403354027","siid":2,"piid":4,"value":1,"code":0,"updateTime":1629291047},{"did":"403354027","siid":2,"piid":5,"value":0,"code":0,"updateTime":1629286790},{"did":"403354027","siid":15,"piid":1,"code":-704053100},{"did":"403354027","siid":15,"piid":2,"code":-704053100},{"did":"403354027","siid":15,"piid":3,"code":-704053100},{"did":"403354027","siid":15,"piid":4,"code":-704053100},{"did":"403354027","siid":15,"piid":5,"code":-704053100},{"did":"403354027","siid":15,"piid":6,"code":-704053100},{"did":"403354027","siid":15,"piid":8,"code":-704053100},{"did":"403354027","siid":15,"piid":9,"value":0,"code":0,"updateTime":1622352046},{"did":"403354027","siid":15,"piid":10,"value":1,"code":0,"updateTime":1629171807},{"did":"403354027","siid":15,"piid":11,"code":-704053100},{"did":"403354027","siid":14,"piid":1,"value":"80:70:a1:52:a7:d6:4","code":0,"updateTime":1629286788},{"did":"403354027","siid":14,"piid":2,"code":-704053100},{"did":"403354027","siid":14,"piid":3,"code":-704053100},{"did":"403354027","siid":14,"piid":4,"code":-704053100},{"did":"403354027","siid":14,"piid":5,"code":-704053100},{"did":"403354027","siid":13,"piid":1,"value":80522,"code":0,"updateTime":1629281358},{"did":"403354027","siid":13,"piid":2,"code":-704053100},{"did":"403354027","siid":13,"piid":3,"code":-704053100},{"did":"403354027","siid":13,"piid":4,"code":-704053100},{"did":"403354027","siid":13,"piid":5,"code":-704053100},{"did":"403354027","siid":13,"piid":6,"code":-704053100},{"did":"403354027","siid":13,"piid":7,"code":-704053100},{"did":"403354027","siid":13,"piid":8,"code":-704053100},{"did":"403354027","siid":13,"piid":9,"code":-704053100},{"did":"403354027","siid":12,"piid":1,"value":2407800,"code":0,"updateTime":1629281349},{"did":"403354027","siid":10,"piid":1,"code":-704053100},{"did":"403354027","siid":10,"piid":2,"code":-704053100},{"did":"403354027","siid":10,"piid":3,"code":-704053100},{"did":"403354027","siid":10,"piid":4,"code":-704053100},{"did":"403354027","siid":10,"piid":5,"code":-704053100},{"did":"403354027","siid":10,"piid":6,"code":-704053100},{"did":"403354027","siid":10,"piid":7,"code":-704053100},{"did":"403354027","siid":10,"piid":8,"code":-704053100},{"did":"403354027","siid":10,"piid":9,"code":-704053100},{"did":"403354027","siid":10,"piid":10,"code":-704053100},{"did":"403354027","siid":9,"piid":1,"code":-704053100},{"did":"403354027","siid":9,"piid":2,"code":-704053100},{"did":"403354027","siid":8,"piid":1,"value":"power","code":0,"updateTime":1629123513},{"did":"403354027","siid":7,"piid":1,"code":-704053100},{"did":"403354027","siid":6,"piid":1,"value":1,"code":0,"updateTime":1629172599},{"did":"403354027","siid":6,"piid":6,"code":-704053100},{"did":"403354027","siid":5,"piid":1,"value":false,"code":0,"updateTime":1627219983},{"did":"403354027","siid":4,"piid":3,"value":80,"code":0,"updateTime":1629270285},{"did":"403354027","siid":4,"piid":5,"value":666,"code":0,"updateTime":1629270286},{"did":"403354027","siid":3,"piid":6,"value":5,"code":0,"updateTime":1629290039},{"did":"403354027","siid":3,"piid":7,"value":73,"code":0,"updateTime":1629290588},{"did":"403354027","siid":3,"piid":8,"value":29.4,"code":0,"updateTime":1629289388}]}
2021-08-18 20:50:59 DEBUG (MainThread) [custom_components.xiaomi_miot] Got new state from Twins Air Air Purifier: {'air_purifier.fault.error': '-704053100 The device cannot be operated in its current state', 'air_purifier.on': True, 'air_purifier.fan_level': 1, 'air_purifier.mode': 0, 'others.app_extra.error': '-704053100 The device cannot be operated in its current state', 'others.main_channel.error': '-704053100 The device cannot be operated in its current state', 'others.slave_channel.error': '-704053100 The device cannot be operated in its current state', 'others.cola.error': '-704053100 The device cannot be operated in its current state', 'others.buttom_door.error': '-704053100 The device cannot be operated in its current state', 'others.reboot_cause.error': '-704053100 The device cannot be operated in its current state', 'others.hw_version.error': '-704053100 The device cannot be operated in its current state', 'others.iic_error_count': 0, 'others.manual_level': 1, 'others.country_code.error': '-704053100 The device cannot be operated in its current state', 'rfid.rfid_tag': '80:70:a1:52:a7:d6:4', 'rfid.rfid_factory_id.error': '-704053100 The device cannot be operated in its current state', 'rfid.rfid_product_id.error': '-704053100 The device cannot be operated in its current state', 'rfid.rfid_time.error': '-704053100 The device cannot be operated in its current state', 'rfid.rfid_serial_num.error': '-704053100 The device cannot be operated in its current state', 'aqi.purify_volume': 80522, 'aqi.average_aqi.error': '-704053100 The device cannot be operated in its current state', 'aqi.average_aqi_cnt.error': '-704053100 The device cannot be operated in its current state', 'aqi.aqi_zone.error': '-704053100 The device cannot be operated in its current state', 'aqi.sensor_state.error': '-704053100 The device cannot be operated in its current state', 'aqi.aqi_goodh.error': '-704053100 The device cannot be operated in its current state', 'aqi.aqi_runstate.error': '-704053100 The device cannot be operated in its current state', 'aqi.aqi_state.error': '-704053100 The device cannot be operated in its current state', 'aqi.aqi_updata_heartbeat.error': '-704053100 The device cannot be operated in its current state', 'use_time': 2407800, 'motor_speed.motor_strong.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_high.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_med.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_med_l.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_low.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_silent.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_favorite.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.motor_set_speed.error': '-704053100 The device cannot be operated in its current state', 'motor_speed.favorite_fan_level.error': '-704053100 The device cannot be operated in its current state', 'filter_time.filter_max_time.error': '-704053100 The device cannot be operated in its current state', 'filter_time.filter_hour_debug.error': '-704053100 The device cannot be operated in its current state', 'button.button_pressed': 'power', 'physical_controls_locked.error': '-704053100 The device cannot be operated in its current state', 'indicator_light.brightness': 1, 'indicator_light.on.error': '-704053100 The device cannot be operated in its current state', 'alarm': False, 'filter.filter_life_level': 80, 'filter.filter_used_time': 666, 'environment.pm2_5_density': 5, 'environment.relative_humidity': 73, 'environment.temperature': 29.4, 'state_updater': 'cloud', 'sub_entities': ['environment-3.pm2_5_density-6', 'environment-3.relative_humidity-7', 'environment-3.temperature-8', 'filter-4.filter_life_level-3', 'filter-4.filter_used_time-5', 'physical_controls_locked-7.physical_controls_locked-1', 'indicator_light-6']}
2021-08-18 20:51:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2627782184] dictionary update sequence element #0 has length 1; 2 is required
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 387, in async_start
await self.hass.async_add_executor_job(self.start)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_miot/vacuum.py", line 171, in start
return self.miot_action(self._act_start.service.iid, self._act_start.iid)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1248, in miot_action
eno = dict(result or {}).get('code', 1)
ValueError: dictionary update sequence element #0 has length 1; 2 is required`

**Comment by johnjoemorgan** [comment]
Logger: miio.miioprotocol
Source: /usr/local/lib/python3.9/site-packages/miio/miioprotocol.py:240
First occurred: 14:40:51 (32 occurrences)
Last logged: 14:51:45

Got error when receiving: timed out

**Comment by al-one** [comment]
Add this device via Xiaomi account.
