### ISSUE TITLE
Cover babai.curtain.m515e becomes intermittently unavailable - Error: byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by theodorx7** [al-one/hass-xiaomi-miot#1614]
### Device model / 设备型号

babai.curtain.m515e

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Periodically, an error appears in the log and after its occurrence the device becomes inaccessible.
I have 3 devices of this model and this problem periodically occurs with each of them at different periods of time.

### Entity attributes / 实体属性

current_position: 2
model: babai.curtain.m515e
lan_ip: 192.168.1.199
mac_address: 58:B6:23:CE:DB:00
entity_class: MiotCoverEntity
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:babai-m515e:1:0000C805
curtain.current_position: 2
curtain.target_position: 2
curtain.mode: 1
state_updater: lan
device_class: curtain
friendly_name: Левое окно curtain
supported_features: 15

### Home Assistant Logs / 系统日志

ERROR (MainThread) [homeassistant.helpers.entity] Update for cover.babai_m515e_072e_curtain fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
await self.async_update()
File "/config/custom_components/xiaomi_miot/cover.py", line 132, in async_update
await super().async_update()
File "/config/custom_components/xiaomi_miot/__init__.py", line 1414, in async_update
results = await self.hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/xiaomi_miot/__init__.py", line 702, in get_properties_for_mapping
return self.get_properties(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 240, in get_properties
values.extend(self.send(property_getter, _props[:max_properties]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 107, in send
return self._protocol.send(
^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 202, in send
self.__id = payload["id"]
~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str

**Comment by gieljnssns** [comment]
```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.device.roborock.vacuum.a15
Source: helpers/update_coordinator.py:379
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:49:55 (1 occurrences)
Last logged: 11:49:55

Unexpected error fetching b0:4a:39:40:3b:25-miot_status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 493, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 795, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 120, in get_miot_props
    if dic := self.get_miio_props(device):
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 78, in get_miio_props
    vls = device.send(c['method'], pms)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
```

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by theodorx7** [comment]
> Try master branch.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

Now here is the error:


2025-01-09 14:53:48.473 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.babai.curtain.m515e] Unexpected error fetching 58:b6:23:ce:db:00-chunk_1 data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 850, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1351, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1344, in get_properties_for_mapping
    return self.get_properties(
           ~~~~~~~~~~~~~~~~~~~^
        properties,
        ^^^^^^^^^^^
        property_getter='get_properties',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        max_properties=max_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str

**Comment by theodorx7** [comment]
> Try master branch.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

Now here is the error:




2025-01-09 14:53:48.473 ERROR (MainThread) [custom_components.xiaomi_miot.core.device.babai.curtain.m515e] Unexpected error fetching 58:b6:23:ce:db:00-chunk_1 data

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 850, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1351, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1344, in get_properties_for_mapping
    return self.get_properties(
           ~~~~~~~~~~~~~~~~~~~^
        properties,
        ^^^^^^^^^^^
        property_getter='get_properties',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        max_properties=max_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
```

**Comment by theodorx7** [comment]
On component version 1.0.9, the following error always occurs when HA is launched and then periodically during system operation:
Registrar: custom_components.xiaomi_miot.core.device.babai.curtain.m515e
Source: helpers/update_coordinator.py:380


```
Unexpected error fetching 58:b6:23:ce:db:00-chunk_1 data
Unexpected error fetching 58:b6:23:cf:07:2e-chunk_1 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 536, in _update
    result = await self.update_miot_status(mapping, chunk_services=chunk_services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 886, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1402, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1395, in get_properties_for_mapping
    return self.get_properties(
           ~~~~~~~~~~~~~~~~~~~^
        properties,
        ^^^^^^^^^^^
        property_getter='get_properties',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        max_properties=max_properties,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
```
