### ISSUE TITLE
Vacuum: Roidmi EVE Plus (model: roidmi.vacuum.v60)

### ISSUE THREAD

**Issue by poisondima** [al-one/hass-xiaomi-miot#163]
Hi, I connected the vacuum cleaner "Roidmi EVE Plus", does not correctly indicate the current status on charging.
It does not work the cleaning of a particular room in the local mode (LAN). 
Information here -> http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:roidmi-v60:2
![ha_vacuum](https://user-images.githubusercontent.com/39500249/129470908-d02e0fac-4b30-4643-8585-8174b45dfae4.jpg)

**Comment by al-one** [comment]
The vacuum entity state fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/6a8fa2274d2c165a7d9bcadb59fba599e19add81.

About cleaning rooms, please show me the relevant debug logs.

**Comment by poisondima** [comment]
> The vacuum entity state fixed in commit: 6a8fa22.

Thank you, I checked the status is correct.

**Comment by poisondima** [comment]
I start cleaning like this:
```
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.vacuum_cleaner_robot_cleaner
            did: !secret xiaomi_cloud_did
            siid: 14
            aiid: 1
            params: [2,"{\"mapId\":1626189155,\"segmentId\":[2]}"]
```
And get an error like this:
```
2021-08-16 18:13:26 INFO (SyncWorker_4) [custom_components.xiaomi_miot] Call miot action to Vacuum Cleaner Robot Cleaner ({'did': '441961352', 'siid': 14, 'aiid': 1, 'in': [2, '{"mapId":1626189155,"segmentId":[2]}']}) failed: None
2021-08-16 18:13:30 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for Vacuum Cleaner Robot Cleaner: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 10}, 'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'map.clean_path': {'siid': 13, 'piid': 2}, 'map.restricted_zone': {'siid': 13, 'piid': 3}, 'map.auto_area': {'siid': 13, 'piid': 4}, 'map.map_memory': {'siid': 13, 'piid': 5}, 'map.map_name': {'siid': 13, 'piid': 6}, 'map.use_auto_area': {'siid': 13, 'piid': 7}, 'map.path_type': {'siid': 13, 'piid': 8}, 'custom.mop': {'siid': 8, 'piid': 1}, 'custom.work_station_freq': {'siid': 8, 'piid': 2}, 'custom.timing': {'siid': 8, 'piid': 6}, 'custom.clean_area': {'siid': 8, 'piid': 7}, 'custom.uid': {'siid': 8, 'piid': 8}, 'custom.auto_boost': {'siid': 8, 'piid': 9}, 'custom.forbid_mode': {'siid': 8, 'piid': 10}, 'custom.water_level': {'siid': 8, 'piid': 11}, 'custom.total_clean_time': {'siid': 8, 'piid': 13}, 'custom.total_clean_areas': {'siid': 8, 'piid': 14}, 'custom.clean_counts': {'siid': 8, 'piid': 18}, 'custom.clean_time': {'siid': 8, 'piid': 19}, 'custom.double_clean': {'siid': 8, 'piid': 20}, 'custom.edge_sweep': {'siid': 8, 'piid': 21}, 'custom.led_switch': {'siid': 8, 'piid': 22}, 'custom.lidar_collision': {'siid': 8, 'piid': 23}, 'custom.station_key': {'siid': 8, 'piid': 24}, 'custom.station_led': {'siid': 8, 'piid': 25}, 'custom.current_audio': {'siid': 8, 'piid': 26}, 'custom.progress': {'siid': 8, 'piid': 28}, 'custom.station_type': {'siid': 8, 'piid': 29}, 'custom.voice_conf': {'siid': 8, 'piid': 30}, 'brush_left_time-15-1': {'siid': 15, 'piid': 1}, 'brush_life_level-15-2': {'siid': 15, 'piid': 2}, 'brush_left_time-12-1': {'siid': 12, 'piid': 1}, 'brush_life_level-12-2': {'siid': 12, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 11, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 11, 'piid': 2}, 'filter.filter_life_level': {'siid': 10, 'piid': 1}, 'filter.filter_left_time': {'siid': 10, 'piid': 2}, 'speaker.volume': {'siid': 9, 'piid': 1}, 'speaker.mute': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10
2021-08-16 18:13:30 ERROR (MainThread) [homeassistant.components.automation.vacuum_get_miot_property] vacuum_get_miot_property: Error executing script. Invalid data for call_service at pos 4: expected float for dictionary value @ data['value']
2021-08-16 18:13:30 ERROR (MainThread) [homeassistant.components.automation.vacuum_get_miot_property] Error while executing automation automation.vacuum_get_miot_property: expected float for dictionary value @ data['value']

```

**Comment by al-one** [comment]
Call this service via [developer tools](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.call_action), and add the parameter `throw: true`:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.vacuum_cleaner_robot_cleaner
  did: 1234567890 # your did
  siid: 14
  aiid: 1
  params:
    - 2
    - '{"mapId":1626189155,"segmentId":[2]}'
  throw: true
```
Find result from the notification in the left sidebar.

**Comment by poisondima** [comment]
![изображение](https://user-images.githubusercontent.com/39500249/129686364-8ffed27a-bac0-4332-a422-ea4c7969f3e6.png)
```
2021-08-17 10:52:28 WARNING (SyncWorker_1) [custom_components.xiaomi_miot] Call miot action to Vacuum Cleaner Robot Cleaner ({'did': '441961352', 'siid': 14, 'aiid': 1, 'in': [2, '{"mapId":1626189155,"segmentId":[2]}']}) failed: {'code': -9999, 'message': 'user ack timeout'}
2021-08-17 10:52:28 INFO (SyncWorker_1) [custom_components.xiaomi_miot] Call miot action to Vacuum Cleaner Robot Cleaner ({'did': '441961352', 'siid': 14, 'aiid': 1, 'in': [2, '{"mapId":1626189155,"segmentId":[2]}']}) failed: None
2021-08-17 10:52:28 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Miot action result: None
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/xiaomi_miot/__init__.py", line 348, in async_service_handler
await getattr(dvc, fun)(**params)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1285, in async_miot_action
return await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1281, in miot_action
raise Warning(f'Miot action result: {result}')
Warning: Miot action result: None
2021-08-17 10:52:28 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1846288904] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/xiaomi_miot/__init__.py", line 348, in async_service_handler
await getattr(dvc, fun)(**params)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1285, in async_miot_action
return await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1281, in miot_action
raise Warning(f'Miot action result: {result}')
Warning: Miot action result: None
```

**Comment by al-one** [comment]
Maybe you need to enable call action in the cloud for this device, [Add custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) to the entity:
```yaml
# customize.yaml
vacuum.vacuum_cleaner_robot_cleaner:
  miot_cloud_action: true
```
> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute

**Comment by poisondima** [comment]
I added it to customize.yaml:
```yaml
  miot_cloud: true          # Enable miot cloud for entity (read, write, action)
  #miot_cloud_write: true  # (Optional) Enable miot cloud (only write)
  #miot_cloud_action: true # (Optional) Enable miot cloud (only action)
  #miot_local: true        # Force to read and write data in LAN
```
When I run the command I get this (the vacuum cleaner starts cleaning):
`Warning: Miot action result: {'did': '441961352', 'miid': 0, 'siid': 14, 'aiid': 1, 'code': 0, 'exe_time': 0, 'net_cost': 0, 'ot_cost': 0, 'otlocalts': 0, 'oa_cost': 0, '_oa_rpc_cost': 0}`

In the attributes of the vacuum cleaner such values:
```
state_updater: cloud
miot_cloud: true
```
Do I understand correctly that now all updates and changes go through the cloud, not the LAN?
Is it possible to make all updates and changes go through the LAN, and only the cleaning call goes through the cloud?

**Comment by al-one** [comment]
```yaml
# customize.yaml
vacuum.vacuum_cleaner_robot_cleaner:
  miot_local: true
  miot_cloud: false
  miot_cloud_action: true
```
In this way, call action in xiaomi cloud and update state in the LAN.

**Comment by poisondima** [comment]
Thank you, it works!
Can't you do a LAN cleanup run without the cloud?

**Comment by al-one** [comment]
Your device cannot execute the action in the LAN, maybe you can try this way without cloud:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: vacuum.vacuum_cleaner_robot_cleaner
  siid: 2 # service: vacuum
  aiid: 1 # action: start-room-sweep
  params:
    - '2,3' # room-ids
```

**Comment by poisondima** [comment]
Yes, that code works, LAN cleanup, thank you very much!

**Comment by undy27** [comment]
Hi. I’ve tried to perform single-room cleaning in local mode, which corresponds to aiid=3, testing with ‘low’ numbers (since I don’t know the room codes), but it doesn’t work. If I use aiid=1 it does clean, but all the rooms. I understand that cloud mode has been ruled out since Xiaomi implemented login with 2FA and captcha. Does single-room cleaning currently work in local mode with this vacuum?

**Comment by poisondima** [comment]
Unfortunately, I tried to run the cleaning locally a long time ago, but it didn't work, so now I use cloud-based room cleaning. Where XXX is the your mapId.
```
        - service: xiaomi_miot.call_action
          data:
            entity_id: vacuum.vacuum_cleaner_robot_cleaner
            did: !secret xiaomi_cloud_did
            siid: 14
            aiid: 1
            params: [2,"{\\"mapId\\":XXX,\\"segmentId\\":[1]}"]
```

**Comment by undy27** [comment]
Cloud mode would work for me, but I don’t know how to obtain the mapId, since it’s not shown in the entity’s attributes. On the other hand, I think the Miot integration doesn’t support individual room cleaning. Apart from aiid=3 (corresponding to the start-room-sweep action) not working, if I query property 9 with siid=2 to get the room-ids, it returns the error ‘-4003 Property/Action/Event does not exist.’

**Comment by poisondima** [comment]
Here is a [manual ](https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912)on how to obtain the map number and room number when you start cleaning through the app.
