### ISSUE TITLE
Can not turn on/off switch(no attribute 'async_turn_on')

### ISSUE THREAD

**Issue by timtimno1** [al-one/hass-xiaomi-miot#168]
[picture1](https://timtimno1.ddns.net/s/mgnx797MXNsznwg)
[picture2](https://timtimno1.ddns.net/s/do75DWx5nMSPcdn)

My product is a xiaomi.aircondition.c13

This is my log:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:689
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:06:07 (7 occurrences)
Last logged: 12:38:19

[139717407091248] 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'
[139717288338576] 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'
[139717288338576] 'MiotSwitchSubEntity' object has no attribute 'async_turn_off'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/local/lib/python3.9/site-packages/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 689, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'

```

**Comment by al-one** [comment]
Fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/92f49d7832e1355d0625d0b4e95532f193bccc96

**Comment by timtimno1** [comment]
Thanks!!
