### ISSUE TITLE
Blocking call inside event loop

### ISSUE THREAD

**Issue by luca-angemi** [al-one/hass-xiaomi-miot#1694]
HA 2024.6.0b0

```
Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file: (offender: /config/custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
```

**Comment by hmmbob** [comment]
Got several other line numbers as well:

> 2024-06-01 16:22:19.564 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file: (offender: /config/custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:)
2024-06-01 16:22:19.589 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 40: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 62: with open(tzpath) as tzfile:)
2024-06-01 16:22:19.597 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 40: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 62: with open(tzpath) as tzfile:)
2024-06-01 16:22:19.605 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 40: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 97: with open(tzpath, "rt") as tzfile:)
2024-06-01 16:22:19.617 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 40: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 97: with open(tzpath, "rt") as tzfile:)
2024-06-01 16:22:19.636 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 40: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 189: with open(tzpath, "rb") as tzfile:)
2024-06-01 16:40:59.187 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/utils.py, line 15: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil: (offender: /config/custom_components/xiaomi_miot/core/utils.py, line 15: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil:)

The timezone ones might be related to https://developers.home-assistant.io/blog/2024/05/19/fix_zoneinfo_blocking_io/

**Comment by dawiinci** [comment]
Please check here for a solution:
https://github.com/dummylabs/thewatchman/issues/135#issuecomment-2155726347

Maybe this fix can be done with this integration as well.

Please do so fast as this flooding makes HA crash.

**Comment by al-one** [comment]
Oh, I found one more warning:

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 1:20:50 AM (1 occurrences)
Last logged: 1:20:50 AM

Detected blocking call to open with args ('/config/custom_components/xiaomi_miot/core/../manifest.json',) inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/utils.py, line 118: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil: (offender: /config/custom_components/xiaomi_miot/core/utils.py, line 118: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/xiaomi_miot/config_flow.py", line 615, in async_step_user await check_miio_device(self.hass, user_input, errors) File "/config/custom_components/xiaomi_miot/config_flow.py", line 107, in check_miio_device await async_analytics_track_event( File "/config/custom_components/xiaomi_miot/core/utils.py", line 223, in async_analytics_track_event 'ver': get_manifest('version', ''), File "/config/custom_components/xiaomi_miot/core/utils.py", line 118, in get_manifest with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil:
```

_Originally posted by @il77781 in https://github.com/al-one/hass-xiaomi-miot/discussions/1905#discussioncomment-11160583_
