### ISSUE TITLE
小米空調開關eco/dryer/sleep mode執行失敗

### ISSUE THREAD

**Issue by evan85** [al-one/hass-xiaomi-miot#171]
Model：xiaomi.aircondition.mc5

彈出訊息：
服務 switch/turn_on 執行失敗。 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'

Log:
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:689
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 06:50:44 (7 occurrences)
Last logged: 12:15:15

[140269155498544] 'MiotSwitchSubEntity' object has no attribute 'async_turn_off'
[140269197679824] 'MiotSwitchSubEntity' object has no attribute 'async_turn_off'
[140269197679824] 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'
[140269370861744] 'MiotSwitchSubEntity' object has no attribute 'async_turn_on'
[140269370861744] 'MiotSwitchSubEntity' object has no attribute 'async_turn_off'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 689, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'MiotSwitchSubEntity' object has no attribute 'async_turn_off'

**Comment by al-one** [comment]
The bug was fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/92f49d7832e1355d0625d0b4e95532f193bccc96 , Please upgrade to [v0.4.0b1](https://github.com/al-one/hass-xiaomi-miot/releases/tag/v0.4.0b1).

**Comment by evan85** [comment]
Thanks very much
