### ISSUE TITLE
Xiaomi Smart Speaker (IR Control) not responding

### ISSUE THREAD

**Issue by azeos** [al-one/hass-xiaomi-miot#1712]
### Device model / 设备型号

xiaomi.wifispeaker.l05g

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.6.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I was able to add mi [Xiaomi Smart Speaker (IR Control)](https://home.miot-spec.com/s/xiaomi.wifispeaker.l05g) to Home Assistant, but I can't control it or get any state.

I tried with automatic and token integrations modes.

### Entity attributes / 实体属性

media_player.xiaomi_l05g_9002_play_control (idle):  

```
model: xiaomi.wifispeaker.l05g
lan_ip: xxx
mac_address: xxx
entity_class: MiotMediaPlayerEntity
home_room: xxx
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05g:1
attribution: Support TTS through service
play_control.playing_state.error: -704220043 Property value error
play_control.play_loop_mode.error: -704220043 Property value error
clock.on.error: -704220043 Property value error
clock.status.error: -704220043 Property value error
clock.fault.error: -704220043 Property value error
clock.ringtone.error: -704220043 Property value error
microphone.mute.error: -704220043 Property value error
speaker.volume.error: -704220043 Property value error
speaker.mute.error: -704220043 Property value error
state_updater: cloud
sub_entities: intelligent_speaker-5.wake_up-1, intelligent_speaker-5.play_music-5, clock-6.stop_alarm-1, intelligent_speaker-5.play_text-3, intelligent_speaker-5.execute_text_directive-4
miot_action_error: -704083036 Device operation timeout
miot_action_result: 
did: '561259112'
miid: 0
siid: 3
aiid: 2
code: -704083036
exe_time: 0
withLatency: 0

device_class: speaker
friendly_name: Xiaomi Smart Speaker (IR Control) Play Control
supported_features: 22077
```

### Home Assistant Logs / 系统日志

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.media_player
Fuente: custom_components/xiaomi_miot/__init__.py:1882
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 00:11:06 (1 ocurrencias)
Último inicio de sesión: 00:11:06

Xiaomi Smart Speaker (IR Control)(xiaomi.wifispeaker.l05g): Set miot property {'did': '561259112', 'siid': 2, 'piid': 1, 'value': 91} failed, result: {'did': '561259112', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'code': -704083036, 'exe_time': 0}
```

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.core.xiaomi_cloud
Fuente: custom_components/xiaomi_miot/core/xiaomi_cloud.py:217
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 11 de junio de 2024, 16:27:20 (3 ocurrencias)
Último inicio de sesión: 00:10:47

Request xiaomi api: https://api2.mina.mi.com/admin/v2/device_list {'presence': False, 'master': False} failed, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1></body></html>
Request xiaomi api: v2/message/v2/typelist {} failed, response: internal server err
```

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.core.xiaomi_cloud
Fuente: custom_components/xiaomi_miot/core/xiaomi_cloud.py:644
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 11 de junio de 2024, 16:27:20 (2 ocurrencias)
Último inicio de sesión: 00:10:47

Unauthorized while executing request to https://api2.mina.mi.com/admin/v2/device_list, logged out.
```

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.sensor
Fuente: custom_components/xiaomi_miot/sensor.py:852
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 11 de junio de 2024, 16:25:55 (2 ocurrencias)
Último inicio de sesión: 00:10:03

Get xiaomi scene history for 6732877378 106001030028 failed: {'code': 0, 'message': '成功', 'result': {'history': []}}
```

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.sensor
Fuente: helpers/update_coordinator.py:325
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 11 de junio de 2024, 17:30:16 (6 ocurrencias)
Último inicio de sesión: 14 de junio de 2024, 12:31:05

Error requesting xiaomi_miot-mihome-message-6732877378 data: HTTPSConnectionPool(host='us.api.io.mi.com', port=443): Max retries exceeded with url: /app/v2/message/v2/typelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5c93a270>: Failed to establish a new connection: [Errno -3] Try again'))
Error requesting xiaomi_miot-mihome-message-6732877378 data: HTTPSConnectionPool(host='us.api.io.mi.com', port=443): Max retries exceeded with url: /app/v2/message/v2/typelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x595841f8>: Failed to establish a new connection: [Errno -3] Try again'))
Error requesting xiaomi_miot-mihome-scene-history-6732877378_106001030028 data: HTTPSConnectionPool(host='us.api.io.mi.com', port=443): Max retries exceeded with url: /app/scene/history (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5eab4a50>: Failed to establish a new connection: [Errno -3] Try again'))
Error requesting xiaomi_miot-mihome-scene-history-6732877378_106001030028 data: HTTPSConnectionPool(host='us.api.io.mi.com', port=443): Max retries exceeded with url: /app/scene/history (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5958a630>: Failed to establish a new connection: [Errno -3] Try again'))
Error requesting xiaomi_miot-mihome-message-6732877378 data: HTTPSConnectionPool(host='us.api.io.mi.com', port=443): Max retries exceeded with url: /app/v2/message/v2/typelist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5958a048>: Failed to establish a new connection: [Errno -3] Try again'))
```

```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.xiaomi_miot.core.xiaomi_cloud
Fuente: custom_components/xiaomi_miot/core/xiaomi_cloud.py:628
integración: Xiaomi Miot Auto (documentación, problemas)
Ocurrió por primera vez: 13 de junio de 2024, 02:00:02 (1 ocurrencias)
Último inicio de sesión: 13 de junio de 2024, 02:00:02

Error while decrypting response of request to https://us.api.io.mi.com/app/v2/message/v2/typelist :internal server err
```
```

Registrador: homeassistant.util.loop
Fuente: util/loop.py:84
Ocurrió por primera vez: 11 de junio de 2024, 16:25:44 (2 ocurrencias)
Último inicio de sesión: 11 de junio de 2024, 16:25:52

Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file: (offender: /config/custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component result = await task File "/config/custom_components/xiaomi_miot/__init__.py", line 208, in async_setup with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:
Detected blocking call to open inside the event loop by custom integration 'smartir' at custom_components/smartir/climate.py, line 85: with open(device_json_path) as j: (offender: /config/custom_components/smartir/climate.py, line 85: with open(device_json_path) as j:), please report it to the author of the 'smartir' custom integration Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 319, in async_setup_platform await self._platforms[key].async_setup(platform_config, discovery_info) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 303, in async_setup await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/smartir/climate.py", line 85, in async_setup_platform with open(device_json_path) as j:
```

**Comment by gitmed1** [comment]
I have the same problem, is anyone taking charge of this report?

**Comment by azeos** [comment]
I didn't solve it, it doesn't work with the other Xiaomi integration neither.

**Comment by naklovas** [comment]
I solved it! Please at the beggining stop trying mi home app first. With two buttons reset the device and connect to google home. Once you register your device to google home open mi home app. There is a button in google home for opening mi home app and thats bullshit. Once you opened mi home app find the device named smart speaker remote something... And when pairing screen appears first you need to reset aaand this time the button in the middle works.!!! Reset with button in the middle and you can connect to wifi device broadcasts. And thats te surprise of the century :) and then the installation finishes smooth. And you can use your remote and program it inside mi home app.ı've created some autmations which open and close TV and aircon. Enjoy your smarter home :)
