### ISSUE TITLE
3 To 1 Thermostat SR-Mesh lacks a ventilation switch, and there is confusion in the logic between air conditioning and floor heating.

### ISSUE THREAD

**Issue by sevenmade** [al-one/hass-xiaomi-miot#1734]
### Device model / 设备型号

bean.airrtc.nt01

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.6.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The 3 To 1 Thermostat SR-Mesh lacks a ventilation switch, and there is confusion in the logic between air conditioning and floor heating. The controls for floor heating and air conditioning are reversed.

### Entity attributes / 实体属性

hvac_modes: auto, cool, heat, dry, fan_only, off
min_temp: 16
max_temp: 35
target_temp_step: 1
fan_modes: auto, low, medium, high
current_temperature: 33
temperature: 28
current_humidity: 37
fan_mode: auto
hvac_action: off
model: bean.airrtc.nt01
lan_ip: 
mac_address: B8:50:D8:0D:ED:29
entity_class: MiotClimateEntity
home_room: 公司 客厅
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:bean-nt01:1:0000C822
air_conditioner.on: false
air_conditioner.mode: 4
air_conditioner.fault: 0
target_temperature-2-4: 28
adv_setting.three_one_mode: 13
adv_setting.air_temp_up: 30
adv_setting.air_temp_down: 16
adv_setting.hot_temp_up: 32
adv_setting.hot_temp_down: 18
adv_setting.temp_correct: 0
adv_setting.humi_correct: 0
environment.relative_humidity: 37
environment.temperature: 33
fan_control.fan_level: 0
thermostat.on: false
thermostat.target_temperature: 27
air_fresh.on: true
air_fresh.fault: 0
air_fresh.mode: 1
air_fresh.fan_level: 3
state_updater: cloud
sub_entities: air_conditioner-2.on-1, environment-6.relative_humidity-1, environment-6.temperature-2
friendly_name: 3 To 1 Thermostat SR-Mesh Air Conditioner
supported_features: 393

### Home Assistant Logs / 系统日志

2024-06-27 17:31:17.002 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edge_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 17:31:17.005 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 17:31:17.007 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 17:31:17.009 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 17:31:17.012 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 17:31:18.083 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-06-27 17:31:21.878 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-27 17:31:24.323 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file: (offender: /config/custom_components/xiaomi_miot/__init__.py, line 208: with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component
result = await task
File "/config/custom_components/xiaomi_miot/__init__.py", line 208, in async_setup
with open(os.path.dirname(__file__) + '/core/miot_specs_extend.json') as file:
2024-06-27 17:31:24.843 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:24.843 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:24.843 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_air_conditioner (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) implements HVACMode(s): auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:24.844 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_thermostat (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:24.844 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_thermostat (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:24.844 WARNING (MainThread) [homeassistant.components.climate] Entity xiaomi_miot.bean_nt01_ed29_thermostat (<class 'custom_components.xiaomi_miot.climate.MiotClimateEntity'>) implements HVACMode(s): auto, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-06-27 17:31:33.578 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 643: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-27 18:10:50.088 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/utils.py, line 15: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil: (offender: /config/custom_components/xiaomi_miot/core/utils.py, line 15: with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
data = await registration.info_callback(hass)
File "/config/custom_components/xiaomi_miot/system_health.py", line 34, in system_health_info
'component_version': get_manifest('version', 'unknown'),
File "/config/custom_components/xiaomi_miot/core/utils.py", line 15, in get_manifest
with open(f'{os.path.dirname(__file__)}/../manifest.json') as fil:

**Comment by al-one** [comment]
Please provide more detailed information and include some screenshots.

**Comment by vanscer** [comment]
1.当在空调控制界面
![image](https://github.com/user-attachments/assets/ecb541fc-99f2-47da-a474-ea1103bc34f2)
，调节温度的时候（包括+合-），它实际的操作是打开地暖并调节地暖的温度，模式选项正常，风速选项正常。 
2.switch
![image](https://github.com/user-attachments/assets/1cb80d91-1bae-4114-bb35-56c4d95cddaa)
，实际上它是地暖的开关，当空调在制冷的时候，这个开关显示为开启，手动关闭这个开关，则会关闭空调制冷和关闭地暖。
3.thermostat
![image](https://github.com/user-attachments/assets/0f5720af-deec-427f-8885-b89616fc5a11)
当模式选择自动，实际上会打开空调，风速选项正常。当模式选择关闭，实际上是关闭空调。
4.没有新风相关实体。
![image](https://github.com/user-attachments/assets/10ad8f9f-02cd-4b37-91aa-5ebd54020bb9)
5.温湿度显示正常

**Comment by 596311341** [comment]
我的也是这样
