### ISSUE TITLE
No module named 'imp'

### ISSUE THREAD

**Issue by mjxoicq** [al-one/hass-xiaomi-miot#1737]
### Device model / 设备型号

小米整个集成不可用

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2024.6.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新HA版本后，MIOT集成不可用，禁用再启用也不行。看日志说是集成不支持2024.5之后的HA core。

### Entity attributes / 实体属性

没办法筛选出属性最多的实体

### Home Assistant Logs / 系统日志

1：
```
日志记录器: homeassistant.config_entries
来源: config_entries.py:2757
首次出现: 20:06:44 (1 次总计出现)
上次记录: 20:06:44
Error occurred loading flow for integration xiaomi_miot: No module named 'imp'
```

2：
```
日志记录器: homeassistant.const
来源: helpers/deprecation.py:197
首次出现: 19:57:58 (272 次总计出现)
上次记录: 20:06:44

DATA_RATE_KIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.KIBIBYTES_PER_SECOND instead, please report it to the author of the 'xiaomi_miot' custom integration
DATA_RATE_MEBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEBIBYTES_PER_SECOND instead, please report it to the author of the 'xiaomi_miot' custom integration
DATA_RATE_GIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.GIBIBYTES_PER_SECOND instead, please report it to the author of the 'xiaomi_miot' custom integration
ENTITY_CATEGORY_CONFIG was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.CONFIG instead, please report it to the author of the 'xiaomi_miot' custom integration
ENTITY_CATEGORY_DIAGNOSTIC was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.DIAGNOSTIC instead, please report it to the author of the 'xiaomi_miot' custom integration
```

3:
```
日志记录器: homeassistant.setup
来源: setup.py:320
首次出现: 19:57:58 (1 次总计出现)
上次记录: 19:57:58

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by al-one** [comment]
Fixed in v0.7.17
