### ISSUE TITLE
HACS 更新 Xiaomi Miot Auto master 版本失敗

### ISSUE THREAD

**Issue by parkghost** [al-one/hass-xiaomi-miot#1751]
選擇 master 後，按 Download，Download 按鈕轉不停

![image](https://github.com/al-one/hass-xiaomi-miot/assets/306544/efac02f6-a9ae-4f79-a4ea-d1b5a35dadcf)

HACS 日誌顯示 https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip 下載失敗

```
2024-07-07 20:41:17.342 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Getting repository information
2024-07-07 20:41:18.162 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Running checks against master
2024-07-07 20:41:18.913 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Getting documentation for version=v0.7.18,filename=README.md
2024-07-07 20:41:18.913 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/al-one/hass-xiaomi-miot/v0.7.18/README.md
2024-07-07 20:41:19.591 INFO (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Running pre installation steps
2024-07-07 20:41:19.592 INFO (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Pre installation steps completed
2024-07-07 20:41:19.592 INFO (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Running installation steps
2024-07-07 20:41:19.592 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Getting repository information
2024-07-07 20:41:20.517 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Running checks against master
2024-07-07 20:41:21.399 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Getting documentation for version=v0.7.18,filename=README.md
2024-07-07 20:41:21.400 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/al-one/hass-xiaomi-miot/v0.7.18/README.md
2024-07-07 20:41:22.103 DEBUG (SyncWorker_40) [custom_components.hacs] Backup for /config/custom_components/xiaomi_miot, created in /tmp/hacs_backup/xiaomi_miot
2024-07-07 20:41:22.106 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Local path is set to /config/custom_components/xiaomi_miot
2024-07-07 20:41:22.106 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Remote path is set to custom_components/xiaomi_miot
2024-07-07 20:41:22.106 DEBUG (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Version to install: master
2024-07-07 20:41:22.106 DEBUG (MainThread) [custom_components.hacs] Trying to download https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip
2024-07-07 20:41:22.452 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip
2024-07-07 20:41:22.458 ERROR (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Failed to download https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip
2024-07-07 20:41:22.589 DEBUG (SyncWorker_21) [custom_components.hacs] Restored /config/custom_components/xiaomi_miot, from backup /tmp/hacs_backup/xiaomi_miot
2024-07-07 20:41:22.597 DEBUG (SyncWorker_35) [custom_components.hacs] Backup dir /tmp/hacs_backup/ cleared
2024-07-07 20:41:22.599 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139796369354624] Error handling message: Unknown error (unknown_error) Brandon from 192.168.10.51 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Comment by al-one** [comment]
网络问题。可以使用以下命令更新:
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=latest bash -
```

**Comment by parkghost** [comment]
指令可以正常安裝 master
![image](https://github.com/al-one/hass-xiaomi-miot/assets/306544/7cd5aac9-3380-47cd-856e-512c69d244c1)

我比較了一指令與 UI 的下載路徑

指令:
- master
https://ghrp.hacs.vip/al-one/hass-xiaomi-miot/archive/master.zip ok 
- v0.7.18
https://ghrp.hacs.vip/al-one/hass-xiaomi-miot/archive/v0.7.18.zip ok

UI:
- master
https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip fail (404 not found)
- v0.7.18
https://github.com/al-one/hass-xiaomi-miot/releases/download/v0.7.18/xiaomi_miot.zip ok

**Comment by parkghost** [comment]
關聯的 [hacs issue](https://github.com/hacs/integration/issues/3513)，依描述是 hac 功能有變更

看起來要透過 HACS UI 下載 master version 需將 zip_release 選項移除，不然應該要將 hide_default_branch=true 避免錯誤操作路徑
