### ISSUE TITLE
Problem support Air Dog X7SM

### ISSUE THREAD

**Issue by GreshnikYa** [al-one/hass-xiaomi-miot#1805]
### Device model / 设备型号

Air Dog X7SM (airdog.airpurifier.x7sm)

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.08.0

### Integrated mode / 集成方式

Token

### The problem / 问题详情

No suport Air Dog X7SM 

### Entity attributes / 实体属性

```yaml
No
```

### Home Assistant Logs / 系统日志

Error while setting up xiaomi_miio_airpurifier platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1197, in async_setup_platform
    device = XiaomiAirDog(name, air_purifier, model, unique_id, retries)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 3063, in __init__
    AirDogOperationMode("Manual"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'Manual' is not a valid OperationMode

**Comment by al-one** [comment]
`xiaomi_miio_airpurifier` is not this component.
