### ISSUE TITLE
更新HA版本后xiaomi-miot不可用

### ISSUE THREAD

**Issue by ranqingwen** [al-one/hass-xiaomi-miot#1840]
### Device model / 设备型号

xiaomi-miot

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新HA版本后，MIOT集成不可用，禁用，删除重新安装xiaomi-miot都不可用

### Entity attributes / 实体属性

```yaml
xiaomi-miot下的所有实体
```

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.config_entries
来源: config_entries.py:604
首次出现: 20:31:53 (3 次总计出现)
上次记录: 20:42:33

Error setting up entry Xiaomi: 140883539 for xiaomi_miot
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/media_player.py", line 31, in <module>
    from homeassistant.components.homekit.const import EVENT_HOMEKIT_TV_REMOTE_KEY_PRESSED
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/homekit/__init__.py", line 84, in <module>
    from . import (  # noqa: F401
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/homekit/type_cameras.py", line 34, in <module>
    from .accessories import TYPES, HomeAccessory, HomeDriver
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/homekit/accessories.py", line 10, in <module>
    from pyhap.accessory_driver import AccessoryDriver
  File "/usr/local/lib/python3.12/site-packages/pyhap/accessory_driver.py", line 53, in <module>
    from pyhap.hap_server import HAPServer
  File "/usr/local/lib/python3.12/site-packages/pyhap/hap_server.py", line 11, in <module>
    from .hap_protocol import HAPServerProtocol
  File "/usr/local/lib/python3.12/site-packages/pyhap/hap_protocol.py", line 16, in <module>
    from .hap_crypto import HAPCrypto
  File "/usr/local/lib/python3.12/site-packages/pyhap/hap_crypto.py", line 8, in <module>
    from chacha20poly1305_reuseable import ChaCha20Poly1305Reusable as ChaCha20Poly1305
  File "src/chacha20poly1305_reuseable/__init__.py", line 21, in init chacha20poly1305_reuseable
AttributeError: module 'lib' has no attribute 'EVP_CIPHER_CTX_ctrl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 279, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, SUPPORTED_DOMAINS)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2085, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 16 more times]
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1284, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.xiaomi_miot.media_player
![屏幕截图 2024-08-29 204926](https://github.com/user-attachments/assets/dc4b1ca5-1b39-4bc8-b420-c629fbe3957d)

**Comment by ranqingwen** [comment]
已解决，使用“docker exec -it home-assistants pip3 install --upgrade homeassistant”更新得HASS，因使用的系统为OPENWRT，python环境不全，python3-pip组件无法安装导致。使用docker传统更新容器方法更新后已成功
