### ISSUE TITLE
Detected blocking call to open with args ('/etc/timezone',) inside the event loop by custom integration 'xiaomi_miot' 

### ISSUE THREAD

**Issue by nikmedoed** [al-one/hass-xiaomi-miot#1885]
HA in docker, version 2024.10.1.

```log

2024-10-07 17:17:37.340 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/etc/timezone',) inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 43: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 62: with open(tzpath) as tzfile:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 225, in async_setup
    mic = MiotCloud(
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 43, in __init__
    super().__init__(username, password)

2024-10-07 17:17:37.384 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/etc/sysconfig/clock', 'rt') inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 43: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 97: with open(tzpath, "rt") as tzfile:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 225, in async_setup
    mic = MiotCloud(
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 43, in __init__
    super().__init__(username, password)

2024-10-07 17:17:37.426 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/etc/localtime', 'rb') inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 43: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 189: with open(tzpath, "rb") as tzfile:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 225, in async_setup
    mic = MiotCloud(
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 43, in __init__
    super().__init__(username, password)

```

At the same time, the integrations are working. Roborock s5 is controlled via HA.

**Comment by al-one** [comment]
Fixed in v0.7.21
