### ISSUE TITLE
v0.4.4 new version bug：lumi.motion.bmgl01 not available

### ISSUE THREAD

**Issue by PedroNeer** [al-one/hass-xiaomi-miot#189]
[lumi.motion.bmgl01](https://home.miot-spec.com/s/lumi.motion.bmgl01)
制造商：lumi
固件：1.1.1_0010

```
2021-09-18 11:19:37 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform xiaomi_miot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 137, in state
    iso = self.is_on
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 132, in is_on
    return val <= dur
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

**Comment by al-one** [comment]
Please try to update to the master branch.

**Comment by PedroNeer** [comment]
> Please try to update to the master branch.

It works.  But sth still wrong in log. So confused.

`2021-09-19 12:39:19 ERROR (MainThread) [pyhap.characteristic] SecuritySystemCurrentState: value=0 is an invalid value.
2021-09-19 12:39:19 ERROR (MainThread) [pyhap.characteristic] SecuritySystemTargetState: value=0 is an invalid value.
2021-09-19 12:39:25 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.lumi_bmgl01_ea2c_motion_sensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 171, in async_update
    await self.async_update_ble_data()
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 199, in async_update_ble_data
    val = int.from_bytes(bytes.fromhex(vls[0] or ''), 'little')
ValueError: non-hexadecimal number found in fromhex() arg at position 1
2021-09-19 12:39:55 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.lumi_bmgl01_ea2c_motion_sensor fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 171, in async_update
    await self.async_update_ble_data()
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 199, in async_update_ble_data
    val = int.from_bytes(bytes.fromhex(vls[0] or ''), 'little')
ValueError: non-hexadecimal number found in fromhex() arg at position 1`

**Comment by al-one** [comment]
Please update to the master branch and try again.

**Comment by PedroNeer** [comment]
> Please update to the master branch and try again.

Everything is ok now. Thx
