### ISSUE TITLE
新版HA安装Miot Auto插件后无法登录

### ISSUE THREAD

**Issue by Timerunning** [al-one/hass-xiaomi-miot#1893]
错误日志：
```
2024-10-17 14:25:19.824 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/etc/localtime', 'rb') inside the event loop by custom integration 'xiaomi_miot' at custom_components/xiaomi_miot/core/xiaomi_cloud.py, line 43: super().__init__(username, password) (offender: /usr/local/lib/python3.12/site-packages/tzlocal/unix.py, line 189: with open(tzpath, "rb") as tzfile:), please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
gFor developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
#Traceback (most recent call last):
:  File "<frozen runpy>", line 198, in _run_module_as_main
/  File "<frozen runpy>", line 88, in _run_code
Q  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
M  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
)    exit_code = runner.run(runtime_conf)
J  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
G    return loop.run_until_complete(setup_and_run_hass(runtime_config))
[  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
T  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
S  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
G  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
3    self._context.run(self._callback, *self._args)
g  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
*    resp = await request_handler(request)
Z  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
"    return await handler(request)
_  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
"    return await handler(request)
y  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
"    return await handler(request)
m  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
"    return await handler(request)
y  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
"    return await handler(request)
a  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
"    return await handler(request)
d  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
"    return await handler(request)
i  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
&    response = await handler(request)
R  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
:    result = await handler(request, **request.match_info)
d  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
6    return await func(self, request, *args, **kwargs)
e  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
0    return await super().post(request, flow_id)
e  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
>    return await method(view, request, data, *args, **kwargs)
\  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
A    result = await self._flow_mgr.async_configure(flow_id, data)
_  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
>    result = await self._async_configure(flow_id, user_input)
`  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
,    result = await self._async_handle_step(
b  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
C    result: _FlowResultT = await getattr(flow, method)(user_input)
]  File "/config/custom_components/xiaomi_miot/config_flow.py", line 308, in async_step_cloud
R    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
a  File "/config/custom_components/xiaomi_miot/config_flow.py", line 118, in check_xiaomi_account
D    mic = await MiotCloud.from_token(hass, user_input, login=False)
]  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 599, in from_token
    mic = MiotCloud(
Z  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 43, in __init__
)    super().__init__(username, password)
```

**Comment by Timerunning** [comment]
找到问题所在了。将时区设置为上海就ok了
