### ISSUE TITLE
Xiaomi Miio Airconditioning Companion MCN02 - Error on Device Update

### ISSUE THREAD

**Issue by johnjoemorgan** [al-one/hass-xiaomi-miot#193]
The device is configured using Cloud.  Device is working OK with no problems.
Seeing this error in logs.  

========

Logger: homeassistant.components.climate
Source: custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py:323
Integration: Climate (documentation, issues)
First occurred: 13:14:46 (2 occurrences)
Last logged: 13:14:46

xiaomi_miio_airconditioningcompanionmcn02: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 323, in async_update
    if state.target_temperature <= self.max_temp else None,
  File "/usr/local/lib/python3.9/site-packages/miio/airconditioningcompanionMCN.py", line 79, in target_temperature
    return self.data[2]
IndexError: list index out of range

**Comment by al-one** [comment]
Domain `xiaomi_miio_airconditioningcompanionmcn02` is not this component.
https://github.com/search?q=xiaomi_airconditioningcompanionMCN02

**Comment by johnjoemorgan** [comment]
Apologies!
