### ISSUE TITLE
Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by dwd1** [al-one/hass-xiaomi-miot#1988]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/xiaomi_miot/sensor.py:322
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: November 27, 2024 at 23:40:48 (14151 occurrences)
Last logged: 21:37:37

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1046, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 544, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 322, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

**Comment by al-one** [comment]
Fixed in v0.7.25
