### ISSUE TITLE
xiaomi_miot 已载入，但HA的UI中找不到此集成，在configuration.yaml添加设备也不成功

### ISSUE THREAD

**Issue by zhtengw** [al-one/hass-xiaomi-miot#2]
您好，我有一个米家智能晾衣机，型号是hyd.airer.znlyj1，想测试一下能否接入，但遇到一些问题，想咨询一下原因。
首选，xiaomi_miot放置位置应该没问题，路径如下：
```
┌ Tuesday [2021.01.12 - 15:49:39] (/etc/homeassistant/custom_components)
# ll
total 24K
drwxr-xr-x 12 homeassistant 4.0K Jan 11 21:28 hacs
drwxr-xr-x  4 homeassistant 4.0K Jan 12 15:15 miio_yeelink
drwxr-xr-x  5 homeassistant 4.0K Jan 11 21:43 xiaomi_gateway3
drwxr-xr-x  3 homeassistant 4.0K Dec 24 18:38 xiaomi_miio_airconditioningcompanion
drwxr-xr-x  3 homeassistant 4.0K Jan 11 21:43 xiaomi_miio_airconditioningcompanionmcn02
drwxr-xr-x  4 homeassistant 4.0K Jan 12 15:38 xiaomi_miot
┌ Tuesday [2021.01.12 - 15:49:40] (/etc/homeassistant/custom_components)
# ll xiaomi_miot
total 80K
-rw-r--r-- 1 homeassistant 7.2K Jan  8 23:35 climate.py
-rw-r--r-- 1 homeassistant 3.2K Jan  8 23:35 config_flow.py
-rw-r--r-- 1 homeassistant  15K Jan  8 23:35 cover.py
-rw-r--r-- 1 homeassistant 1.4K Jan  8 23:35 fan.py
-rw-r--r-- 1 homeassistant  15K Jan  8 23:35 __init__.py
-rw-r--r-- 1 homeassistant 1.7K Jan  8 23:35 light.py
-rw-r--r-- 1 homeassistant  377 Jan  8 23:35 manifest.json
drwxr-xr-x 2 homeassistant 4.0K Jan 12 15:38 __pycache__
-rw-r--r-- 1 homeassistant 4.3K Jan  8 23:35 sensor.py
-rw-r--r-- 1 homeassistant  604 Jan  8 23:35 services.yaml
-rw-r--r-- 1 homeassistant 1.1K Jan  8 23:35 switch.py
drwxr-xr-x 2 homeassistant 4.0K Jan  8 23:35 translations
```

启动HA时的相关日志为，表明此集成也正常载入了：
```log
2021-01-12 15:42:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-12 15:42:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for miio_yeelink which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-12 15:42:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-12 15:42:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-12 15:42:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airconditioningcompanion which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-12 15:42:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airconditioningcompanionmcn02 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

但在Web UI中却搜索不到此集成：
![no miot](https://user-images.githubusercontent.com/3148769/104285342-75309580-54ee-11eb-828e-4561756e28d2.png)

另外，我在configuration.yaml中直接配置为light和cover也不成功，配置如下：
```
light:
  - platform: xiaomi_miot
    name: 阳台灯
    host: 192.168.2.55
    token: af0f2be5d00d70f85a2753ee837d1475
#    model: hyd.airer.znlyj1

# 晾衣机
cover:
  - platform: xiaomi_miot
    name: 晾衣机
    host: 192.168.2.55
    token: af0f2be5d00d70f85a2753ee837d1475
#    model: hyd.airer.znlyj1
```
light这项配置在日志里报错如下：
```
2021-01-12 15:42:25 ERROR (MainThread) [homeassistant.config] Invalid config for [light.xiaomi_miot]: [name] is an invalid option for [light.xiaomi_miot]. Check: light.xiaomi_miot->name. (See /etc/homeassistant/configuration.yaml, line 109). Please check the docs at https://github.com/al-one/hass-xiaomi-miot
```
而cover的配置没有相关日志提示，HA中也没有出现相关实体。

**Comment by al-one** [comment]
请问是docke部署的HA吗？
[hassbian论坛](https://bbs.hassbian.com/forum.php?mod=redirect&goto=findpost&ptid=11276&pid=348577)也有人遇到过，原因不明，你可以尝试下在命令行重启HA

**Comment by zhtengw** [comment]
不是docker，自建Linux服务器直接安装的homeassistant，Web UI重启，命令行重启homeassistant服务都试过了，日志提示一直都是这样的。

**Comment by al-one** [comment]
请下载最新版[master](https://github.com/al-one/hass-xiaomi-miot/tree/master)分支重试下，另外有灯的晾衣机无需单独配置light，只需配置cover，通过yaml集成时model也是必须的。
当前版本的插件不确定能否支持您这款晾衣架，如果你确定miio props中包含`led`和`motor`，则支持。
```yaml
cover:
  - platform: xiaomi_miot
    name: 晾衣机
    host: 192.168.2.55
    token: af0f2be5d00d70f85a2753ee837d1475
    model: hyd.airer.znlyj1
```

**Comment by zhtengw** [comment]
更新了最新版，WebUI的集成里仍然看不到；配置文件里我把model加上了，日志里同样没有任何相关提示，也没有生成相关实体。

补充一下，我使用[xiaomi_miot_raw](https://github.com/ha0y/xiaomi_miot_raw/)这个集成是可以添加使用这个晾衣机的，但它不支持灯，所以想试试看您的这个集成。

**Comment by al-one** [comment]
事实上目前xiaomi_miot这个集成是使用旧的miio协议实现的，且晾衣机类设备应该仅支持mrbond.airer.m1pro。
至于WebUI集成中收不到xiaomi_miot，我觉得应该是其他位置问题造成的。目前我本人已经通过这个插件集成了好几个设备都正常运行。

![图片](https://user-images.githubusercontent.com/4549099/104322026-58f91c80-551f-11eb-9d7f-4076d0595458.png)

**Comment by zhtengw** [comment]
你好，我升级homeassistant到2021.1.1，xiaomi_miot在集成中能显示了，我的这个晾衣机可以在集成中添加，但仍然没有生成任何实体，应该是不支持了。感谢您的跟进。

**Comment by al-one** [comment]
我刚添加了对`hyd.airer.znlyj1`的支持，你可以尝试下分支[add-airer](https://github.com/al-one/hass-xiaomi-miot/tree/add-airer)

**Comment by zhtengw** [comment]
> 
> 
> 我刚添加了对`hyd.airer.znlyj1`的支持，你可以尝试下分支[add-airer](https://github.com/al-one/hass-xiaomi-miot/tree/add-airer)

更新试了下，日志报错误：
```
2021-01-13 22:46:49 ERROR (MainThread) [homeassistant.components.cover] xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/etc/homeassistant/custom_components/xiaomi_miot/cover.py", line 246, in async_update
    self._position = 100 - round(attrs.get('current_position', 0), -1) * 50
TypeError: type NoneType doesn't define __round__ method
```

**Comment by al-one** [comment]
下载最新的提交再试下

**Comment by zhtengw** [comment]
看来还有几个位置得改：
```
2021-01-13 23:20:50 ERROR (MainThread) [homeassistant.components.cover] xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 359, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/etc/homeassistant/custom_components/xiaomi_miot/cover.py", line 247, in async_update
    self._is_opening = int(attrs.get('status', 0)) == 1
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by zhtengw** [comment]
我从邦先生的类中把这几个缺少的属性复制过去了，具体修改代码如下：
```
--- cover.py.old        2021-01-13 23:44:50.172849081 +0800
+++ cover.py    2021-01-13 23:37:30.721860489 +0800
@@ -234,18 +234,20 @@
         _LOGGER.info('Initializing with host %s (token %s...)', host, token[:5])

         self._device = MiotDevice(self.mapping, host, token)
+        self._add_entities = config.get('add_entities')
         super().__init__(name, self._device)
         self._device_class = DEVICE_CLASS_DAMPER
         self._supported_features = SUPPORT_OPEN | SUPPORT_CLOSE | SUPPORT_STOP
         self._state_attrs.update({'entity_class': self.__class__.__name__})
+        self._subs = {}

     async def async_update(self):
         await super().async_update()
         if self._available:
             attrs = self._state_attrs
             self._position = 100 - round(attrs.get('current_position') or 0, -1) * 50
-            self._is_opening = int(attrs.get('status', 0)) == 1
-            self._is_closing = int(attrs.get('status', 0)) == 2
+            self._is_opening = int(attrs.get('status') or 0) == 1
+            self._is_closing = int(attrs.get('status') or 0) == 2
             self._closed = self._position <= 0
             self._state_attrs.update({
                 'stopped': bool(not self._is_opening and not self._is_closing),
```

出现了两个实体：灯和升降帘，但灯的开关无效，升级帘可以降下来，可以暂停，不能升上去。

**Comment by zhtengw** [comment]
您好，新的提交可以正常升降和开关灯了，但灯的开关状态获取不正常，任何时候灯的状态在HA都显示为关，要在HA里关灯的话，需要打开的时候趁灯的状态还没自动变回“关”的时候点关才行。

**Comment by al-one** [comment]
强烈推荐使用[auto-miot](https://github.com/al-one/hass-xiaomi-miot/tree/auto-miot)分支，该分支通过miot-spec.org提供的数据自动适配设备。

**Comment by al-one** [comment]
请问有尝试最新版本吗？是否正常接入？
