### ISSUE TITLE
欧普浴霸一直报错，型号：opple.bhf_light.acmoto

### ISSUE THREAD

**Issue by hanley520** [al-one/hass-xiaomi-miot#200]
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/__init__.py:1790
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 2021年9月29日 23:15:24 (589 occurrences)
Last logged: 09:01:26

Update for climate.opple_acmoto_1403_ptc_bath_heater fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/climate.py", line 189, in async_update
    self._subs[des] = ClimateModeSubEntity(self, self._prop_mode, {
  File "/config/custom_components/xiaomi_miot/climate.py", line 610, in __init__
    super().__init__(parent, miot_property, option)
  File "/config/custom_components/xiaomi_miot/fan.py", line 313, in __init__
    super().__init__(parent, miot_property.full_name, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1823, in __init__
    super().__init__(parent, attr, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1790, in __init__
    self._miot_service = miot_property.service
AttributeError: 'str' object has no attribute 'service'

**Comment by supersks** [comment]
This yeelight heater also has this issue

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/__init__.py:1790
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 01:26:48 (1 occurrences)
Last logged: 01:26:48

Update for climate.yeelight_smart_bath_heater_ptc_bath_heater fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/climate.py", line 189, in async_update
    self._subs[des] = ClimateModeSubEntity(self, self._prop_mode, {
  File "/config/custom_components/xiaomi_miot/climate.py", line 610, in __init__
    super().__init__(parent, miot_property, option)
  File "/config/custom_components/xiaomi_miot/fan.py", line 313, in __init__
    super().__init__(parent, miot_property.full_name, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1823, in __init__
    super().__init__(parent, attr, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1790, in __init__
    self._miot_service = miot_property.service
AttributeError: 'str' object has no attribute 'service'

**Comment by al-one** [comment]
Please upgrade to master and try again.
