### ISSUE TITLE
v0.4.5 AttributeError: 'str' object has no attribute 'service'

### ISSUE THREAD

**Issue by PedroNeer** [al-one/hass-xiaomi-miot#205]
lumi.motion.bmgl01
制造商：lumi
固件：1.1.1_0010
sensor.lumi_bmgl01_ea2c_illumination失效，和升级0.4.5时间吻合
![image](https://user-images.githubusercontent.com/13635493/136246697-89adc502-dfad-4bdf-bb87-cc3217ce928f.png)

相关日志：

```
File "/config/custom_components/xiaomi_miot/__init__.py", line 1496, in _update_sub_entities
    self._subs[fnm] = MiotModesSubEntity(self, p, option=opt)
  File "/config/custom_components/xiaomi_miot/fan.py", line 313, in __init__
    super().__init__(parent, miot_property.full_name, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1823, in __init__
    super().__init__(parent, attr, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1790, in __init__
    self._miot_service = miot_property.service
AttributeError: 'str' object has no attribute 'service'
```

```
2021-10-07 00:32:57 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.mmgg_s1_fec0_pet_drinking_fountain fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/switch.py", line 134, in async_update
    self._update_sub_entities(
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1496, in _update_sub_entities
    self._subs[fnm] = MiotModesSubEntity(self, p, option=opt)
  File "/config/custom_components/xiaomi_miot/fan.py", line 313, in __init__
    super().__init__(parent, miot_property.full_name, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1823, in __init__
    super().__init__(parent, attr, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1790, in __init__
    self._miot_service = miot_property.service
AttributeError: 'str' object has no attribute 'service'
2021-10-07 00:33:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.mmgg_s1_fec0_pet_drinking_fountain fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/switch.py", line 134, in async_update
    self._update_sub_entities(
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1496, in _update_sub_entities
    self._subs[fnm] = MiotModesSubEntity(self, p, option=opt)
  File "/config/custom_components/xiaomi_miot/fan.py", line 313, in __init__
    super().__init__(parent, miot_property.full_name, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1823, in __init__
    super().__init__(parent, attr, option)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1790, in __init__
    self._miot_service = miot_property.service
AttributeError: 'str' object has no attribute 'service'
```

**Comment by al-one** [comment]
请升级到master后重试。

**Comment by PedroNeer** [comment]
![image](https://user-images.githubusercontent.com/13635493/136693808-d2ed16e9-49b7-40d1-994f-ab7498d443f3.png)
![image](https://user-images.githubusercontent.com/13635493/136693844-f7d0fe97-7267-4fc6-8eb5-c19cef154609.png)

日志里没有错误了，但传感器少了光照的属性

**Comment by al-one** [comment]
该型号[人体传感器](https://home.miot-spec.com/s/lumi.motion.bmgl01)的[miot-spec](https://home.miot-spec.com/spec/lumi.motion.bmgl01)规格中的`illumination`属性并非真实的照度值，此属性仅有两个值：`1: weak` `2: strong`，只能表明当前光线强弱，你可以从实体属性`illumination_level`得到它的值。

**Comment by PedroNeer** [comment]
> 该型号[人体传感器](https://home.miot-spec.com/s/lumi.motion.bmgl01)的[miot-spec](https://home.miot-spec.com/spec/lumi.motion.bmgl01)规格中的`illumination`属性并非真实的照度值，此属性仅有两个值：`1: weak` `2: strong`，只能表明当前光线强弱，你可以从实体属性`illumination_level`得到它的值。

我再回滚下代码试下，https://github.com/al-one/hass-xiaomi-miot/issues/189 这个问题fix之后的版本是可以正常使用的，记得数据曲线是有值，测试完给你同步下

**Comment by al-one** [comment]
是的。这两个值代码光线强弱，因此后面我把照度实体移除了。可以从人体传感器实体的`illumination_level`属性获取。

**Comment by PedroNeer** [comment]
恩，好的谢谢
