### ISSUE TITLE
bj352.waterpuri.s100cm Unavailable

### ISSUE THREAD

**Issue by IDhiding** [al-one/hass-xiaomi-miot#2100]
### Device model / 设备型号

bj352.waterpuri.s100cm

### Component version / 插件版本

master branch

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Unavailable

### Entity attributes / 实体属性

```yaml
No entity
```

### Home Assistant Logs / 系统日志

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 221:09:24 (1 occurrences)
Last logged: 22:09:24

Error setting up entry waterpuri for xiaomi_miot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 246, in async_setup_entry
    device = await entry.new_device(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entry.py", line 96, in new_device
    await device.async_init()
  File "/config/custom_components/xiaomi_miot/core/device.py", line 181, in async_init
    spec = await self.get_spec()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 315, in get_spec
    self.init_converters()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 440, in init_converters
    self.add_converter(conv)
    ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 342, in add_converter
    self.log.info('Converter for %s already exists. Ignored.', c.full_name)
                                                               ^
NameError: name 'c' is not defined

**Comment by IDhiding** [comment]
solved, thanks.
