### ISSUE TITLE
升级到1.0.6，所有实体不可用。集成那里显示设置失败。

### ISSUE THREAD

**Issue by jarod360** [al-one/hass-xiaomi-miot#2114]
Error setting up entry Xiaomi: 950275585 for xiaomi_miot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 242, in async_setup_entry
    await async_setup_xiaomi_cloud(hass, config_entry)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 277, in async_setup_xiaomi_cloud
    cloud = await entry.get_cloud(check=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entry.py", line 115, in get_cloud
    await self.cloud.async_check_auth(notify=True)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 167, in async_check_auth
    rdt = await self.async_request_api(api, dat, method='POST') or {}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 221, in async_request_api
    rsp = await self.async_request_rc4_api(api, params, method, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 784, in async_request_rc4_api
    response = await session.post(url, data=params, timeout=timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 512, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by Azaelyus** [comment]
I am getting the same errors, the whole integration has stopped working. Maybe something related to new Python version?

**Comment by YobiFan** [comment]
我也收到相同的错误，整个集成已停止工作。也许和我的心情无关？

**Comment by YonghuiKing** [comment]
Same issue, already roll back to 1.01,the most stable version

**Comment by XieBrok** [comment]
重装一下试试？

**Comment by coolzhi** [comment]
一样，是不是小米官方出了插件不让第三方用的原因？

但是官方插件好像现在只能认证一个HA设备，多家庭的就不方便了

**Comment by yukunyi** [comment]
全部不可用了

**Comment by al-one** [comment]
检查网络和环境

**Comment by jarod360** [comment]
> 检查网络和环境

退回1.0.5都正常，试了几次更新到1.0.6就出错。

**Comment by al-one** [comment]
那就检查是都还有其他报错日志，与`RuntimeError: Session is closed`无关

**Comment by jarod360** [comment]
> 那就检查是都还有其他报错日志，与`RuntimeError: Session is closed`无关。 或者直接更新 master 分支:
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

更新master分支后正常。

**Comment by cjhqyz** [comment]
我这边也是同样的问题，我这边还要一条日志如下：

```
日志详细信息( WARNING )
日志: zeroconf
来源: /usr/local/lib/python3.12/site-packages/zeroconf/_logger.py:86
首次发生: 19:16:25 (1 全部发生)
上次记录: 19:16:25

Error with socket 14 (('::', 5353, 0, 0))): [Errno 13] Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1265, in sendto
    self._sock.sendto(data, addr)
PermissionError: [Errno 13] Permission denied
```

**Comment by YonghuiKing** [comment]
我的情况1.0.6就是有大量的实体都无法使用，期间每个版本都试过了，原本我用的是1.0还是1.1的来着，这时候我家的设备都是正常的，只是有些实体的英文名很长很长，不太直观。更新到1.0.5后，米家温湿度计不自动更新，但是如果点击诊断中的“按下”，是可以手动更新的。我试着回退到了1.0.4和1.0.3发现这时候就已经存在这个问题了，最后我还是用了1.0.5，自动更新的问题没有解决，但是我在智能场景种添加了自动化，每30秒点击一次诊断中的“按下”操作来实现自动更新。

根本不是什么网络问题，我反复尝试了多个版本，什么清空设备重新添加什么的都尝试过了，没有出现不同的结果，就是插件的问题

**Comment by al-one** [comment]
如果实体都不可用并且提示`集成不再提供此实体`，请在集成配置中重新筛选设备。

**Comment by sjwz042** [comment]
> > 检查网络和环境
> 
> 退回1.0.5都正常，试了几次更新到1.0.6就出错。

大哥能不能教我怎么退回1.0.5
