### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_max_properties'

### ISSUE THREAD

**Issue by dwd1** [al-one/hass-xiaomi-miot#2115]
Logger: custom_components.xiaomi_miot.core.device.miaomiaoce.sensor_ht.o2
Source: helpers/update_coordinator.py:379
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 01:09:08 (5 occurrences)
Last logged: 01:10:10
Unexpected error fetching a1:b2:c3:d4:e5:f6-5541c7b5a06c39b267a5efae6628e003 -miot_status data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 493, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 803, in update_miot_status
    max_properties = self.local.get_max_properties(mapping)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_max_properties'

**Comment by Matt7C2** [comment]
same problem

**Comment by al-one** [comment]
Select the local mode, but it includes unsupported devices.
