### ISSUE TITLE
Mi Air Purifier 3C zhimi.airpurifier.mb4 - error custom_service.favorite_speed

### ISSUE THREAD

**Issue by zawias** [al-one/hass-xiaomi-miot#212]
Hi. Probably after the upgrade to HA 2021.10.4 there is no fan control in [zhimi.airpurifier.mb4](https://home.miot-spec.com/spec/zhimi.airpurifier.mb4).

```yaml
service: xiaomi_miot.set_property
data:
  entity_id: climate.xiaomi_mc5_374e
  field: custom_service.favorite_speed
  value: 1500
```

```
2021-10-15 10:39:34 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140498994488656] set_property() got an unexpected keyword argument 'field'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/xiaomi_miot/__init__.py", line 365, in async_service_handler
await getattr(dvc, fun)(**params)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1313, in async_set_property
return await self.hass.async_add_executor_job(partial(self.set_property, *args, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: set_property() got an unexpected keyword argument 'field'
2021-10-15 10:41:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140499003331056] set_property() got an unexpected keyword argument 'field'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/config/custom_components/xiaomi_miot/__init__.py", line 365, in async_service_handler
await getattr(dvc, fun)(**params)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1313, in async_set_property
return await self.hass.async_add_executor_job(partial(self.set_property, *args, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: set_property() got an unexpected keyword argument 'field'
```
Before it worked. Anyone can help?

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/a69c8e0e44400b9aa0f94f1003d3c6f3de4996fd .
It is recommended to use the [`xiaomi_miot.set_miot_property`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.set_miot_property) service, this `field name` may be changed in future versions.
```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: climate.zhimi_mb4_entity_id
  siid: 9 # custom_service
  piid: 3 # favorite_speed
  value: 1500
```
Check the `siid`/`piid` in the website: https://home.miot-spec.com/spec/zhimi.airpurifier.mb4
