### ISSUE TITLE
Failed to load xiaomi miot auto

### ISSUE THREAD

**Issue by EvanLuo42** [al-one/hass-xiaomi-miot#214]
This is the log
```
Oct 17 13:38:13 hassbian hass[766]: 2021-10-17 13:38:13 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.7.3 is deprecated an
Oct 17 13:38:39 hassbian hass[766]: 2021-10-17 13:38:39 ERROR (MainThread) [aiohttp.server] Error handling request
Oct 17 13:38:39 hassbian hass[766]: Traceback (most recent call last):
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Oct 17 13:38:39 hassbian hass[766]:     resp = await self._request_handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 499, in _handle
Oct 17 13:38:39 hassbian hass[766]:     resp = await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 118, in impl
Oct 17 13:38:39 hassbian hass[766]:     return await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_f
Oct 17 13:38:39 hassbian hass[766]:     return await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_co
Oct 17 13:38:39 hassbian hass[766]:     return await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
Oct 17 13:38:39 hassbian hass[766]:     return await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
Oct 17 13:38:39 hassbian hass[766]:     return await handler(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
Oct 17 13:38:39 hassbian hass[766]:     result = await result
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 136, in post
Oct 17 13:38:39 hassbian hass[766]:     return await super().post(request)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
Oct 17 13:38:39 hassbian hass[766]:     result = await method(view, request, *args, **kwargs)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 73, in post
Oct 17 13:38:39 hassbian hass[766]:     "show_advanced_options": data["show_advanced_options"],
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 119, in async_init
Oct 17 13:38:39 hassbian hass[766]:     flow = await self.async_create_flow(handler, context=context, data=data)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 535, in async_create_flow
Oct 17 13:38:39 hassbian hass[766]:     integration.get_platform("config_flow")
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 424, in get_platform
Oct 17 13:38:39 hassbian hass[766]:     cache[full_name] = self._import_platform(platform_name)
Oct 17 13:38:39 hassbian hass[766]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 429, in _import_platform
Oct 17 13:38:39 hassbian hass[766]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
Oct 17 13:38:39 hassbian hass[766]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Oct 17 13:38:39 hassbian hass[766]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap_external>", line 860, in get_code
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
Oct 17 13:38:39 hassbian hass[766]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Oct 17 13:38:39 hassbian hass[766]:   File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/__init__.py", line 189
Oct 17 13:38:39 hassbian hass[766]:     if lang := config.get('language'):
Oct 17 13:38:39 hassbian hass[766]:              ^
Oct 17 13:38:39 hassbian hass[766]: SyntaxError: invalid syntax
```

**Comment by al-one** [comment]
This component requires python version 3.8 or higher, please upgrade your python.
