### ISSUE TITLE
Aiohttp session error

### ISSUE THREAD

**Issue by someone1989** [al-one/hass-xiaomi-miot#2210]
Hi, after update to latest version and hard restart Home assistant server (I first did soft restart, not with whole Home assistant server and addons and It was still working after the integration update) I am getting the following error below from logs, but only for European server integration (I also have Chinese servers and they are working as should). I can click configure and login to cloud with my credentials and all devices show there as added on European server in Home assistant but when clicking finish I just get the instant error below. 
Also, in Xiaomi Home app everything on European server is working as should.

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 00:57:29 (2 occurrences)
Last logged: 00:58:15

Error setting up entry Xiaomi: xxxxxxxxxxx for xiaomi_miot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 242, in async_setup_entry
    await async_setup_xiaomi_cloud(hass, config_entry)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 277, in async_setup_xiaomi_cloud
    cloud = await entry.get_cloud(check=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entry.py", line 115, in get_cloud
    await self.cloud.async_check_auth(notify=True)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 167, in async_check_auth
    rdt = await self.async_request_api(api, dat, method='POST') or {}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 221, in async_request_api
    rsp = await self.async_request_rc4_api(api, params, method, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 784, in async_request_rc4_api
    response = await session.post(url, data=params, timeout=timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 512, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards

**Comment by someone1989** [comment]
I've updated today to today's latest version and now everything works! Thanks!

**Comment by someone1989** [comment]
Update:
Cameras on European server are not working, switches and functions that earlier worked for Cameras are now unavailable
All other devices work as expected

**Comment by someone1989** [comment]
Latest update today to v1.0.8:
Everything works!

Thx
