### ISSUE TITLE
update 1.07 Unable to add device

### ISSUE THREAD

**Issue by AbianTang** [al-one/hass-xiaomi-miot#2228]
### Device model / 设备型号

all

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2024.7.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

update 1.07 Unable to add device

### Entity attributes / 实体属性

```yaml
无
```

### Home Assistant Logs / 系统日志

Got MiioException while fetching the state: Unable to discover the device 192.168.31.77, mapping: {'battery.charging_state': {'siid': 3, 'piid': 2}, 'vacuum.status': {'siid': 2, 'piid': 2}, 'vacuum.cleaning_area': {'siid': 2, 'piid': 6}, 'vacuum.cleaning_time': {'siid': 2, 'piid': 7}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to discover the device 192.168.31.77, mapping: {'vacuum.sweep_mop_type': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 5}, 'vacuum.clean_times': {'siid': 2, 'piid': 8}, 'vacuum.mode': {'siid': 2, 'piid': 9}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to discover the device 192.168.31.77, mapping: {'custom.updata_difference': {'siid': 20, 'piid': 3}, 'dust_bag.dust_bag_life_level': {'siid': 19, 'piid': 1}, 'dust_bag.dust_bag_left_time': {'siid': 19, 'piid': 2}, 'detergent_left_level-18-1': {'siid': 18, 'piid': 1}, 'detergent_self_delivery-18-2': {'siid': 18, 'piid': 2}, 'detergent_self_delivery_level-18-3': {'siid': 18, 'piid': 3}, 'voice_management.target_voice': {'siid': 15, 'piid': 1}, 'voice_management.cur_voice': {'siid': 15, 'piid': 2}, 'download_status-15-3': {'siid': 15, 'piid': 3}, 'download_progress-15-4': {'siid': 15, 'piid': 4}, 'filter.filter_life_level': {'siid': 14, 'piid': 1}, 'filter.filter_left_time': {'siid': 14, 'piid': 2}, 'brush_life_level-13-1': {'siid': 13, 'piid': 1}, 'brush_left_time-13-2': {'siid': 13, 'piid': 2}, 'brush_cleaner.brush_life_level': {'siid': 12, 'piid': 1}, 'brush_cleaner.brush_left_time': {'siid': 12, 'piid': 2}, 'no_disturb': {'siid': 11, 'piid': 1}, 'no_disturb.enable_time_period': {'siid': 11, 'piid': 2}, 'no_disturb.current_no_disturb': {'siid': 11, 'piid': 3},

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.dmaker.fan.p8
来源: custom_components/xiaomi_miot/core/device.py:868
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年12月28日 23:37:11 (1 次总计出现)
上次记录: 2024年12月28日 23:37:11

Got MiioException while fetching the state: Unable to discover the device 172.16.149.115, mapping: {'indicator_light.on': {'siid': 5, 'piid': 1}, 'fan.on': {'siid': 2, 'piid': 1}, 'fan.fan_level': {'siid': 2, 'piid': 2}, 'fan.mode': {'siid': 2, 'piid': 7}}, max_properties: 4/4

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/__init__.py", line 242, in async_setup_entry
    await async_setup_xiaomi_cloud(hass, config_entry)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 288, in async_setup_xiaomi_cloud
    device = await entry.new_device(d)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/hass_entry.py", line 99, in new_device
    await device.async_init()
  File "/config/custom_components/xiaomi_miot/core/device.py", line 207, in async_init
    await self.init_coordinators()
  File "/config/custom_components/xiaomi_miot/core/device.py", line 500, in init_coordinators
    await coo.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 848, in update_miot_status
    res = await self.local.async_get_properties_for_mapping(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 1346, in async_get_properties_for_mapping
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.device.dmaker.airpurifier.f20
来源: custom_components/xiaomi_miot/core/device.py:868
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年12月28日 23:37:01 (4 次总计出现)
上次记录: 2024年12月28日 23:37:26

Got MiioException while fetching the state: Unable to discover the device 172.17.2.120, mapping: {'screen.on': {'siid': 7, 'piid': 1}, 'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'air_purifier.fan_level': {'siid': 2, 'piid': 7}}, max_properties: 4/4
Got MiioException while fetching the state: Unable to discover the device 172.17.2.120, mapping: {'dm_sevice.favorite_speed': {'siid': 9, 'piid': 1}, 'dm_sevice.moto_control': {'siid': 9, 'piid': 2}, 'dm_sevice.moto_feedback': {'siid': 9, 'piid': 3}, 'dm_sevice.filter_type': {'siid': 9, 'piid': 4}, 'dm_sevice.event_pm': {'siid': 9, 'piid': 5}, 'dm_sevice.moto_current': {'siid': 9, 'piid': 6}, 'dm_sevice.filter_event': {'siid': 9, 'piid': 7}, 'dm_sevice.moto_hz': {'siid': 9, 'piid': 9}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'screen.brightness': {'siid': 7, 'piid': 2}, 'alarm': {'siid': 6, 'piid': 1}, 'alarm.volume': {'siid': 6, 'piid': 2}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_left_time': {'siid': 4, 'piid': 2}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_used_flow': {'siid': 4, 'piid': 4}, 'filter.filter_left_flow': {'siid': 4, 'piid': 5}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.pm10_density': {'siid': 3, 'piid': 5}, 'environment.temperature': {'siid': 3, 'piid': 7}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.door_state': {'siid': 2, 'piid': 6}}, max_properties: 8/23

**Comment by al-one** [comment]
Restart and try again.

**Comment by AbianTang** [comment]
重启无效，降级使用。
