### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by benceje** [al-one/hass-xiaomi-miot#225]
Hi there! Thank you for this integration. After install I have this error in server log:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:161
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:55:02 (1 occurrences)
Last logged: 8:55:02

[1254407040] The system cannot restart because the configuration is not valid: Component error: xiaomi_miot - No module named 'croniter'
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 728, in admin_handler
    await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/homeassistant/__init__.py", line 161, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: xiaomi_miot - No module named 'croniter'

My environment: Synology nas ds115j - Home Assistant Core 2121.8.8-14

**Comment by al-one** [comment]
This component does not import the python module named `croniter`. I found the integration `utility_meter` imported it. Have you used it in your HA? In addition, you can try to execute the shell command to install the `croniter` module:
```shell
pip install croniter
```
