### ISSUE TITLE
Long status update and change setting temperature or humidifity

### ISSUE THREAD

**Issue by Redram49RUS** [al-one/hass-xiaomi-miot#2256]
### Device model / 设备型号

Zhimi.heater.mc2a and shimi.humidifier.ca4

### Component version / 插件版本

1.07

### HA core version / HA版本

2024.12.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![Screenshot_20241230-222720](https://github.com/user-attachments/assets/71244b75-b000-4dba-a6c7-866b46bf95ea)

When I try on/off device or change settings temperature or humidifity status change has take long time or I need tap the button twice to have effect.

### Entity attributes / 实体属性

```yaml
.
```

### Home Assistant Logs / 系统日志

.

**Comment by Redram49RUS** [comment]
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.xiaomi_miot.core.device.zhimi.heater.mc2a
Источник: custom_components/xiaomi_miot/core/device.py:868
интеграция: Xiaomi Miot Auto (документация, проблемы)
Первое сообщение: 19:46:42 (3 сообщений)
Последнее сообщение: 19:46:58

Got MiioException while fetching the state: Unable to discover the device 192.168.1.71, mapping: {'indicator_light.on': {'siid': 7, 'piid': 1}, 'heater.on': {'siid': 2, 'piid': 1}, 'heater.target_temperature': {'siid': 2, 'piid': 5}}, max_properties: 3/3
Got MiioException while fetching the state: Unable to discover the device 192.168.1.71, mapping: {'private_service.hw_enable': {'siid': 8, 'piid': 8}, 'private_service.use_time': {'siid': 8, 'piid': 9}, 'private_service.country_code': {'siid': 8, 'piid': 10}, 'alarm': {'siid': 6, 'piid': 1}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'countdown.countdown_time': {'siid': 3, 'piid': 1}, 'heater.fault': {'siid': 2, 'piid': 2}}, max_properties: 8/8

**Comment by Redram49RUS** [comment]
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.xiaomi_miot.core.device.roborock.vacuum.a27
Источник: helpers/update_coordinator.py:379
интеграция: Xiaomi Miot Auto (документация, проблемы)
Первое сообщение: 23:06:27 (1 сообщений)
Последнее сообщение: 23:06:27

Unexpected error fetching b0:4a:39:5b:a4:c9-add867fe9cbe045af4c0c71542836c6a-chunk_2 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 827, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 120, in get_miot_props
    if dic := self.get_miio_props(device):
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 78, in get_miio_props
    vls = device.send(c['method'], pms)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str

**Comment by gieljnssns** [comment]
I'm also seeing this error for roborock.vacuum.a15
```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.device.roborock.vacuum.a15
Source: helpers/update_coordinator.py:379
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: January 1, 2025 at 19:58:50 (1 occurrences)
Last logged: January 1, 2025 at 19:58:50

Unexpected error fetching b0:4a:39:40:3b:25-chunk_1 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 513, in _update
    result = await self.update_miot_status(mapping)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/device.py", line 827, in update_miot_status
    results = await self.miio2miot.async_get_miot_props(self.local, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 112, in async_get_miot_props
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        partial(self.get_miot_props, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 120, in get_miot_props
    if dic := self.get_miio_props(device):
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 78, in get_miio_props
    vls = device.send(c['method'], pms)
  File "/usr/local/lib/python3.13/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
                ~~~~~~~^^^^^^
TypeError: byte indices must be integers or slices, not str
```

**Comment by Redram49RUS** [comment]
After update 1.0.12 problem home for heater mc2a, but humidifier ca4 still have it.

**Comment by al-one** [comment]
> File "/usr/local/lib/python3.13/site-packages/miio/miioprotocol.py", line 202, in send
self.__id = payload["id"]
TypeError: byte indices must be integers or slices, not str


Error comes from upstream dependency [python-miio](https://github.com/rytilahti/python-miio)

**Comment by Redram49RUS** [comment]
Problem has gone in 1.0.14
