### ISSUE TITLE
chuangmi.camera.ip029a 摄像头无图像

### ISSUE THREAD

**Issue by MapleEve** [al-one/hass-xiaomi-miot#228]
这个新的2K 版摄像头没有 rtsp 链接，但是 log 中会报如下错误：

`2021-11-05 20:19:37 WARNING (stream_worker) [libav.https] HTTP error 404 Not Found
2021-11-05 20:19:37 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream https://cn02.livestreaming.io.mi.com/hlstranscoder/GCBkMDEwNmXXXXXXhYTczZThjNWY5YWIyYjJlYxgKX191bnXXXXXXfXwA_HXXXXX64/playlist.m3u8
2021-11-05 20:20:33 WARNING (SyncWorker_8) [custom_components.xiaomi_miot.camera] 客厅监控 Camera Control: stream address status invalid: 403 (Forbidden)
2021-11-05 20:20:49 WARNING (stream_worker) [libav.https] HTTP error 403 Forbidden
2021-11-05 20:20:49 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream https://cn02.livestreaming.io.mi.com/hlstranscoder/GCBkMDEwNmZXXXXXXXhYTczZThjNWY5YWIyYjJlYxgKX191bnXXXXXwA_H2XXXXXX/playlist.m3u8
2021-11-05 20:22:09 WARNING (stream_worker) [libav.https] HTTP error 403 Forbidden`

以及下列错误
```

2021-11-05 20:32:42 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)
2021-11-05 20:32:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 72, in <module>
    from .gateway import ConnectXiaomiGateway
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/gateway.py", line 6, in <module>
    from micloud.micloudexception import MiCloudAccessDenied
ImportError: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 716, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2021-11-05 20:32:42 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)
2021-11-05 20:32:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 72, in <module>
    from .gateway import ConnectXiaomiGateway
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/gateway.py", line 6, in <module>
    from micloud.micloudexception import MiCloudAccessDenied
ImportError: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 716, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
```

![image](https://user-images.githubusercontent.com/1845053/140510983-557559dc-d2f1-4878-8d53-7af86457e8b7.png)

**Comment by MapleEve** [comment]
```
access_token: xxxxxxxxxxxxxxxxxxxxxxx
brand: chuangmi
motion_detection: true
frontend_stream_type: hls
stream_type: hls
model: chuangmi.camera.029a02
lan_ip: 192.168.0.37
mac_address: 60:XX:XX:XX:69:XX
firmware_version: 4.1.6_0329
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-029a02:1
miot_action_result:
  did: '45050XXXX'
  miid: 0
  siid: 7
  aiid: 1
  code: -704220025
  exe_time: 0
  net_cost: 0
  ot_cost: 0
  otlocalts: 0
  oa_cost: 0
  _oa_rpc_cost: 0
stream_http_status: 403
stream_http_reason: Forbidden
stream_address: ''
expire_at: '2021-11-05 20:41:23.905436'
miot_error: null
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 0
camera_control.motion_tracking: true
camera_control.time_watermark: true
stream_status-8-9: 1
stream_status-7-9: 1
motion_detection.alarm_interval: 5
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: '00:00:00'
motion_detection_end_time-5-5: '23:59:59'
memory_card_management.status: 4
storage_total_space-4-2: 15532032
storage_free_space-4-3: 14467072
storage_used_space-4-4: 1064960
indicator_light.on: false
state_updater: cloud
motion_video_time: '2021-11-05 20:35:23'
motion_video_type: ObjectMotion:PeopleMotion
sub_entities:
  - camera_control.on
  - motion_event
  - motion_detection-5.motion_detection-1
  - indicator_light-3
miot_action_error: '-704220025 The number of action parameters does not match'
motion_video_latest:
  startDuration: 0
  cut: false
  offset: 0
  isCloud: false
  isRead: false
  videoStoreId: >-
    GKACcR6sl0eOyPDCkD8oetJIPVcCBA1mDoMi1Vc3kkQVhmVdG21XuNoyRbiRcO0vF-fW4arKeSO47iE4JmaltZksBtJgj2SEWyJF-bU2Ek9OazpUb-sugaRyyOTCHE1Nn_izlzsP5GALsfBGYr9EvpFJeLV6tPVG9_zFL6cUpZxJUoLXj9WOV7YKEWZg-XXXXXXXXXXXXXXX-LPVu2g_Tj_KW1PgQS1iPkP48m4liovyVrgNl9z7EmNz4Hs8EbdtXxWRoq_tAkSBFsE6UKyDYNGFn7vq2WjtVCADrRNj9eGftW22YpyLHZ4PXf9JszevmcLG8QvDHt450dkd-XXXXXXXXXXXXXXXXXX-ZYzHRcYFBWiKWCvIFhJQ2CY6C-XBWJtq8KQAA
  eventType: ObjectMotion:PeopleMotion
  expireTime: 1636720529982
  isAlarm: true
  imgStoreId: >-
    GKACWumFzE-_Er0ZUDouM1jEEPXBs-TeVS5iOlizQ-1QBhABlskyX8iisfbDdVGUoh_j9Mt5OaQt0rsRPq-oeSpxKodq0XcKbXfHH8d0U-XXXXXXXXXXXXXX-Staes-lkDPHRXRkDYhogAG_Vio9DP3ImtpuLen-XXXXXXXXXXXXX
  fileId: '65825993479692160'
  extraInfo: '{"ver":"1.0.0","alarmStart":true,"eventType":"ObjectMotion"}'
friendly_name: 客厅相机图像
entity_picture: >-
  /api/camera_proxy/camera.chuangmi_029a02_e569_camera_control?token=6XXXXXXXXXXXXXXXXXXXXXXXX86b2d98d223c4dd4d034e
supported_features: 3

```

**Comment by al-one** [comment]
> [libav.https] HTTP error 403 Forbidden

插件获取到了该摄像机的直播流m3u8地址，但是该地址无法访问，因此无法播放摄像头视频。你可以在米家APP开始该摄像头的`看家助手`并产生回放记录，即可在HA中该设备下的另一个camera实体中看到截图。


> ImportError: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception'

将插件升级到v0.4.9即可解决。

**Comment by MapleEve** [comment]
Thx

**Comment by MapleEve** [comment]
摄像头实时串流问题是小米那边的问题还是现在核心不支持？
我设置看家模式，在 apple home 上可以查看图像，但是在 HA 中查看不到图像

**Comment by al-one** [comment]
实时直播流`403 Forbidden`应该是小米的问题，给了一个不可访问的流地址。
至于回放视频的m3u8地址是可以正常访问的，但是由于HA core使用FFmpeg解码视频切片为mjpeg的时候报错了，导致无法播放，在HomeKit可以播放可能是由于使用FFmpeg解码为不同的输出格式。你可以参考 #166 使用ffmpeg命令行调试视频流地址。
