### ISSUE TITLE
micloud 0.3 package requirement conflicts with home assistant

### ISSUE THREAD

**Issue by Wh1terat** [al-one/hass-xiaomi-miot#229]
Home Assistant now includes xiaomi_miio component as standard, this has a package requirement of micloud 0.4 since https://github.com/home-assistant/core/commit/e34aed743cf1a1448166a990bfdeefd654f0a452

xiaomi_miot requires 0.3 exactly (not >=)
https://github.com/al-one/hass-xiaomi-miot/blob/68815169735fd5db4435a6ce02dfd919bd1e2524/custom_components/xiaomi_miot/manifest.json#L17

Because xiaomi_miio component is now built in it will fail to initialise the component even if the component is not used spamming as 0.3 does not contain the MiCloudAccessDenied exception class.

```
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 16:10:40 (12 occurrences)
Last logged: 16:21:58

Error occurred loading configuration flow for integration xiaomi_miio: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)
```

```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 72, in <module>
    from .gateway import ConnectXiaomiGateway
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/gateway.py", line 6, in <module>
    from micloud.micloudexception import MiCloudAccessDenied
ImportError: cannot import name 'MiCloudAccessDenied' from 'micloud.micloudexception' (/usr/local/lib/python3.9/site-packages/micloud/micloudexception.py)
```

**Comment by al-one** [comment]
Thanks! It is fixed in the latest commit: https://github.com/al-one/hass-xiaomi-miot/commit/427417a284b90ca2b065aa2ca7cc40f0834a680b
