### ISSUE TITLE
小米账号登陆错误

### ISSUE THREAD

**Issue by hosinosora** [al-one/hass-xiaomi-miot#230]
此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:32
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 22:54:13 (1 occurrences)
Last logged: 22:54:13

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 244, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 109, in check_xiaomi_account
    mic = await MiotCloud.from_token(hass, user_input)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 255, in from_token
    mic = MiotCloud(
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 32, in __init__
    super().__init__(username, password)
  File "/usr/local/lib/python3.9/site-packages/micloud/micloud.py", line 38, in __init__
    timezone = datetime.datetime.now(tzlocal.get_localzone()).strftime('%z')
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'

**Comment by hosinosora** [comment]
时区我改了还是这样提示，这种怎么处理？

**Comment by hosinosora** [comment]
找到问题了，docker里面时区不对
