### ISSUE TITLE
小米电视xiaomi.tv.rmh1切换APP时出错

### ISSUE THREAD

**Issue by MageDelfador** [al-one/hass-xiaomi-miot#233]
实体select.xiaomi_rmh1_eee1_app_current_2  选择任意app后出错，电视不启动对应app

2021-11-07_ 21:58:42 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140272637582640] start_app() got an unexpected keyword argument 'attr'
Traceback (most recent call last):
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/core.py", line 1495, in async_call
task.result()
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 667, in entity_service_call
future.result() # pop exception if have
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 863, in async_request_call
await coro
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 704, in _handle_entity_call
await result
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/components/select/__init__.py", line 54, in async_select_option
await entity.async_select_option(option)
File "/home/xxxx/.local/lib/python3.8/site-packages/homeassistant/components/select/__init__.py", line 113, in async_select_option
await self.hass.async_add_executor_job(self.select_option, option)
File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/xxxx/.homeassistant/custom_components/xiaomi_miot/select.py", line 148, in select_option
if ret := self._select_option(option, **kws):
TypeError: start_app() got an unexpected keyword argument 'attr'

**Comment by al-one** [comment]
最新提交：https://github.com/al-one/hass-xiaomi-miot/commit/e183c5187796a3008089dc1f77e1eae91c1b0084 已修复。
