### ISSUE TITLE
小米养生壶集成后有三个实体

### ISSUE THREAD

**Issue by goxofy** [al-one/hass-xiaomi-miot#246]
![image](https://user-images.githubusercontent.com/1695416/141881799-dfddcb88-aa26-4a60-bd3e-ccd86b8ed002.png)

第二个switch代表什么意思呢，点了也没用，会提示一个报错

![image](https://user-images.githubusercontent.com/1695416/141881852-3655b95f-8b7f-4194-8349-bd536d5499d6.png)

**Comment by al-one** [comment]
这个开关实体是用来启动和暂停养生壶的，但是启动需要先选择烹饪模式属性，也就是上方的`Cook Mode`。

**Comment by goxofy** [comment]
@al-one 但是我上面选了 Boil Water之后，点下面这个按钮还是提示这个错误

**Comment by al-one** [comment]
请到 [`配置` > `日志`](https://my.home-assistant.io/redirect/logs) 页面，复制完整的错误日志。

**Comment by goxofy** [comment]
@al-one 如下~

```
2021-11-17 07:06:44 WARNING (SyncWorker_31) [custom_components.xiaomi_miot.sensor] 烧水壶 Health Pot Status: Call miot action [{'piid': 3, 'value': 4}] failed: {'code': -5000, 'message': 'Invalid json'}
2021-11-17 07:06:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139883661628080] pop from empty list
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 915, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1962, in turn_on
return self.call_parent('turn_on', **kwargs)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1888, in call_parent
ret = getattr(self._parent, f)(*args, **kwargs)
File "/config/custom_components/xiaomi_miot/sensor.py", line 300, in turn_on
return self.turn_action(True)
File "/config/custom_components/xiaomi_miot/sensor.py", line 313, in turn_action
ret = self.call_action(act, pms)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1455, in call_action
return self.miot_action(siid, aiid, pms, did, **kwargs)
File "/config/custom_components/xiaomi_miot/__init__.py", line 1478, in miot_action
pms = action.in_params(params or [])
File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 715, in in_params
val = params.pop(0)
IndexError: pop from empty list
```

**Comment by al-one** [comment]
这个开关实体需要通过自定义配置一个默认的烹饪模式，[米家智能多功能养生壶](https://home.miot-spec.com/s/chunmi.health_pot.a1)的`cook-mode`定义如下：
```
0 - Tea
1 - Fruit Tea
2 - Tremella
3 - Soup
4 - Boil Water
5 - Keep Warm
6 - Power
7 - Custom
```
你可以[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)：
```yaml
# customize.yaml
sensor.chunmi_a1_entity_id:
  start_cook_params: 3 # Soup
```

另外，`select.chunmi_a1_xxxx_cook_mode`实体在选择模式后应该会直接启动养生壶，你可以尝试下。

**Comment by goxofy** [comment]
你好，我添加了自定义属性之后开关确实没有报错了，但是还是不起作用，点击开关之后等待三秒左右又会变成关闭状态。不知道是不是我自定义属性添加的有问题。

另外上面select.chunmi_a1_xxxx_cook_mode选择后也是不起作用不知道什么情况

**Comment by al-one** [comment]
请检查下操作后有没有实体相关报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by goxofy** [comment]
```
2021-11-19 04:45:33 WARNING (SyncWorker_17) [custom_components.xiaomi_miot.sensor] 烧水壶 Health Pot Status: Call miot action [{'piid': 3, 'value': '4'}] failed: {'code': -5000, 'message': 'Invalid json'}
```

**Comment by al-one** [comment]
这是v0.4.9版本的一个bug，已在 https://github.com/al-one/hass-xiaomi-miot/commit/bf9d9c86b2da2d2c56a009cf443de40d8a2ab2fa 中修复了，你可以更新到master分支或等待下个版本发布。

**Comment by goxofy** [comment]
ok我自己改一下试一下谢谢

**Comment by al-one** [comment]
这个自定义属性需要加在养生壶的sensor实体上，加在switch实体上没有效果。

**Comment by goxofy** [comment]
@al-one 我明白，我就是加在sensor上的，如下：

<img width="450" alt="截屏2021-11-18 下午10 41 38" src="https://user-images.githubusercontent.com/1695416/142436615-4c6a0171-5df5-4f63-bf03-d83ad1f859f5.png">

**Comment by al-one** [comment]
你可以去[`开发者工具` > `状态`](https://my.home-assistant.io/redirect/developer_states)看下实体属性中有没有添加成功。如果没有，请检查下`​customize.yaml​`文件有没有被包含在`homeassistant:`配置项下面。

**Comment by goxofy** [comment]
您好，我查了一下应该是添加成功了的

<img width="520" alt="截屏2021-11-18 下午10 59 34" src="https://user-images.githubusercontent.com/1695416/142440014-e1195ad2-173b-42d9-9c88-089bc93c4c90.png">

最后一项是我加的，因为customize里还有其他的自定义属性，所以应该是没有问题的

**Comment by al-one** [comment]
如果你是通过`customize.yaml`文件添加的自定义属性，可以尝试下：
```yaml
# customize.yaml
sensor.chunmi_a1_entity_id:
  start_cook_params: [4]
```

**Comment by goxofy** [comment]
谢谢改成[4]后就可以了~
