### ISSUE TITLE
输入账号和密码后无法加载，报错Unknown Error Occured

### ISSUE THREAD

**Issue by holyfun** [al-one/hass-xiaomi-miot#260]
输入账号和密码后无法加载，报错Unknown Error Occured，log如下
xiaomi_miot_raw可以正常加载。请指教，谢谢！
=========================================
此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:32
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 2021年11月24日 03:47:34 (8 occurrences)
Last logged: 09:47:16

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 244, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 109, in check_xiaomi_account
    mic = await MiotCloud.from_token(hass, user_input)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 260, in from_token
    mic = MiotCloud(
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 32, in __init__
    super().__init__(username, password)
  File "/usr/local/lib/python3.9/site-packages/micloud/micloud.py", line 38, in __init__
    timezone = datetime.datetime.now(tzlocal.get_localzone()).strftime('%z')
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 161, in _get_localzone
    tzenv = utils._tz_from_env()
  File "/usr/local/lib/python3.9/site-packages/tzlocal/utils.py", line 122, in _tz_from_env
    raise ZoneInfoNotFoundError(
tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/230#issuecomment-962473702

建议检查看你docker启动配置中是否包含`-e TZ=Asia/Shanghai`，并推荐参照[HA官方的安装文档](https://www.home-assistant.io/installation/linux#install-home-assistant-container)及官方的容器镜像。

**Comment by holyfun** [comment]
确实是docker漏掉了TZ参数，感谢指点！

**Comment by chaoqunxie** [comment]
树莓派B3直接安装的homeassistant系统镜像 怎么看加了这个时区参数

**Comment by chaoqunxie** [comment]
登录小米账号报错这个
Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:296
Integration: xiaomi_miot (documentation, issues)
First occurred: 2021年10月13日 13:12:24 (1 occurrences)
Last logged: 2021年10月13日 13:12:24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sts.api.io.mi.com', port=443): Max retries exceeded with url: /sts?d=zuhhhq&ticket=0&pwd=1&p_ts=1641713146000&fid=0&p_lm=1&auth=wJ5bwqeS2EezLkwioejfjdpYWCH2SgOx24YEyDo68EVPUy19ufl%2B6T3I%2FQ9u6RWzT4AteKBKXEvCQSNIq%2F%2F0hPW58ReF3S53cNsWo7cxo5bbkBGwRWyv9isH86mHwe2%2BWfW%2F7BywkMJoNpY8moP3d3iv7ph1wSkrwYta4CI48Eg%3D&m=1&tsl=0&nonce=G2pKGiDZ6HQBoYJd&_ssign=Y2bKfr5BGMohdDPg2WZ2CDrkRr0%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

**Comment by chaoqunxie** [comment]
解决了，还是时间的问题，homassistant系统 运行homeassistant服务是用的docker 把宿主机的时间设置正确 再把容器和宿主机时间同步
