### ISSUE TITLE
Service "remote.learn_command" does not work 

### ISSUE THREAD

**Issue by ReWiG** [al-one/hass-xiaomi-miot#276]
I connected the "chuangmi.ir.v2" device to my HomeAssistant using the "MIOT" integration.
I want to teach him a few commands, for this I try to use the "remote.learn_command" service but it doesn't work and keeps giving an "Unknown error" error. 
In this case, the following error is recorded in the log: 

> ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1746101584] Error handling message: Unknown error
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 1243, in async_run
await asyncio.shield(run.async_run())
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 353, in async_run
await self._async_step(log_exceptions=False)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
task.result()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 667, in entity_service_call
future.result() # pop exception if have
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 863, in async_request_call
await coro
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 704, in _handle_entity_call
await result
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/remote/__init__.py", line 202, in async_learn_command
await self.hass.async_add_executor_job(ft.partial(self.learn_command, **kwargs))
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/remote.py", line 163, in learn_command
raise NotImplementedError()
NotImplementedError

**Comment by al-one** [comment]
Added in https://github.com/al-one/hass-xiaomi-miot/commit/c3bd723f30e643029413861356f0d1726500ebd6

```yaml
service: remote.learn_command
data:
  entity_id: remote.chuangmi_v2_a0d5
  device: 666 # For store ir command, 1 - 1000000
```

> https://github.com/rytilahti/python-miio/blob/master/miio/chuangmi_ir.py#L38-L50

**Comment by al-one** [comment]
Does it work ?

**Comment by ReWiG** [comment]
> Does it work ?

No. The error, of course, is gone and does not appear in the log anymore, but no action is taken when the service is called. I am trying to teach the remote a command, but I am not getting it in any way. Maybe I don’t understand how to use it?

**Comment by al-one** [comment]
Add in v0.7.21
