### ISSUE TITLE
zhimi.heater.nb1 does not reflect hvac mode when not off

### ISSUE THREAD

**Issue by FrancYescO** [al-one/hass-xiaomi-miot#281]
Issue is similar to https://github.com/al-one/hass-xiaomi-miot/issues/141

Here the full trace:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 470, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/climate.py", line 390, in set_hvac_mode
    return self.set_property(self._prop_mode, val)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1411, in set_property
    result = self.set_miot_property(siid, piid, value)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1465, in set_miot_property
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/xiaomi_miot/climate.py", line 331, in state
    sta = self.hvac_mode
  File "/config/custom_components/xiaomi_miot/climate.py", line 346, in hvac_mode
    acm = -1 if acm is None else int(acm or 0)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

When Off:
![image](https://user-images.githubusercontent.com/4574593/144727167-6a583b9f-c88d-4e90-86e8-887c2e093a14.png)

Tryng to put On (setting auto on operation mode) it works but shows an error and the current state is not readed:
![image](https://user-images.githubusercontent.com/4574593/144727199-beb25661-54c8-41d0-9f3d-bfe939a7447d.png)

If helps this is the interface on app (there are also few more settings):
![image](https://user-images.githubusercontent.com/4574593/144727253-dae29d45-4154-4f16-b45c-8fd767a50502.png)

**Comment by al-one** [comment]
`TypeError` has been fixed, and a switch and delayed shutdown entity have been added to the device. Please upgrade to the master branch and try again.

**Comment by FrancYescO** [comment]
TypeError fix confirmed, but the "Operation" select is still empty when heater is On (in both case of "costant temperature" or "keep heating").

do you have the possibility to add also the "Notification sound" and "recenter" switch?

**Comment by al-one** [comment]
> TypeError fix confirmed, but the "Operation" select is still empty when heater is On (in both case of "costant temperature" or "keep heating").

https://github.com/home-assistant/core/blob/bbaec2c48123564576c7a2b011cfcb0ad1aa61e5/homeassistant/components/climate/const.py#L25-L33
The "Operation" (`hvac mode`) can only be one of the following values:
```python
HVAC_MODES = [
    HVAC_MODE_OFF,
    HVAC_MODE_HEAT,
    HVAC_MODE_COOL,
    HVAC_MODE_HEAT_COOL,
    HVAC_MODE_AUTO,
    HVAC_MODE_DRY,
    HVAC_MODE_FAN_ONLY,
]
```
But the [miot-spec](https://home.miot-spec.com/spec/zhimi.heater.nb1) of your device is defined as:
```yaml
heat-level: # Operation (hvac mode)
  - 1: High
  - 2: Low

mode: # Fan mode
  - 0: Fan not swing
  - 1: Fan swing
```

----

> do you have the possibility to add also the "Notification sound" and "recenter" switch?

You can [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities):
```yaml
# customize.yaml
heater.zhimi_nb1_entity_id:
  switch_properties: heater.on,alarm,return_to_middle
```
