### ISSUE TITLE
在一开始登录账号的时候提示: Unknown error occurred.我觉得应该是服务器有点问题。

### ISSUE THREAD

**Issue by guokai10000** [al-one/hass-xiaomi-miot#302]
2021-12-13 13:10:12 ERROR (MainThread) [aiohttp.server] Error handling request

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

    resp = await request_handler(request)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle

    resp = await handler(request)

  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware

    return await handler(request)

  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle

    result = await result

  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post

    return await super().post(request, flow_id)

  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper

    result = await method(view, request, *args, **kwargs)

  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post

    result = await self._flow_mgr.async_configure(flow_id, data)

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure

    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step

    result: FlowResult = await getattr(flow, method)(user_input)

  File "/config/custom_components/xiaomi_miot/config_flow.py", line 247, in async_step_cloud

    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)

  File "/config/custom_components/xiaomi_miot/config_flow.py", line 109, in check_xiaomi_account

    mic = await MiotCloud.from_token(hass, user_input)

  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 273, in from_token

    mic = MiotCloud(

  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 32, in __init__

    super().__init__(username, password)

  File "/usr/local/lib/python3.9/site-packages/micloud/micloud.py", line 38, in __init__

    timezone = datetime.datetime.now(tzlocal.get_localzone()).strftime('%z')

  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone

    _cache_tz = _get_localzone()

  File "/usr/local/lib/python3.9/site-packages/tzlocal/unix.py", line 161, in _get_localzone

    tzenv = utils._tz_from_env()

  File "/usr/local/lib/python3.9/site-packages/tzlocal/utils.py", line 122, in _tz_from_env

    raise ZoneInfoNotFoundError(

tzlocal.utils.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like %s. \nPlease use a timezone in the form of Continent/City'

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/260#issuecomment-978886852

https://github.com/al-one/hass-xiaomi-miot/issues?q=is%3Aissue+ZoneInfoNotFoundError

**Comment by guokai10000** [comment]
<img width="1014" alt="截屏2021-12-13 下午9 53 53" src="https://user-images.githubusercontent.com/60421269/145824857-45bae305-df6b-48b8-a7e0-d1f1f6d357f2.png">

已经在时区里设置了Asia/Shanghai了…

**Comment by al-one** [comment]
请问该问题还存在吗？

**Comment by fox181x** [comment]
群晖虚拟机VMM安装的Home Assistant OS，登录小米账号出现Unknown error occurred，请教解决方法。

此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/miot_spec.py:240
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:29:54 (16 occurrences)
Last logged: 22:18:50

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2c2a0999a0>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='miot-spec.org', port=443): Max retries exceeded with url: /miot-spec-v2/instances?status=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2c2a0999a0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 262, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 123, in check_xiaomi_account
    await MiotSpec.async_get_model_type(hass, 'xiaomi.miot.auto', use_remote=True)
  File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 240, in async_get_model_type
    res = await hass.async_add_executor_job(requests.get, url)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='miot-spec.org', port=443): Max retries exceeded with url: /miot-spec-v2/instances?status=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2c2a0999a0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by al-one** [comment]
> Name does not resolve

@fox181x 看起来你的dns服务出了问题，可以尝试重启宿主机。

**Comment by fox181x** [comment]
> 重置了hassos的dns、重启了宿主机，又除了新的未知错误…
此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/miot_spec.py:240 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 23:46:15 (1 occurrences) 
Last logged: 23:46:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6ac9f6c730>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='miot-spec.org', port=443): Max retries exceeded with url: /miot-spec-v2/instances?status=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6ac9f6c730>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 262, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 123, in check_xiaomi_account
    await MiotSpec.async_get_model_type(hass, 'xiaomi.miot.auto', use_remote=True)
  File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 240, in async_get_model_type
    res = await hass.async_add_executor_job(requests.get, url)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='miot-spec.org', port=443): Max retries exceeded with url: /miot-spec-v2/instances?status=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6ac9f6c730>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
