### ISSUE TITLE
local devices not working after v0.4.8

### ISSUE THREAD

**Issue by heyjared** [al-one/hass-xiaomi-miot#304]
I had two devices that I had set to `miot_local: true` that were working in v0.4.7 but stopped working after upgrading to v0.4.8 and later
- kejia.airer.mzn
- 090615.curtain.jldj03

```
2021-12-14 14:58:49 DEBUG (MainThread) [custom_components.xiaomi_miot.cover] Blinds Curtain: Got new state: {'curtain.fault.error': '-704083036 Device operation timeout', 'curtain.motor_control.error': '-704030013 Property is not readable', 'curtain.status': 1, 'curtain.mode': 0, 'curtain.current_position': 0, 'curtain.target_position': 0, 'curtain.motor_reverse': 0, 'state_updater': 'cloud'}
2021-12-14 14:58:56 ERROR (MainThread) [custom_components.xiaomi_miot.cover] Blinds Curtain: Got MiioException while fetching the state: Unable to parse message payload, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.status': {'siid': 2, 'piid': 4}, 'curtain.mode': {'siid': 2, 'piid': 5}, 'curtain.current_position': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'curtain.motor_reverse': {'siid': 2, 'piid': 8}}, max_properties: 10
```

```
2021-12-14 14:59:00 ERROR (MainThread) [custom_components.xiaomi_miot.cover] MI Smart·Electric Airer Airer: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.on': {'siid': 2, 'piid': 3}, 'airer.current_position': {'siid': 2, 'piid': 7}, 'airer.dryer': {'siid': 2, 'piid': 8}, 'airer.uv': {'siid': 2, 'piid': 11}, 'airer-2.dryer': {'siid': 2, 'piid': 12}, 'airer.status': {'siid': 2, 'piid': 13}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 10

```

**Comment by luzik** [comment]
local connection problem here too

```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1094
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 12:05:33 (25 occurrences)
Last logged: 12:17:38

Henryk Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device 192.168.12.14, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 10}, 'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'map.clean_path': {'siid': 13, 'piid': 2}, 'map.restricted_zone': {'siid': 13, 'piid': 3}, 'map.auto_area': {'siid': 13, 'piid': 4}, 'map.map_memory': {'siid': 13, 'piid': 5}, 'map.map_name': {'siid': 13, 'piid': 6}, 'map.use_auto_area': {'siid': 13, 'piid': 7}, 'map.path_type': {'siid': 13, 'piid': 8}, 'custom.mop': {'siid': 8, 'piid': 1}, 'custom.work_station_freq': {'siid': 8, 'piid': 2}, 'custom.timing': {'siid': 8, 'piid': 6}, 'custom.clean_area': {'siid': 8, 'piid': 7}, 'custom.uid': {'siid': 8, 'piid': 8}, 'custom.auto_boost': {'siid': 8, 'piid': 9}, 'custom.forbid_mode': {'siid': 8, 'piid': 10}, 'custom.water_level': {'siid': 8, 'piid': 11}, 'custom.total_clean_time': {'siid': 8, 'piid': 13}, 'custom.total_clean_areas': {'siid': 8, 'piid': 14}, 'custom.clean_counts': {'siid': 8, 'piid': 18}, 'custom.clean_time': {'siid': 8, 'piid': 19}, 'custom.double_clean': {'siid': 8, 'piid': 20}, 'custom.edge_sweep': {'siid': 8, 'piid': 21}, 'custom.led_switch': {'siid': 8, 'piid': 22}, 'custom.lidar_collision': {'siid': 8, 'piid': 23}, 'custom.station_key': {'siid': 8, 'piid': 24}, 'custom.station_led': {'siid': 8, 'piid': 25}, 'custom.current_audio': {'siid': 8, 'piid': 26}, 'custom.progress': {'siid': 8, 'piid': 28}, 'custom.station_type': {'siid': 8, 'piid': 29}, 'custom.voice_conf': {'siid': 8, 'piid': 30}, 'brush_left_time-15-1': {'siid': 15, 'piid': 1}, 'brush_life_level-15-2': {'siid': 15, 'piid': 2}, 'brush_left_time-12-1': {'siid': 12, 'piid': 1}, 'brush_life_level-12-2': {'siid': 12, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 11, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 11, 'piid': 2}, 'filter.filter_life_level': {'siid': 10, 'piid': 1}, 'filter.filter_left_time': {'siid': 10, 'piid': 2}, 'speaker.volume': {'siid': 9, 'piid': 1}, 'speaker.mute': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/47
```

**Comment by al-one** [comment]
@heyjared You can try [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities):
```yaml
# customize.yaml
cover.090615_jldj03_entity_id:
  chunk_properties: 5
cover.kejia_mzn_entity_id:
  chunk_properties: 5
```

**Comment by al-one** [comment]
@luzik  You can try [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities):
```yaml
# customize.yaml
cover.your_vacuum_entity_id:
  exclude_miot_services: custom,map
```

**Comment by luzik** [comment]
@al-one 
just updated to latest version, added customization, now it looks like this:
```
  vacuum.vacuum_cleaner_robot_cleaner:
    miot_local: true         # Force to read and write data in LAN
    miot_cloud: false        # Enable miot cloud for entity (read, write, action)
    #miot_cloud_write: true  # (Optional) Enable miot cloud (only write)
    miot_cloud_action: true  # (Optional) Enable miot cloud (only action)
    exclude_miot_services: custom,map
```
and after restart got:

```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1164 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 12:14:45 (2 occurrences) 
Last logged: 12:15:20

Henryk Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device 192.168.124.14, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 10}}, max_properties: 8/5
Henryk Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device 192.168.124.14, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 10}, 'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'map.clean_path': {'siid': 13, 'piid': 2}, 'map.restricted_zone': {'siid': 13, 'piid': 3}, 'map.auto_area': {'siid': 13, 'piid': 4}, 'map.map_memory': {'siid': 13, 'piid': 5}, 'map.map_name': {'siid': 13, 'piid': 6}, 'map.use_auto_area': {'siid': 13, 'piid': 7}, 'map.path_type': {'siid': 13, 'piid': 8}, 'custom.mop': {'siid': 8, 'piid': 1}, 'custom.work_station_freq': {'siid': 8, 'piid': 2}, 'custom.timing': {'siid': 8, 'piid': 6}, 'custom.clean_area': {'siid': 8, 'piid': 7}, 'custom.uid': {'siid': 8, 'piid': 8}, 'custom.auto_boost': {'siid': 8, 'piid': 9}, 'custom.forbid_mode': {'siid': 8, 'piid': 10}, 'custom.water_level': {'siid': 8, 'piid': 11}, 'custom.total_clean_time': {'siid': 8, 'piid': 13}, 'custom.total_clean_areas': {'siid': 8, 'piid': 14}, 'custom.clean_counts': {'siid': 8, 'piid': 18}, 'custom.clean_time': {'siid': 8, 'piid': 19}, 'custom.double_clean': {'siid': 8, 'piid': 20}, 'custom.edge_sweep': {'siid': 8, 'piid': 21}, 'custom.led_switch': {'siid': 8, 'piid': 22}, 'custom.lidar_collision': {'siid': 8, 'piid': 23}, 'custom.station_key': {'siid': 8, 'piid': 24}, 'custom.station_led': {'siid': 8, 'piid': 25}, 'custom.current_audio': {'siid': 8, 'piid': 26}, 'custom.progress': {'siid': 8, 'piid': 28}, 'custom.station_type': {'siid': 8, 'piid': 29}, 'custom.voice_conf': {'siid': 8, 'piid': 30}, 'brush_left_time-15-1': {'siid': 15, 'piid': 1}, 'brush_life_level-15-2': {'siid': 15, 'piid': 2}, 'brush_left_time-12-1': {'siid': 12, 'piid': 1}, 'brush_life_level-12-2': {'siid': 12, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 11, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 11, 'piid': 2}, 'filter.filter_life_level': {'siid': 10, 'piid': 1}, 'filter.filter_left_time': {'siid': 10, 'piid': 2}, 'speaker.volume': {'siid': 9, 'piid': 1}, 'speaker.mute': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/47
```

**Comment by al-one** [comment]
@luzik It is recommended to put the device and HA on the same subnet.

**Comment by luzik** [comment]
@al-one thanks for a clue ! masquerade did the trick smooth :)

**Comment by heyjared** [comment]
I also updated to v0.5.0, now control of airer works with local.

But blinds are still not working
```
2022-01-12 11:58:35 ERROR (SyncWorker_15) [miio.miioprotocol] Got error when receiving: timed out
2022-01-12 11:58:35 ERROR (MainThread) [custom_components.xiaomi_miot.cover] Blinds Curtain: Got MiioException while fetching the state: No response from the device, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.status': {'siid': 2, 'piid': 4}, 'curtain.mode': {'siid': 2, 'piid': 5}, 'curtain.current_position': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'curtain.motor_reverse': {'siid': 2, 'piid': 8}}, max_properties: 5/7
```

This is what I have in my customize.yml
```
light.kejia_mzn_253a_light:
  miot_local: 'true'
cover.kejia_mzn_253a_airer:
  miot_local: 'true'
cover.090615_jldj03_9759_curtain:
  miot_local: 'true'
  chunk_properties: 5
```

**Comment by al-one** [comment]
@heyjared Try:
```yaml
# customize.yaml
cover.090615_jldj03_9759_curtain:
  chunk_properties: 1
```

**Comment by heyjared** [comment]
That did not seem to do anything. 
In fact, in v0.5.0, it seems I am now unable to control the blinds entirely regardless of `chunk_properties` or `miot_local` setting.

When it is using cloud, there are some logs: 
```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:431
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 1:21:24 PM (4 occurrences)
Last logged: 1:40:43 PM
Update for cover.090615_jldj03_9759_curtain fails

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 666, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/cover.py", line 126, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1124, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 47, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 62, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 71, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 150, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 431, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)
```

Although it says timeout, I am able to reach the host from my network using curl.

**Comment by al-one** [comment]
@heyjared Try with `miot_local: 'true'`:
```yaml
# customize.yaml
cover.090615_jldj03_9759_curtain:
  miot_local: 'true'
  chunk_properties: 1
```

**Comment by heyjared** [comment]
It still does not work, this is what I get 
```
2022-01-13 12:27:28 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: timed out
2022-01-13 12:27:28 ERROR (MainThread) [custom_components.xiaomi_miot.cover] Blinds Curtain: Got MiioException while fetching the state: No response from the device, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.status': {'siid': 2, 'piid': 4}, 'curtain.mode': {'siid': 2, 'piid': 5}, 'curtain.current_position': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'curtain.motor_reverse': {'siid': 2, 'piid': 8}}, max_properties: 1/7
```

**Comment by al-one** [comment]
@heyjared Maybe you can try to rebind this blinds in Mihome APP.
