### ISSUE TITLE
UI "Unknown error occurred" and HALog Traceback when login with notificationUrl

### ISSUE THREAD

**Issue by XMoon** [al-one/hass-xiaomi-miot#312]
Full Traceback log, for private I cut the notificationUrl.

```
2021-12-18 17:43:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 104, in check_xiaomi_account
    await mic.async_login()
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 286, in async_login
    return await self.hass.async_add_executor_job(self._login_request)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 292, in _login_request
    location = self._login_step2(sign)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 325, in _login_step2
    raise MiCloudAccessDenied(f'Login to xiaomi error: {response.text}')
custom_components.xiaomi_miot.core.xiaomi_cloud.MiCloudAccessDenied: Login to xiaomi error: &&&START&&&{"notificationUrl":"https://account.xiaomi.com/fe/service/verifyPhonexxxx","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":32,"pwd":0,"desc":"成功"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 215, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 387, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=renew)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 113, in check_xiaomi_account
    persistent_notification.create(
TypeError: create() takes from 2 to 4 positional arguments but 5 were given
```

**Comment by al-one** [comment]
Thinks ! The new version [v0.4.14](https://github.com/al-one/hass-xiaomi-miot/releases/latest) was released, please upgrade.
