### ISSUE TITLE
请问小爱音响接口是不是不能用了？

### ISSUE THREAD

**Issue by hanzch** [al-one/hass-xiaomi-miot#318]
前两天（11.21）还是好的，平时不太用，今天突然发现不能用了，设备在线，就是无法TTS，已确定音响联网，并且正常使用。

贴一下错误日志

`
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:409
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 13:00:33 (1 occurrences)
Last logged: 13:00:33

Update for media_player.xiaomi_l05b_f612_play_control fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f01d6880220>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Max retries exceeded with url: /app/miotspec/prop/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f01d6880220>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/media_player.py", line 295, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1054, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 47, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 62, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 71, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 151, in request_miot_api
    rsp = self.request(self.get_api_url(api), params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 409, in request
    response = self.session.post(url, data=post_data, timeout=self.http_timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Max retries exceeded with url: /app/miotspec/prop/get (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f01d6880220>: Failed to establish a new connection: [Errno -3] Try again'))
`

**Comment by al-one** [comment]
看样子你的HA无法连接米家API，请检查你的HA是否可以访问外网。
> [配置](https://my.home-assistant.io/redirect/config) > 设置与日志 > [信息](https://my.home-assistant.io/redirect/info) > `Xiaomi Miot Auto`

**Comment by hanzch** [comment]
> 看样子你的HA无法连接米家API，请检查你的HA是否可以访问外网。
> 
> > [配置](https://my.home-assistant.io/redirect/config) > 设置与日志 > [信息](https://my.home-assistant.io/redirect/info) > `Xiaomi Miot Auto`

感谢，拔掉电源重插确实好了，但是刚刚确认是可以联网和听音乐的，挺奇怪，我再关注下，有问题再请教，感谢

**Comment by al-one** [comment]
如果是hassio，有可能是supervisor下面的dns服务挂了，可以通过下面的命令重启dns服务：
```shell
ha dns info
ha dns restart
```
当然了，重启宿主机也同样能解决。

**Comment by hanzch** [comment]
> 如果是hassio，有可能是supervisor下面的dns服务挂了，可以通过下面的命令重启dns服务：
> 
> ```shell
> ha dns info
> ha dns restart
> ```
> 
> 当然了，重启宿主机也同样能解决。

感谢大佬的补充！~
