### ISSUE TITLE
viomi.vacuum.v18 Unable to discover device

### ISSUE THREAD

**Issue by r3pek** [al-one/hass-xiaomi-miot#349]
Hey!

I'm trying to get Viomi S9 to work with you integration but for some reason it still tries to connect locally to the vacuum and AFAIK this one only support reading information via the cloud, not locally.
This is what I get in the logs:

`
2022-01-03 13:01:14 ERROR (MainThread) [custom_components.xiaomi_miot.vacuum] Viomi S9 Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device 10.0.1.100, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.wdr_mode': {'siid': 2, 'piid': 11}, 'vacuum.door_state': {'siid': 2, 'piid': 12}, 'vacuum.contact_state': {'siid': 2, 'piid': 13}, 'vacuum-2.contact_state': {'siid': 2, 'piid': 15}, 'vacuum-2.contact_state-16': {'siid': 2, 'piid': 16}, 'vacuum.mute': {'siid': 2, 'piid': 17}, 'vacuum.sweep_type': {'siid': 2, 'piid': 4}, 'vacuum.mode': {'siid': 2, 'piid': 19}, 'voice.target_voice': {'siid': 8, 'piid': 3}, 'voice.cur_voice': {'siid': 8, 'piid': 4}, 'voice.download_status': {'siid': 8, 'piid': 5}, 'voice.download_progress': {'siid': 8, 'piid': 6}, 'voice.voice_url': {'siid': 8, 'piid': 7}, 'voice.voice_mdfive': {'siid': 8, 'piid': 8}, 'map.map_type': {'siid': 7, 'piid': 1}, 'map.map_id': {'siid': 7, 'piid': 2}, 'map.map_name': {'siid': 7, 'piid': 4}, 'map.lang': {'siid': 7, 'piid': 5}, 'map.arrange_room_ids': {'siid': 7, 'piid': 6}, 'map.target_room_id': {'siid': 7, 'piid': 7}, 'map.split_points': {'siid': 7, 'piid': 8}, 'map.room_name': {'siid': 7, 'piid': 9}, 'map.cur_cleaning_path': {'siid': 7, 'piid': 10}, 'map.map_list': {'siid': 7, 'piid': 11}, 'map.oper_result': {'siid': 7, 'piid': 13}, 'map.auto_area_id': {'siid': 7, 'piid': 14}, 'point_zone.target_point': {'siid': 6, 'piid': 1}, 'point_zone.zone_points': {'siid': 6, 'piid': 2}, 'point_zone.restrict_points': {'siid': 6, 'piid': 3}, 'order.order_id': {'siid': 5, 'piid': 1}, 'order.enable': {'siid': 5, 'piid': 2}, 'order.day': {'siid': 5, 'piid': 3}, 'order.hour': {'siid': 5, 'piid': 4}, 'order.minute': {'siid': 5, 'piid': 5}, 'order.repeat': {'siid': 5, 'piid': 6}, 'order.clean_way': {'siid': 5, 'piid': 8}, 'order.suction': {'siid': 5, 'piid': 9}, 'order.water': {'siid': 5, 'piid': 10}, 'order.twice_clean': {'siid': 5, 'piid': 11}, 'order.mapid': {'siid': 5, 'piid': 12}, 'order.room_count': {'siid': 5, 'piid': 13}, 'order.room_data': {'siid': 5, 'piid': 14}, 'order.dnd_enable': {'siid': 5, 'piid': 15}, 'order.dnd_start_hour': {'siid': 5, 'piid': 16}, 'order.dnd_start_minute': {'siid': 5, 'piid': 17}, 'order.dnd_end_hour': {'siid': 5, 'piid': 18}, 'order.dnd_end_minute': {'siid': 5, 'piid': 19}, 'order.dnd_timezone': {'siid': 5, 'piid': 20}, 'order.timestamp': {'siid': 5, 'piid': 21}, 'order.orderdata': {'siid': 5, 'piid': 22}, 'viomi_vacuum.repeat_state': {'siid': 4, 'piid': 1}, 'viomi_vacuum.remember_state': {'siid': 4, 'piid': 3}, 'viomi_vacuum.mop_route': {'siid': 4, 'piid': 6}, 'viomi_vacuum.side_brush_life': {'siid': 4, 'piid': 8}, 'viomi_vacuum.side_brush_hours': {'siid': 4, 'piid': 9}, 'viomi_vacuum.main_brush_life': {'siid': 4, 'piid': 10}, 'viomi_vacuum.main_brush_hours': {'siid': 4, 'piid': 11}, 'viomi_vacuum.hypa_life': {'siid': 4, 'piid': 12}, 'viomi_vacuum.hypa_hours': {'siid': 4, 'piid': 13}, 'viomi_vacuum.mop_life': {'siid': 4, 'piid': 14}, 'viomi_vacuum.mop_hours': {'siid': 4, 'piid': 15}, 'viomi_vacuum.direction': {'siid': 4, 'piid': 16}, 'viomi_vacuum.suction_grade': {'siid': 4, 'piid': 17}, 'viomi_vacuum.water_grade': {'siid': 4, 'piid': 18}, 'viomi_vacuum.map_num': {'siid': 4, 'piid': 23}, 'viomi_vacuum.time_zone': {'siid': 4, 'piid': 24}, 'viomi_vacuum.clean_start_time': {'siid': 4, 'piid': 25}, 'viomi_vacuum.clean_use_time': {'siid': 4, 'piid': 26}, 'viomi_vacuum.clean_area': {'siid': 4, 'piid': 27}, 'viomi_vacuum.clean_map_url': {'siid': 4, 'piid': 28}, 'viomi_vacuum.clean_mode': {'siid': 4, 'piid': 29}, 'viomi_vacuum.clean_way': {'siid': 4, 'piid': 30}, 'viomi_vacuum.cur_lang': {'siid': 4, 'piid': 31}, 'viomi_vacuum.cur_map_id': {'siid': 4, 'piid': 32}, 'viomi_vacuum.cur_map_url': {'siid': 4, 'piid': 33}, 'viomi_vacuum.last_update_time': {'siid': 4, 'piid': 34}, 'viomi_vacuum.consumable_index': {'siid': 4, 'piid': 35}, 'viomi_vacuum.clean_room_mode': {'siid': 4, 'piid': 36}, 'viomi_vacuum.clean_room_oper': {'siid': 4, 'piid': 37}, 'viomi_vacuum.clean_room_ids': {'siid': 4, 'piid': 38}, 'viomi_vacuum.has_map': {'siid': 4, 'piid': 39}, 'viomi_vacuum.has_newmap': {'siid': 4, 'piid': 40}, 'viomi_vacuum.dust_collection': {'siid': 4, 'piid': 41}, 'battery.battery_level': {'siid': 3, 'piid': 1}}, max_properties: 10/86
`

I tried commenting out the "[viomi.vacuum.v18](https://home.miot-spec.com/s/viomi.vacuum.v18)" line in miot_local_devices.py but looks like it stills tries to connect locally. Anything else I could try?

**Comment by r3pek** [comment]
ok... got it to work with
```
        'miot_local': False,
        'miot_cloud': True,
```
added to devices_customizes.py under "viomi.vacuum.*" (maybe I should just configure it to use the cloud instead of "auto"?)

**Comment by al-one** [comment]
> Unable to discover the device 10.0.1.100

Please confirm your device IP.

**Comment by r3pek** [comment]
> Please confirm your device IP.

It is correct and "pingable"

**Comment by al-one** [comment]
Are subnets divided ?

**Comment by r3pek** [comment]
Yeah. HASS is on 10.0.0.0/24. The vacuum is on 10.0.1.0/24

**Comment by al-one** [comment]
It is recommended that they be divided into the same subnet.

- https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets
- https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152

**Comment by r3pek** [comment]
Also tried on the same subnet before, no difference. That's why "sent it" there. Also, looks like everything is working with the changes I made... Yet, I still get this on the logs:
```
2022-01-03 15:46:18 WARNING (SyncWorker_15) [custom_components.xiaomi_miot.vacuum] Viomi S9 Robot Cleaner: Got miio properties ['run_state', 'mode', 'err_state', 'battary_life', 'box_type', 'mop_type', 's_time', 's_area', 'suction_grade', 'water_grade', 'remember_map', 'has_map', 'is_mop', 'has_newmap'] failed: Unable to discover the device 10.0.1.100
```

**Comment by al-one** [comment]
Please try the latest [commit](https://github.com/al-one/hass-xiaomi-miot/commit/c5e0ea0d9c22c21e22c66fde3cc4f74ba3f19d9b) of branch [v0.4.x](https://github.com/al-one/hass-xiaomi-miot/tree/v0.4.x):
```shell
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -
```

**Comment by r3pek** [comment]
Nop. Went back to the original error.

**Comment by al-one** [comment]
Try this configuration:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      exclude_miot_services: order,point_zone,map,voice
```

> [⚙️  Configuration](https://my.home-assistant.io/redirect/config) > [Server Controls](https://my.home-assistant.io/redirect/server_controls) > YAML configuration reloading > `XIAOMI MIOT AUTO`

**Comment by r3pek** [comment]
Same. I still had the "connection mode" set to "auto". If I force it to "cloud" it works as after my manual patches

**Comment by al-one** [comment]
If you don't mind it working with cloud, try this configuration:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      miot_cloud: true
```

> [⚙️  Configuration](https://my.home-assistant.io/redirect/config) > [Server Controls](https://my.home-assistant.io/redirect/server_controls) > YAML configuration reloading > `XIAOMI MIOT AUTO`

**Comment by al-one** [comment]
If there is no problem with the network, I think there may be too many attributes queried at the same time, so that the device cannot respond. Try this command in terminal:
```shell
miiocli device --ip 10.0.1.100 --token xxxxxx raw_command get_properties "[{'did': 'miot', 'siid': 2, 'piid': 1}, {'did': 'miot', 'siid': 2, 'piid': 2}]"
```

**Comment by r3pek** [comment]
OK. So, I added a rule on the router that MASQUERADEs the source IP when going from one network to the other and now, your `rawcommand` works:
```
[{'code': 0, 'did': 'miot', 'piid': 1, 'siid': 2, 'value': 4}, {'code': 0, 'did': 'miot', 'piid': 2, 'siid': 2, 'value': 0}]
```

Yet, the HASS log says it timeouts:
```
2022-01-03 16:33:53 WARNING (SyncWorker_0) [custom_components.xiaomi_miot.vacuum] Viomi S9 Robot Cleaner: Got miio properties ['run_state', 'mode', 'err_state', 'battary_life', 'box_type', 'mop_type', 's_time', 's_area', 'suction_grade', 'water_grade', 'remember_map', 'has_map', 'is_mop', 'has_newmap'] failed: {'code': -9999, 'message': 'user ack timeout'}
```

**Comment by al-one** [comment]
Please ensure that you upgrade to the last commit of branch [v0.4.x](https://github.com/al-one/hass-xiaomi-miot/tree/v0.4.x), check your component code:
https://github.com/al-one/hass-xiaomi-miot/blob/c5e0ea0d9c22c21e22c66fde3cc4f74ba3f19d9b/custom_components/xiaomi_miot/vacuum.py#L66-L67

**Comment by r3pek** [comment]
Yeah... that line is there.

**Comment by al-one** [comment]
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      miio_properties: null
```

**Comment by r3pek** [comment]
```
2022-01-03 17:01:17 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up xiaomi_miot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 52, in async_setup_entry
    await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 472, in async_setup_config_entry
    await async_setup_platform(hass, c, async_add_entities)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 67, in async_setup_platform
    entities.append(MiotVacuumEntity(config, srv))
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 82, in __init__
    super().__init__(miot_service, config=config, logger=_LOGGER)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 919, in __init__
    if custom := DEVICE_CUSTOMIZES.get(self._model, {}).get('miot_mapping'):
AttributeError: 'NoneType' object has no attribute 'get'
```
I still had the `miot_cloud: true` line in there. As soon as I removed it, that message popped up (adding the miio_properties line didn't help)

**Comment by al-one** [comment]
```yaml
​#​ configuration.yaml​
xiaomi_miot:
```

Not:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
```

**Comment by r3pek** [comment]
Just to be sure I tested all this alternatives:
```
xiaomi_miot:
  device_customizes:
    miio_properties: null
    viomi.vacuum.v18:
```

```
xiaomi_miot:
  miio_properties: null
```

```
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      miio_properties: null
```
Same traceback as before

**Comment by al-one** [comment]
```yaml
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      miio_properties: []
```

**Comment by r3pek** [comment]
Same thing

**Comment by r3pek** [comment]
Got it to work. Had to replace this:
https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/__init__.py#L929

to:
`if custom := (self.global_config('device_customizes') or {}).get(self._model, {}).get('miot_mapping'):`

**Comment by al-one** [comment]
Please upgrade master branch and try again.
```shell
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=master bash -
```

**Comment by r3pek** [comment]
@al-one all working nice without anything on the configuration file

**Comment by r3pek** [comment]
spoke too soon.... had to re-add the `null` line or it would `failed: {'code': -9999, 'message': 'user ack timeout'}`

**Comment by al-one** [comment]
Try master branch again without yaml.

**Comment by al-one** [comment]
Formatting attribute values is not currently supported, but this is a good suggestion, and I will consider supporting it in future versions.

**Comment by al-one** [comment]
It is now supported to format entity attributes by configuring `attributes_template`:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      attributes_template: |-
        {%- set dat = namespace(data,clean_use_time='00:00') %}
        {%- set tim = data['viomi_vacuum.clean_use_time'] | default(0) | int(0) %}
        {%- set dat.clean_use_time = tim | timestamp_custom('%H:%M:%S',False) %}
        {{ dat._Namespace__attrs }}
```

**Comment by r3pek** [comment]
Throws me this error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1267, in async_update
    self.update_attrs(attrs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 891, in update_attrs
    tpl = cv.template(tpl)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 575, in template
    raise vol.Invalid(f"invalid template ({ex})") from ex
voluptuous.error.Invalid: invalid template (TemplateSyntaxError: unexpected end of template, expected ','.)

```

**Comment by al-one** [comment]
Weird, I checked the template again and it seems to be fine.

**Comment by r3pek** [comment]
> Weird, I checked the template again and it seems to be fine.

yeah.... also didn't see anything wrong with it. Was just in doubt if the `data['viomi_vacuum.clean_use_time']` should be the actually vacuum entity (in my case `vacuum.viomi_v18_e271_robot_cleaner`), a replaced it for `data['viomi_v18_e271_robot_cleaner.clean_use_time']` but also didn't work

**Comment by al-one** [comment]
Upgrade to master branch and try:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      attributes_template: |-
        {%- set tim = data['viomi_vacuum.clean_use_time'] | default(0) | int(0) %}
        {{ {
        'viomi_vacuum.clean_use_time': tim | timestamp_custom('%H:%M:%S',False),
        } }}
```

**Comment by r3pek** [comment]
nop.... almost the same error :( now it complains about line 3 :confused: 
```
xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in ensure_valid
    self._compiled_code = self._env.compile(self.template)  # type: ignore[no-untyped-call]
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2016, in compile
    cached = self.template_cache[source] = super().compile(source)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 3, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 572, in template
    template_value.ensure_valid()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 357, in ensure_valid
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TemplateSyntaxError: unexpected end of template, expected ','.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1272, in async_update
    self.update_attrs(attrs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 891, in update_attrs
    tpl = cv.template(tpl)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 575, in template
    raise vol.Invalid(f"invalid template ({ex})") from ex
voluptuous.error.Invalid: invalid template (TemplateSyntaxError: unexpected end of template, expected ','.)
```

**Comment by al-one** [comment]
Try `attributes_template: |`, not `attributes_template: |-`.

**Comment by r3pek** [comment]
> Try `attributes_template: |`, not `attributes_template: |-`.

same error as before. I did try with a few more variations trying to simplify the template to get it to print "something".
With this:

```
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      attributes_template: |
        {%- set tim = data['viomi_vacuum.clean_use_time'] | default(0) | int(0) %}
        {{ { 'viomi_vacuum.clean_use_time': tim } }}
```
I get this:
```
xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1272, in async_update
    self.update_attrs(attrs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 893, in update_attrs
    adt = tpl.render({'data': self._state_attrs}) or {}
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 375, in render
    return run_callback_threadsafe(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 51, in run_callback_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop
```

Don't know if it helps or not.... templating is not my strong stuff :P (maybe I do need to get into it)

**Comment by al-one** [comment]
Upgrade to master branch and try:
```yaml
​#​ configuration.yaml​
xiaomi_miot:
  device_customizes:
    viomi.vacuum.v18:
      attributes_template: |-
        {%- set tim = data['viomi_vacuum.clean_use_time'] | default(3651) | int(0) %}
        {{ { 'clean_use_time': (tim | timestamp_utc(''))[-14:-6] | default('00:00') } }}
```

**Comment by r3pek** [comment]
YAY! Working now ;) thx a bunch!
