### ISSUE TITLE
chuangmi.camera.ipc019摄像头无图像

### ISSUE THREAD

**Issue by qiuyuxuan1999** [al-one/hass-xiaomi-miot#35]
先感谢大佬插件，有如下问题

云账号模式添加摄像头，有2个实体出现并可用，一个摄像头开关实体，一个摄像头实体。但摄像头实体无法显示图像。实体记录没有，实体图像url里也没有。
![image](https://user-images.githubusercontent.com/64347554/111249912-68900100-8647-11eb-8b6c-d2a6f34f5e53.png)

![image](https://user-images.githubusercontent.com/64347554/111250065-a856e880-8647-11eb-8b08-e54e3f8586d4.png)

![image](https://user-images.githubusercontent.com/64347554/111250107-b73d9b00-8647-11eb-8ff2-4718e87e8026.png)

日至报错如下：
Logger: aiohttp.server
Source: custom_components/xiaomi_miot/camera.py:219
First occurred: 上午10:47:15 (10 occurrences)
Last logged: 上午11:04:50

Error handling request
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/camera/__init__.py", line 502, in get
    return await self.handle(request, camera)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/camera/__init__.py", line 537, in handle
    return await camera.handle_async_mjpeg_stream(request)
  File "/volume1/@appstore/homeassistant/var/config/custom_components/xiaomi_miot/camera.py", line 219, in handle_async_mjpeg_stream
    await stream.close()
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/haffmpeg/core.py", line 158, in close
    await self._loop.run_in_executor(None, _close)
  File "/var/packages/python38/target/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/haffmpeg/core.py", line 153, in _close
    self._proc.stdin.write(b"q")
BrokenPipeError: [Errno 32] Broken pipe

我的安装环境如下
System Health

version: 2021.1.5
installation_type: Home Assistant Core
dev: false
hassio: false
docker: false
virtualenv: true
python_version: 3.8.7
os_name: Linux
os_version: 3.10.105
arch: armv7l
timezone: Asia/Shanghai

麻烦能否看下什么问题，多谢。

**Comment by al-one** [comment]
这个报错我也遇到过，不过是偶发的，具体原因不明。

**Comment by qiuyuxuan1999** [comment]
> 这个报错我也遇到过，不过是偶发的，具体原因不明。

感谢回复。但我的摄像头没图像是稳定存在的，不知道有无方法解决。

**Comment by al-one** [comment]
你的摄像头`chuangmi.camera.ipc019`属性`video_attribute`格式为：
```json
{
	"property": "video-attribute",
	"desc": "Video Attribute",
	"access": "",
	"format": "uint8",
	"value-list": [{
		"value": 0,
		"description": "Auto"
	}, {
		"value": 1,
		"description": "1920_1080_20"
	}, {
		"value": 2,
		"description": "640_360_20"
	}]
}
```

你可以尝试更改自定义属性`video_attribute: 2`以降低视频清晰度，如下：
```yaml
# customize.yaml (Configuration > Customize > Select Entity > Add Other Attribute)
camera.your_entity_id:
  video_attribute: 2
```

**Comment by qiuyuxuan1999** [comment]
> 你的摄像头`chuangmi.camera.ipc019`属性`video_attribute`格式为：
> 
> ```json
> {
> 	 “ property ”：“ video-attribute ”，
> 	 “ desc ”：“ Video Attribute ”，
> 	 “ access ”：“ ”，
> 	 “ format ”：“ uint8 ”，
> 	 “ value-list ”：[{
> 		 “ value ”：0，
> 		 “描述“：”自动“
> 	}，{
> 		“值”： 1，
> 		 “描述”： “ 1920_1080_20 ”
> 	}，{
> 		“值”： 2，
> 		 “描述”： “ 640_360_20 ”
> 	}]
> }
> ```
> 
> 您可以尝试更改自定义属性`video_attribute: 2`以降低视频清晰度，如下：
> 
> ```yaml
> ＃ customize.yaml（“配置”>“自定义”>“选择实体”>“添加其他属性”）
> camera.your_entity_id：
>    video_attribute： 2
> ```

大佬，试过了，还是不行，仍然报错，没有图像。
![image](https://user-images.githubusercontent.com/64347554/111259944-e9a4c380-865a-11eb-914d-51022f37a73d.png)

![image](https://user-images.githubusercontent.com/64347554/111259989-fc1efd00-865a-11eb-968a-49a3a8d76a38.png)

![image](https://user-images.githubusercontent.com/64347554/111260039-13f68100-865b-11eb-886d-01cdf4225f5e.png)

**Comment by qiuyuxuan1999** [comment]
但是这次图片报错不是500了，是401，Unauthorized
![image](https://user-images.githubusercontent.com/64347554/111263963-b3b70d80-8661-11eb-9673-2edf9faadc8f.png)

**Comment by al-one** [comment]
开启插件debug日志，在日志中找到小米服务器的m3u8流地址，然后在PC用播放器如VLC播放试试。注意每个流地址只有5分钟有效时间。

**Comment by qiuyuxuan1999** [comment]
> 开启插件debug日志，在日志中找到小米服务器的m3u8流地址，然后在PC用播放器如VLC播放试试。注意每个流地址只有5分钟有效时间。

刚试过了大佬，debug找到m3u8地址，播放不了。
