### ISSUE TITLE
突然出现无法连接小米云服务，报Max retries exceeded， Failed to establish a new connection: [Errno -3] Try again

### ISSUE THREAD

**Issue by DenneyTang** [al-one/hass-xiaomi-miot#354]
2022-01-04 21:36:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa52391f0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: **HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by NewConnectionError**('<urllib3.connection.HTTPSConnection object at 0x7fa52391f0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/318#issuecomment-1000068587
- https://github.com/al-one/hass-xiaomi-miot/issues/318#issuecomment-1000247112

**Comment by DenneyTang** [comment]
已经搞定了，不是插件的问题。是我的hassio_dns莫名其妙出问题了，搞了几天，把过程记录下供后人参考。

最开始的现象是突然发现整个系统很慢，很卡（树莓派3，HASS OS 6.6），这是从开始安装HACS发生的，随后登陆host排除发现是systemd-journald大量占用内存，找了好久，发现是由于hassio_audio的一个bug引发的内存泄露引发，随后按github上的一个addon安装后跑了一次发现似乎这个内存泄露的问题搞定。随之又触发了另外的bug和这个无法连接有关，dns出问题了。。

表现为大量报错无法请求github服务、hass-xiaomi-miot也一直报错无法连接，同时hassio_dns容器占用大量的cpu，系统又开始变得很卡。开始怀疑是我的科学上网出问题了被dns污染导致的，因为HACS确实有一个问题会大量连接github触发限流机制，走了不少弯路折腾很久科学上网。后来醒悟过来为什么一定要HACS呢，索性删之，发现问题依旧，hass-xiaomi-miot还是报无法连接，问题越来越聚焦了，dns应该有问题，又无法解析，还大量占用CPU。

ssh登陆host，用nslookup验证了一下，确认完全无法解析任何域名，遂目标是搞定dns问题了。做法也简单，重新部署hassio_dns。先停掉容器，然后删除hassio_dns镜像，重启host，supervisor会自动重新下载镜像部署容器，问题解决，cpu也恢复正常。
