### ISSUE TITLE
突然不能连接小米云服务，提示api.io.mi.com连接超时

### ISSUE THREAD

**Issue by iwnsly** [al-one/hass-xiaomi-miot#355]
日志如下：

日志详细信息（ ERROR ）
此错误来自自定义集成。
Logger: aiohttp.server
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:431
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 20:14:18 (1 occurrences)
Last logged: 20:14:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 262, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/config/custom_components/xiaomi_miot/config_flow.py", line 105, in check_xiaomi_account
    if not await mic.async_check_auth(False):
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 107, in async_check_auth
    rdt = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 87, in get_user_device_data
    rdt = self.request_miot_api('user/get_user_device_data', params) or {}
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 149, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 431, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

**Comment by al-one** [comment]
请先参考这里检查下：
- https://github.com/al-one/hass-xiaomi-miot/issues/354#issuecomment-1005350717

**Comment by iwnsly** [comment]
重新登录帐号，提示 Unknown error occurred

**Comment by iwnsly** [comment]
登录输入错的密码，提示：
Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:121
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 20:29:26 (2 occurrences)
Last logged: 20:29:51

Setup xiaomi cloud for user:   failed: Login to xiaomi error: &&&START&&&{"result":"error","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","description":"登录验证失败","location":"","securityStatus":0,"pwd":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","desc":"登录验证失败"}

但输入对的密码就提示Unknown error occurred
日志就是最上面的那些。。。

**Comment by iwnsly** [comment]
> 

检查过了 dns 没问题，在docker 里的主机 ping 地址都是通的，奇怪

**Comment by al-one** [comment]
我在刚才的提交中延长了检查登录状态接口的超时时间，请更新到master分支后再试下。

**Comment by iwnsly** [comment]
the problem is still the same.
更新了还是不行。我重新安装了 docker 里的主机（群晖 nas）
重新安装了 ha 和 HACS、xiaomi-miot
登录 xiaomi帐号时，还是报 unknown error，但输入错的密码就有验证失败的提示
网络是北京移动200M宽带，速度很快

---
不知道什么问题了，可能是服务器端的？等几天再看看

**Comment by al-one** [comment]
应该不是米家服务端的问题，因为没有其他人反馈。请检查日志中的报错仍然是`requests.exceptions.ReadTimeout`。

**Comment by iwnsly** [comment]
> 应该不是米家服务端的问题，因为没有其他人反馈。请检查日志中的报错仍然是`requests.exceptions.ReadTimeout`。

改了一下帐户密码，通过了，可以登录了
原来的密码里有 ! 这个字符，去掉就 ok 了，问题可以复现

**Comment by iwnsly** [comment]
应该是前些天改了密码导致的问题
