### ISSUE TITLE
日志报大量的： Connection pool is full, discarding connection: api.io.mi.com

### ISSUE THREAD

**Issue by DenneyTang** [al-one/hass-xiaomi-miot#384]
log：
2022-01-15 20:52:47 ERROR (MainThread) [homeassistant.components.media_player] Platform xiaomi_miot does not generate unique IDs. ID 7c:49:eb:6e:90:56-0d2e0359aefdd5fb0cf63c52d7ce391f-4 is already used by media_player.xiaomi_lx01_9056_play_control - ignoring xiaomi_miot.xiaomi_lx01_9056_play_control
2022-01-15 20:52:48 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID c4:7c:8d:63:a6:cf-0d2e0359aefdd5fb0cf63c52d7ce391f-2 is already used by sensor.hhcc_v1_a6cf_plant_monitor - ignoring xiaomi_miot.hhcc_v1_a6cf_plant_monitor
2022-01-15 20:52:49 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d00010d6b57-0d2e0359aefdd5fb0cf63c52d7ce391f-2 is already used by sensor.lumi_v1_6b57_temperature_humidity_sensor - ignoring xiaomi_miot.lumi_v1_6b57_temperature_humidity_sensor
2022-01-15 20:52:49 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot does not generate unique IDs. ID lumi.158d0001d8370d-0d2e0359aefdd5fb0cf63c52d7ce391f-2 is already used by sensor.lumi_v1_370d_smoke_sensor - ignoring xiaomi_miot.lumi_v1_370d_smoke_sensor
2022-01-15 20:52:50 WARNING (MainThread) [custom_components.xiaomi_miot.climate] climate.zhimi_ua1_3dd6_air_fresh has been deprecated and will be removed in a future version. Please use fan.zhimi_ua1_3dd6_air_fresh.
2022-01-15 20:53:38 WARNING (SyncWorker_41) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_50) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_57) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_54) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_0) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_63) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:53:38 WARNING (SyncWorker_52) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:54:08 WARNING (SyncWorker_35) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:55:08 WARNING (SyncWorker_11) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:55:08 WARNING (SyncWorker_62) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com
2022-01-15 20:55:08 WARNING (SyncWorker_16) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com

**Comment by al-one** [comment]
请参考下[这里](https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-full-discarding-connection)或重启HA宿主机试试。

**Comment by DenneyTang** [comment]
> 请参考下[这里](https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-full-discarding-connection)或重启HA宿主机试试。

重启做过很多次了。虽然实际上这个告警只是一个warning，也没实际影响使用，但看着一大片的告警还是很消耗资源。

我看了下你给的参考，看样子还是urllib3的maxsize影响到了连接pool的数量，也不知道是不是我的设备比较多，大概45个左右。

不知道调整maxsize对整体的性能影响有多大？能否适当调高？当然CPU和内存消耗会高些。

另外我按你另外一个链接，设置了设备的更新间隔时间，也被告警了，是什么原因呢？

> [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 62 and 64



> 
@dvdblk: There's no "balance" between warnings and performance: to get no warnings just make your maxsize equal to the number of worker threads you're using. That way all connections will be kept in the pool for reuse, hence no warnings. And to improve performance, just increase your worker threads. I've read that around 4-5 threads per CPU core is optimal for internet (i.e. slow) I/O. – 
MestreLion
 May 26 '21 at 7:03
1
@shazow: the update was a great improvement! But a statement like "it will limit how many connections are allowed per host" is still inaccurate: urllib3 will always open as many connections as you request, even if it discards some after usage. – 
MestreLion
 May 26 '21 at 7:10 
1
@dvdblk: Setting worker threads in aiohttp is completely out of the scope for this question, but you surely can do it, just check its documentation on connectors – 
MestreLion
 May 27 '21 at 5:39
Show 4 more comments

5

According to the documentation on Customizing Pool Behavior, neither of your interpretations are correct:

By default, if a new request is made and there is no free connection in the pool then a new connection will be created. However, this connection will not be saved if more than maxsize connections exist. This means that maxsize does not determine the maximum number of connections that can be open to a particular host, just the maximum number of connections to keep in the pool.

(my emphasis)

So connections were not aborted to be retried later. They were made immediately, as requested, and results returned. Then, after they have completed, those "extra" connections were discarded, i.e., they were not kept in the pool for later reuse.

For example, if your maxsize is 10 (the default when using urllib3 via requests), and you launch 50 requests in parallel, those 50 connections will be performed at once, and after completion only 10 will remain in the pool while 40 will be discarded (and issue that warning).

**Comment by al-one** [comment]
你是否使用的是自动模式？自动模式下会使用本地模式连接局域网中的设备，会大大减小对米家接口的请求。
如果想通过增加轮询间隔时间也是可以的，参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
- https://github.com/al-one/hass-xiaomi-miot/issues/310#issuecomment-996776691

**Comment by DenneyTang** [comment]
谢谢！我用的自动模式没错，不过还没升级到最新5.0版本。应该还是全部走的小米接口，我试试回来反馈。

**Comment by al-one** [comment]
v0.5之前的版本如果设备在[支持本地miot的设备列表](https://www.github.com/al-one/hass-xiaomi-miot/tree/master/custom_components/xiaomi_miot/core/miot_local_devices.py)中也会用本地模式。

**Comment by DenneyTang** [comment]
### **感觉还是很困扰，设置了轮询时间，但是感觉没生效，一直在报：contains duplicate key "interval_seconds"**

# configuration.yaml
```
xiaomi_miot:
  device_customizes:
    '*.light.*':
      interval_seconds: 120
    '*.plug.*':
      interval_seconds: 120
```

### **Log一直提示“contains duplicate key "interval_seconds"”**

```
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 76 and 78
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 78 and 80
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 80 and 82
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 82 and 84
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 84 and 86
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 86 and 88
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 88 and 90
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 90 and 92
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 92 and 94
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 94 and 96
2022-01-23 22:49:09 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "interval_seconds". Check lines 96 and 98
```


### **日志里还是大片大片的Connection pool is full, Connection pool size: 10**

![image](https://user-images.githubusercontent.com/19922795/150685503-984ee065-f58e-440d-929d-2a0718035cb6.png)

**Comment by al-one** [comment]
请截图你的配置文件(私密信息请打码)。另外检查下你的dns服务器。

**Comment by DenneyTang** [comment]
配置如下：

![Screenshot_20220124_010324](https://user-images.githubusercontent.com/19922795/150689707-23493328-f6b2-4361-a7c7-534cde86ff0e.jpg)



然后DNS之前也检查过，我已经科学上网了，我也在ha core 的容器里nslookup检查过github解析正常。不知还有什么办法

**Comment by al-one** [comment]
`interval_seconds: 120`少了一次缩进。

**Comment by DenneyTang** [comment]
> `interval_seconds: 120`少了一次缩进。不同类型的延迟时长也可以设置的不一样，这样也可以错开请求小米接口。

好的，多谢大佬，我先重新调一下格式和时间看看。

另外，我把带上报错的完整日志也贴一下，你帮忙看看有没有什么异常，谢谢！

比如：
`socket.timeout: _ssl.c:1112: The handshake operation timed out
`
`urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)
`
```
2022-01-24 09:39:00 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-24 09:39:00 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-24 09:39:26 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2022-01-24 09:39:26 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2022-01-24 09:39:26 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2022-01-24 09:39:26 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2022-01-24 09:39:26 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-01-24 09:39:39 WARNING (MainThread) [homeassistant.components.light] Setup of light platform mqtt is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.device_tracker] Setup of device_tracker platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.remote] Setup of remote platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.humidifier] Setup of humidifier platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:01 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:02 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:02 WARNING (MainThread) [homeassistant.components.button] Setup of button platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:02 WARNING (MainThread) [homeassistant.components.number] Setup of number platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:02 WARNING (MainThread) [homeassistant.components.water_heater] Setup of water_heater platform xiaomi_miot is taking over 10 seconds.
2022-01-24 09:40:09 WARNING (MainThread) [custom_components.xiaomi_miot.climate] climate.dmaker_t2017_4bab_air_fresh has been deprecated and will be removed in a future version. Please use fan.dmaker_t2017_4bab_air_fresh.
2022-01-24 09:40:10 WARNING (MainThread) [custom_components.xiaomi_miot.climate] climate.zhimi_ua1_3dd6_air_fresh has been deprecated and will be removed in a future version. Please use fan.zhimi_ua1_3dd6_air_fresh.
2022-01-24 09:40:10 WARNING (MainThread) [custom_components.xiaomi_miot.climate] climate.dmaker_t2017_7c1c_air_fresh has been deprecated and will be removed in a future version. Please use fan.dmaker_t2017_7c1c_air_fresh.
2022-01-24 09:43:54 WARNING (SyncWorker_5) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:43:54 WARNING (SyncWorker_11) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:43:54 WARNING (SyncWorker_13) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:43:54 WARNING (SyncWorker_18) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:43:55 WARNING (SyncWorker_0) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:45:54 WARNING (SyncWorker_8) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:45:54 WARNING (SyncWorker_15) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:45:54 WARNING (SyncWorker_21) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:45:55 WARNING (SyncWorker_1) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:45:55 WARNING (SyncWorker_20) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:47:54 WARNING (SyncWorker_2) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:47:54 WARNING (SyncWorker_1) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:47:54 WARNING (SyncWorker_17) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:47:54 WARNING (SyncWorker_8) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:47:55 WARNING (SyncWorker_16) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:49:54 WARNING (SyncWorker_12) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:49:55 WARNING (SyncWorker_25) [urllib3.connectionpool] Connection pool is full, discarding connection: api.io.mi.com. Connection pool size: 10
2022-01-24 09:50:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.dmaker_t2017_4bab_air_fresh is taking over 10 seconds
2022-01-24 09:50:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.lumi_mcn02_305e_air_conditioner is taking over 10 seconds
2022-01-24 09:50:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.lumi_mcn02_b0e6_air_conditioner is taking over 10 seconds
2022-01-24 09:50:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.dmaker_t2017_4bab_air_fresh is taking over 10 seconds
2022-01-24 09:50:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of fan.dmaker_t2017_7c1c_air_fresh is taking over 10 seconds
2022-01-24 09:50:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for fan.dmaker_t2017_4bab_air_fresh fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1208, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 47, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 62, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 71, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 154, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 441, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)
2022-01-24 09:50:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for fan.dmaker_t2017_7c1c_air_fresh fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1208, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 47, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 62, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 71, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 154, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 441, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
```
