### ISSUE TITLE
Recurring timeout error in HA log for host api.io.mi.com

### ISSUE THREAD

**Issue by pplucky** [al-one/hass-xiaomi-miot#394]
I currently have an [Aquarium (hfjh.fishbowl.v2)](https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Afish-tank%3A0000A0A2%3Ahfjh-v2%3A2) connected to HA via your custom component.

I have recently noticed that I have timeout errors in HA log, caused by your custom component, like the following:
```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:431
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: January 15, 2022, 16:00:28 (43 occurrences)
Last logged: 14:06:09

Update for switch.aquario fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/switch.py", line 93, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1275, in async_update
    await self.hass.async_add_executor_job(partial(self.update_miio_cloud_props, pls))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1365, in update_miio_cloud_props
    rdt = mic.request_miot_api('device/batchdevicedatas', [pms]) or {}
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 150, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 431, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)
```

The underlying device integrated is set as 'Automatic' in Connection Mode.

My yaml config is the following:
```yaml
xiaomi_miot:
### Enable Xiaomi Cloud
#   username: !secret xiaomi_cloud_username
#   password: !secret xiaomi_cloud_password
### Ideas taken from https://github.com/al-one/hass-xiaomi-miot/issues/326
  device_customizes:
    hfjh.fishbowl.v2:
### Generate number entities for pump flux, brightness and led color
      number_properties: pump_flux,ledboard_brightness,ledboard_color 
### Generate a button entity to trigger the action to feed the fish
      button_actions: set_feed_single
### Add attribute to keep track of latest feed-record event
      miio_cloud_props: event.4.1
    zhimi.heater.mc2:
### Assign a different temp sensor to climate entity generated for heater
      bind_sensor: sensor.temperature_158d0001571539
### Generate switches for heater on/off + alarm on/off
      switch_properties: heater.on,alarm
    careli.fryer.maf02:
### Generate a sensor entity to show the remaining cooking time
      sensor_properties: air_fryer.left_time
  exclude_state_attributes:
### Generic attributes to exclude
    - mac_address
### Heater attributes to exclude
    - private_service.hw_enable
    - private_service.use_time
    - private_service.country_code
### Aquarium attributes to exclude
    - function.mcu_type
    - function.mcu_type_new
    - function.key_switch
    - function.feed_time_week
    - function.feed_num
    - function.feed_time
    - function.feed_time_switch
    - function.ledboard_time_switch
    - function.ledboard_time_open
    - function.ledboard_time_close
    - function.ledboard_model
    - function.ledboard_sun
    - function.ledboard_stream
    - function.ledboard_speed
    - function.ledboard_time_switch
    - function.ledboard_time_open
    - function.ledboard_time_close
### Air Fryer attributes to exclude
    - home_room
```

I have 2 questions regarding these:
- Why is the custom component connecting to host='api.io.mi.com', port=443, if the State updater is lan?
- How can I "hide" these errors (assuming they're temporary and not affecting functionality - maybe reducing the check interval would also help reduce it), considering that I already have this in my configuration:
```yaml
logger:
  logs:
    custom_components.xiaomi_miot: critical
```
and the errors still appear?

Thanks in advance for your all your great work and help.

**Comment by al-one** [comment]
> Why is the custom component connecting to host='api.io.mi.com', port=443, if the State updater is lan?

`miio_cloud_props: event.4.1` needs to be obtained from Xiaomi cloud.

----

> How can I "hide" these errors (assuming they're temporary and not affecting functionality - maybe reducing the check interval would also help reduce it), considering that I already have this in my configuration:

```yaml
logger:
  filters:
    homeassistant.helpers.entity:
      - "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443)"
```
https://www.home-assistant.io/integrations/logger#log-filters

**Comment by pplucky** [comment]
> > Why is the custom component connecting to host='api.io.mi.com', port=443, if the State updater is lan?
> 
> `miio_cloud_props: event.4.1` needs to be obtained from Xiaomi cloud.

That was my suspicion, thanks for confirming.

> > How can I "hide" these errors (assuming they're temporary and not affecting functionality - maybe reducing the check interval would also help reduce it), considering that I already have this in my configuration:
> 
> ```yaml
> logger:
>   filters:
>     homeassistant.helpers.entity:
>       - "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443)"
> ```
> 
> https://www.home-assistant.io/integrations/logger#log-filters

Damn, sorry for missing that in documentation. I honestly had no idea this was possible at all. Really sorry. Thanks again.
