### ISSUE TITLE
ZDG300 mop robot missing "start / pause" commands

### ISSUE THREAD

**Issue by PWSteal** [al-one/hass-xiaomi-miot#401]
Hi, I have ZDG300 mop robot ([kxf321.mop.mo001](https://home.miot-spec.com/s/kxf321.mop.mo001l)) that I was able to control from Home Assistant via cloud, but in latest 0.4.x-0.5 versions of your component the "start, start / pause" command for robot got missing.

<details><summary>Now I have a card for mop robot that looks like this:</summary>
<p>

![mop_robot_card](https://user-images.githubusercontent.com/39002058/150625948-692af041-1eea-4b3f-976e-d2a7ff9d2d9c.png)

</p>
</details>

Before this issue there was a "start" ("pause" when cleaning) button next to "stop" and  "return to base". Now it's gone.
I can control mop robot from Mi Home without problem (starting / pausing also).

Attributes for the entity vacuum.kxf321_mo001_490c_mopping_machine:
<details><summary>returning</summary>
<p>

```
fan_speed_list: Dry, Basic, Strong
battery_level: 101
battery_icon: mdi:battery
fan_speed: Basic
model: kxf321.mop.mo001
lan_ip: 192.168.1.141
mac_address: 44:23:7C:FE:49:0C
entity_class: MiotVacuumEntity
home_room: Чайковского Прихожая
miot_type: urn:miot-spec-v2:device:mopping-machine:0000A064:kxf321-mo001:1
mopping_machine.status: 7
mopping_machine.mode: 50
state_updater: cloud
battery.battery_level: 101
sub_entities: battery-3.battery_level-1
friendly_name: ZDG300 mop robot Mopping Machine
supported_features: 4344
```

</p>
</details>
<details><summary>cleaning</summary>
<p>

```
fan_speed_list: Dry, Basic, Strong
battery_level: 101
battery_icon: mdi:battery
fan_speed: Basic
model: kxf321.mop.mo001
lan_ip: 192.168.1.141
mac_address: 44:23:7C:FE:49:0C
entity_class: MiotVacuumEntity
home_room: Чайковского Прихожая
miot_type: urn:miot-spec-v2:device:mopping-machine:0000A064:kxf321-mo001:1
mopping_machine.status: 6
mopping_machine.mode: 50
state_updater: cloud
battery.battery_level: 101
sub_entities: battery-3.battery_level-1
friendly_name: ZDG300 mop robot Mopping Machine
supported_features: 4344
```

</p>
</details>
<details><summary>paused</summary>
<p>

```
fan_speed_list: Dry, Basic, Strong
battery_level: 101
battery_icon: mdi:battery
fan_speed: Dry
model: kxf321.mop.mo001
lan_ip: 192.168.1.141
mac_address: 44:23:7C:FE:49:0C
entity_class: MiotVacuumEntity
home_room: Чайковского Прихожая
miot_type: urn:miot-spec-v2:device:mopping-machine:0000A064:kxf321-mo001:1
mopping_machine.status: 4
mopping_machine.mode: 0
state_updater: cloud
battery.battery_level: 101
sub_entities: battery-3.battery_level-1
miot_action_result: 
did: '312285641'
miid: 0
siid: 2
aiid: 2
code: 0
exe_time: 0
withLatency: 0

friendly_name: ZDG300 mop robot Mopping Machine
supported_features: 4344
```

</p>
</details>

Commands that work via Developer Tools - Services:
 - vacuum: Stop 
 - vacuum: Return to base
 - vacuum: Set fan speed - Dry, Basic, Strong
 - vacuum: Pause
  
 No response and errors in log:
  - vacuum: Turn off
  - vacuum: Turn on

Notification is shown and errors in log appear:
 - Vacuum: Clean spot
 - Vacuum: Start/Pause

<details><summary>Vacuum: Clean spot logs:</summary>
<p>

```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/xiaomi_miot/vacuum.py:204
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 9:44:06 AM (1 occurrences)
Last logged: 9:44:06 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 228, in async_clean_spot
    await self.hass.async_add_executor_job(partial(self.clean_spot, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 204, in clean_spot
    raise NotImplementedError()
NotImplementedError




Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/xiaomi_miot/vacuum.py:204
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:44:06 AM (1 occurrences)
Last logged: 9:44:06 AM

[1641221280] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 228, in async_clean_spot
    await self.hass.async_add_executor_job(partial(self.clean_spot, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 204, in clean_spot
    raise NotImplementedError()
NotImplementedError
```

</p>
</details>

<details><summary>Vacuum: Start/Pause logs:</summary>
<p>

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/service.py:694
First occurred: 9:42:44 AM (1 occurrences)
Last logged: 9:42:44 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'MiotVacuumEntity' object has no attribute 'async_start_pause'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 694, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'MiotVacuumEntity' object has no attribute 'async_start_pause'




Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/service.py:694
First occurred: 9:42:44 AM (1 occurrences)
Last logged: 9:42:44 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'MiotVacuumEntity' object has no attribute 'async_start_pause'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 694, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
AttributeError: 'MiotVacuumEntity' object has no attribute 'async_start_pause'
```

</p>
</details>

**Xiaomi Miot Auto 0.5.1
HACS 1.19.3
Home Assistant 2021.12.10**

Could you please take a look at this issue?

**Comment by blakadder** [comment]
Try changing the [line](https://github.com/al-one/hass-xiaomi-miot/blob/495c43b5e61d1e9117a903e6a6cd485628d4e760/custom_components/xiaomi_miot/vacuum.py#L87) 

to

`        self._act_start = miot_service.get_action('start_sweep', 'start_mop')`

**Comment by PWSteal** [comment]
> Try changing the [line](https://github.com/al-one/hass-xiaomi-miot/blob/495c43b5e61d1e9117a903e6a6cd485628d4e760/custom_components/xiaomi_miot/vacuum.py#L87)
> 
> to
> 
> ` self._act_start = miot_service.get_action('start_sweep', 'start_mop')`

This' worked, thank you! Would you please open the pull request? I'm new to this stuff
