### ISSUE TITLE
xiaomi.tv.rmh1：media_player 播放暂停按钮不生效；朗读文本报错

### ISSUE THREAD

**Issue by axelburks** [al-one/hass-xiaomi-miot#418]
[xiaomi.tv.rmh1](https://home.miot-spec.com/s/xiaomi.tv.rmh1)
制造商：xiaomi
固件：4.2.4_257

<img width="402" alt="截屏2022-01-31 下午11 50 35" src="https://user-images.githubusercontent.com/11376445/151826559-8df81208-c5db-48c4-be3d-1bf9b0152771.png">

播放暂停按钮不生效，无任何响应。
朗读文本报错，如下
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/xiaomi_miot/media_player.py:534
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:49:24 (1 occurrences)
Last logged: 23:49:24

[2868515024] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/tts/__init__.py", line 200, in async_say_handle
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/media_player/__init__.py", line 718, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.homeassistant/custom_components/xiaomi_miot/media_player.py", line 499, in play_media
    rdt = self.request_mitv_api('controller', params=pms)
  File "/home/pi/.homeassistant/custom_components/xiaomi_miot/media_player.py", line 534, in request_mitv_api
    rdt = json.loads(req.content or '{}') or {}
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by al-one** [comment]
> 播放暂停按钮不生效，无任何响应。

根据图片显示，电视当前处在桌面，无法使用播放/暂停。你在电视播放视频的时候再点击该按钮。

----

> 朗读文本报错

更新到master后再试。
