### ISSUE TITLE
lumi.ctrl_neutral2.v1 无法更新开关状态

### ISSUE THREAD

**Issue by befantasy** [al-one/hass-xiaomi-miot#502]
近几个版本，原来工作正常的aqara双键单火线开关lumi.ctrl_neutral2.v1无法显示状态了。可以在HA控制开关通断，但是如果手动按压实体开关，状态无法同步至HA。同款的单键开关lumi.ctrl_neutral1.v1是正常的。

**Comment by al-one** [comment]
请提供开发者工具中的[实体状态及属性](https://my.home-assistant.io/redirect/developer_states)，并检查有无相关[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by befantasy** [comment]
model: lumi.ctrl_neutral2.v1
lan_ip: 
mac_address: lumi.158d0003a24dcb
entity_class: MiotSwitchEntity
home_room: 郑州 客厅
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-ctrl-neutral2-v1:1
switch.on.error: -704002000 Unknown
switch.name.error: -704002000 Unknown
switch.mode.error: -704002000 Unknown
state_updater: cloud
device_class: switch
friendly_name: 客厅开关 Left Switch Service
supported_features: 0
---------------------------------------------------------
model: lumi.ctrl_neutral2.v1
lan_ip: 
mac_address: lumi.158d0003a24dcb
entity_class: MiotSwitchEntity
home_room: 郑州 客厅
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-ctrl-neutral2-v1:1
switch-3.on.error: -704002000 Unknown
switch-3.name.error: -704002000 Unknown
switch-3.mode.error: -704002000 Unknown
state_updater: cloud
device_class: switch
friendly_name: 客厅开关 Right Switch Service
supported_features: 0
-----------------------------------------------------------
以上是异常的双键开关

**Comment by befantasy** [comment]
model: lumi.ctrl_neutral1.v1
lan_ip: 
mac_address: lumi.158d000340bc6c
entity_class: MiotSwitchEntity
home_room: 郑州 卧室
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-ctrl-neutral1-v1:1
switch.on: false
switch.mode.error: -704040898
state_updater: cloud
device_class: switch
friendly_name: 次卧吸顶灯 Switch
supported_features: 0
--------------------------------------------------
以上是正常的单键开关。

**Comment by befantasy** [comment]
我记得是从2022.3.x的某个版本开始出问题的，另外一个插件也有完全一样的问题https://github.com/ha0y/xiaomi_miot_raw

所以估计是HA哪里做了什么改动。

我印象中隐约记得2022.3.x的某个版本好像修改了entity的默认状态属性，新增了一个unknown还是unavailable什么的。。。
但是刚才去官网上没找到在哪里看历史版本的详细release note。
我再去github的release note翻翻吧。

**Comment by befantasy** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:745
First occurred: 10:38:24 (1 occurrences)
Last logged: 10:38:24

Update of switch.lumi_ctrl_neutral2_v1_4dcb_left_switch_service is taking over 10 seconds

**Comment by befantasy** [comment]
> 我记得是从2022.3.x的某个版本开始出问题的，另外一个插件也有完全一样的问题https://github.com/ha0y/xiaomi_miot_raw
> 
> 所以估计是HA哪里做了什么改动。
> 
> 我印象中隐约记得2022.3.x的某个版本好像修改了entity的默认状态属性，新增了一个unknown还是unavailable什么的。。。 但是刚才去官网上没找到在哪里看历史版本的详细release note。 我再去github的release note翻翻吧。

找到了，是2022.2里面的，但是好像跟现在的问题也没啥关联。。。是我记错了。

Binary Sensors
Previously, binary_sensor entities could have the state on, off, and in case the device was unreachable: unavailable.

However, compared to other entities, it wasn’t able to have the unknown state, which has been added this release.

So, a binary_sensor entity can now have the on, off, unavailable, or unknown state.

You might need to adapt your automations or scripts to take this new unknown state into account.

**Comment by befantasy** [comment]
此错误来自自定义集成。

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:444
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:43:05 (1 occurrences)
Last logged: 10:43:05

Update for switch.lumi_ctrl_neutral2_v1_d2b5_left_switch_service fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 750, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/switch.py", line 93, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1234, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 47, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 62, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 71, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 157, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 444, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

**Comment by al-one** [comment]
> switch.on.error: `-704002000 Unknown`

该报错由小米云端返回，插件对此无能为力。你可以尝试在米家APP重新绑定该设备。

**Comment by befantasy** [comment]
这些设备在米家app里面完全正常，可以即时反馈开关状态。
现在是所有的同款单键开关在HA里都正常。
所有的同款双键开关在HA里都不正常。
但是无论双键还是单键开关，在米家app中都正常。

**Comment by al-one** [comment]
```yaml
model: lumi.ctrl_neutral2.v1
lan_ip: 
mac_address: lumi.158d00045ea2a5
entity_class: MiotSwitchEntity
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-ctrl-neutral2-v1:1
switch.on: true
switch.name: 墙壁开关
switch.mode: 0
state_updater: cloud
device_class: switch
icon: hass:lightbulb
supported_features: 0
```
我有同款开关正常接入，使用的是多模网关。如果你在米家重新绑定设备后仍然报`-704002000 Unknown`错误，可以考虑更换网关。

**Comment by befantasy** [comment]
感谢解答。
另外还有个不解。
我单间开关可以反馈正确的状态，但那个switch.mode也是有error。这个switch.mode是表示什么呢？

model: lumi.ctrl_neutral1.v1
lan_ip: 
mac_address: lumi.158d000340bc6c
entity_class: MiotSwitchEntity
home_room: 郑州 卧室
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-ctrl-neutral1-v1:1
switch.on: true
### switch.mode.error: -704040898
state_updater: cloud
device_class: switch
friendly_name: 次卧吸顶灯 Switch
supported_features: 0

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/lumi.ctrl_neutral1.v1
```json
{
    "iid":2,
    "type":"urn:miot-spec-v2:property:mode:00000008:lumi-ctrl-neutral1-v1:1",
    "description":"Mode",
    "format":"uint8",
    "access":[
        "read",
        "write",
        "notify"
    ],
    "unit":"none",
    "value-list":[
        {
            "value":0,
            "description":"Wired And Wireless"
        },
        {
            "value":1,
            "description":"Wireless"
        }
    ]
}
```

**Comment by al-one** [comment]
尝试添加以下自定义属性：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    lumi.ctrl_neutral1.v1:
      exclude_miot_properties: mode
    lumi.ctrl_neutral2.v1:
      exclude_miot_properties: mode,name
```

**Comment by befantasy** [comment]
> 尝试添加以下自定义属性：
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     lumi.ctrl_neutral1.v1:
>       exclude_miot_properties: mode
>     lumi.ctrl_neutral2.v1:
>       exclude_miot_properties: mode,name
> ```

厉害！恢复正常了！
这是什么意思？是属性名和什么东西冲突了？

**Comment by al-one** [comment]
排除掉不重要的属性。
