### ISSUE TITLE
ValueError: entity_category must be a valid EntityCategory instance in 2022.4

### ISSUE THREAD

**Issue by h3nrytan** [al-one/hass-xiaomi-miot#504]
This error pop up after updating to latest 2022.4.0

```
Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:529
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 1:12:40 pm (1 occurrences)
Last logged: 1:12:40 pm

Error adding entities for domain switch with platform xiaomi_miot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by al-one** [comment]
Try master branch.

**Comment by h3nrytan** [comment]
all good

**Comment by Mick51** [comment]
No fixed yesterday for me....... 🤔🤔🤔

**Comment by garyo** [comment]
I'm still getting this with latest 2022.7.7, for a ble_monitor device. What does it mean?
```
2022-08-03 07:56:44 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 536, in _async_add_entity
entry = entity_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 347, in async_get_or_create
return self.async_update_entity(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 643, in async_update_entity
return self._async_update_entity(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 546, in _async_update_entity
raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by al-one** [comment]
@garyo `ble_monitor` is not this component.
