### ISSUE TITLE
添加完账号信息同步设备成功但没有实体显示,报错日志如下,ha是docker安装的

### ISSUE THREAD

**Issue by zeuschocolate** [al-one/hass-xiaomi-miot#530]
Logger: homeassistant.components.vacuum
Source: util/file.py:70
Integration: 扫地机 (documentation, issues)
First occurred: 20:43:50 (1 occurrences)
Last logged: 20:43:50

```python
Error while setting up xiaomi_miot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/file.py", line 67, in write_utf8_file
    os.replace(tmp_filename, filename)
OSError: [Errno 22] Invalid argument: '/config/.storage/xiaomi_miot/tmp8vy5stuu' -> '/config/.storage/xiaomi_miot/urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019:1.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 52, in async_setup_entry
    await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 489, in async_setup_config_entry
    await async_setup_platform(hass, c, async_add_entities)
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 62, in async_setup_platform
    spec = await MiotSpec.async_from_type(hass, miot)
  File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 299, in async_from_type
    await store.async_save(dat)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 194, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 276, in _async_handle_write_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 287, in _write_data
    json_util.save_json(
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in save_json
    write_utf8_file(filename, json_data, private)
  File "/usr/src/homeassistant/homeassistant/util/file.py", line 70, in write_utf8_file
    raise WriteError(error) from error
homeassistant.util.file.WriteError: [Errno 22] Invalid argument: '/config/.storage/xiaomi_miot/tmp8vy5stuu' -> '/config/.storage/xiaomi_miot/urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019:1.json'
```

**Comment by zeuschocolate** [comment]
所有的设备报错日志都是类似这个的,一共大概20多个设备

**Comment by al-one** [comment]
请尝试删除`.storage/xiaomi_miot/`目录。

**Comment by zeuschocolate** [comment]
谢谢,已解决,并不是删除目录解决的,是因为原本的docker映射目录是放在一块ntfs文件格式的机械硬盘上的,我把映射目录改到宿主机本身的ext4文件格式的固态硬盘后就没有报错,一切正常了
