### ISSUE TITLE
chuangmi.camera.038a02 无法查看监控回放

### ISSUE THREAD

**Issue by TigerBeanst** [al-one/hass-xiaomi-miot#540]
![image](https://user-images.githubusercontent.com/3889846/164992061-71ab0005-484d-494e-8125-76f11802ae06.png)
目前是可以看到回放中的一帧截图，但是一旦想要看这段视频：
![image](https://user-images.githubusercontent.com/3889846/164992093-495c9044-168d-48e4-a60e-93e14e2db2e1.png)

审查元素中请求此地址但无法到达：
![image](https://user-images.githubusercontent.com/3889846/164992131-307ef6e6-c8a6-4542-af69-f9b392651d65.png)

日志：
```
Logger: aiohttp.server
Source: components/stream/hls.py:104
First occurred: 02:54:51 (2 occurrences)
Last logged: 02:57:24

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/stream/core.py", line 354, in get
    return await self.handle(request, stream, sequence, part_num)
  File "/usr/src/homeassistant/homeassistant/components/stream/hls.py", line 127, in handle
    body=self.render(track).encode("utf-8"),
  File "/usr/src/homeassistant/homeassistant/components/stream/hls.py", line 104, in render
    if not (segment := track.get_segment(track.sequences[-2])):
IndexError: list index out of range
```

```
Logger: libav.mov,mp4,m4a,3gp,3g2,mj2
Source: components/stream/worker.py:357
First occurred: 02:54:39 (14 occurrences)
Last logged: 02:58:28

Found duplicated MOOV Atom. Skipped it
stream 0, offset 0x937: partial file
```

```
Logger: homeassistant.components.stream.stream.camera.chuangmi_038a02_6f64_camera_control
Source: components/stream/__init__.py:347
Integration: Stream (documentation, issues)
First occurred: 02:54:39 (7 occurrences)
Last logged: 02:58:28

Error from stream worker: Error demuxing stream: [Errno 1094995529] Invalid data found when processing input: 'https://business.smartcamera.api.io.mi.com/common/app/m3u8?data=脱敏'; last error log: [mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0x937: partial file
```

**Comment by al-one** [comment]
> last error log: [mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0x937: partial file

这是HA内置ffmpeg报出的错误信息，如果你拿日志中的hls地址到一些播放器播放也是无法播放。问题未知，暂无法解决。
