### ISSUE TITLE
0.6.3版本下，light.yeelink_lamp22无法工作

### ISSUE THREAD

**Issue by befantasy** [al-one/hass-xiaomi-miot#581]
version: 0.6.3
之前一直正常，刚刚刚更新后，始终无法工作。查看日志如下。

2022-05-10 18:31:56 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.yeelink_lamp22_eb1f
2022-05-10 18:31:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-05-10 18:31:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.yeelink_lamp22_eb1f
2022-05-10 18:32:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.yeelink_lamp22_eb1f

![image](https://user-images.githubusercontent.com/31535803/167611891-4ddcfa55-5b95-43a2-bfb2-d11860754e2c.png)

**Comment by al-one** [comment]
你应该是升级到刚才的v0.6.3版本，该问题已在v0.6.4中修复，请再次更新。

**Comment by befantasy** [comment]
是的是的，我刚才看github release 是0.6.4，就复制过来了。
刚才去HA里又一看，是0.6.3，刚刚把issue编辑了一下。就看到您的回复了。

**Comment by befantasy** [comment]
更新到0.6.4，问题解决。
