### ISSUE TITLE
空調紅外線遙控接入

### ISSUE THREAD

**Issue by AaronFUFU** [al-one/hass-xiaomi-miot#624]
已经成功将米家上面的空调接入HA，但这边有个问题是在调模式时，冷气不会开启，须透过按开关的按钮才会打开

**Comment by AaronFUFU** [comment]
Hi @al-one  
感谢您的回覆，出现以下错误
![截圖 2022-05-31 下午4 50 21](https://user-images.githubusercontent.com/76577625/171133772-2356e316-4480-4f8c-ac99-5e336b1b8b65.png)

**Comment by al-one** [comment]
点开复制日志详情。

**Comment by AaronFUFU** [comment]
自行安裝整合產生錯誤。

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:563
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 16:49:19 (2 occurrences)
Last logged: 16:58:19

Update for select.miir_ir02_2592_ir_aircondition_control fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1345, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 57, in get_properties_for_mapping
    rls = self.get_props(pms)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 72, in get_props
    return self.request_miot_spec('prop/get', params)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 81, in request_miot_spec
    rdt = self.request_miot_api('miotspec/' + api, {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 172, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 563, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

**Comment by AaronFUFU** [comment]
Hi @al-one  另外发现一个问题，红外线空调转到homekit做使用时，第一次新增设备或是重启HA，会导致homekit里的空调法控制无回应，需要在HA按一次空调制冷或是自动，这时homekit才能正常操作。

**Comment by al-one** [comment]
> 另外发现一个问题，红外线空调转到homekit做使用时，第一次新增设备或是重启HA，会导致homekit里的空调法控制无回应，需要在HA按一次空调制冷或是自动，这时homekit才能正常操作。

由于红外空调没有状态反馈，HA重启后插件无法得知空调当前运行模式，此时空调实体的状态外`unknown`，但是homekit并不支持`unknown`，在HA控制后，插件会临时记录当前模式，但是重启HA后会丢失。刚才的提交(https://github.com/al-one/hass-xiaomi-miot/commit/a9fc16429f74c44d5165d7f1eebcd5aa0d35e81b)中优化为永久记录最后的模式，因此只需在接入设备后在HA操作一次，后续重启HA都会读取并恢复成最后的状态。
需要注意的是，此功能需要较新版本的HA，且HA默认每15分钟存储一次状态，因此如果操作后15分钟内重启HA，可能会恢复成操作前的状态。

**Comment by al-one** [comment]
@AaronFUFU 需要注意的是，HA默认每15分钟存储一次状态，因此如果操作后15分钟内重启HA，可能会恢复成操作前的状态。
