### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by master-kenobi** [al-one/hass-xiaomi-miot#630]
I am using Home Assistant Core 2022.5.5 and trying to install [v0.6.7 - 2022-05-30] using Method 2: Manually installation via Samba / SFTP.

When I go to Configuration > Devices & Services > Add Integration, I cannot find Xiaomi Miot Auto.

![2022-06-01_225021](https://user-images.githubusercontent.com/19662311/171436116-1ef640d8-ebe8-4f0a-9557-675007e3ed52.png)

So I added this to my configuration...

```
xiaomi_miot:
  username: !secret xiaomi_username
  password: !secret xiaomi_password
  server_country: cn
  http_timeout: 300
```

After I restart HA, it shows this error in the log…

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:563
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:47:21 PM (1 occurrences)
Last logged: 10:47:21 PM

Error during setup of component xiaomi_miot
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 214, in async_setup
    hass.data[DOMAIN]['devices_by_mac'] = await mic.async_get_devices_by_key('mac') or {}
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 278, in async_get_devices_by_key
    dvs = await self.async_get_devices(renew=renew) or []
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 247, in async_get_devices
    dvs = await self.hass.async_add_executor_job(self.get_device_list)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 204, in get_device_list
    rdt = self.request_miot_api('home/device_list', {
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 172, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 563, in request_rc4_api
    response = self.session.post(url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=60)
```

Please help.

**Comment by master-kenobi** [comment]
Never mind. I managed to find the "Xiaomi Miot Auto" in the integration after I cleared my browser cache.
