### ISSUE TITLE
babai.switch.bb101s 自动模式下会掉线

### ISSUE THREAD

**Issue by harrywenjie** [al-one/hass-xiaomi-miot#642]
[babai.switch.bb103s](https://home.miot-spec.com/s/babai.switch.bb103s)
三键开关，自动模式下会"掉线"，然后无法控制。
~~把它加到剔除列表就正常了，否则老是掉线。~~
在路由里看到设备wifi是在线的，但是会从米家以及HA里掉线。
HA里的提示说，“本地模式 token access失败”
因为是安在墙里的永久开关，“掉线”后唯一的办法是重启路由，或者在路由里用deauth强行让它掉一次wifi

***

昨天把它加到剔除列表，今早依然是掉线的，我怀疑是我自己新加了一个半夜自动重启cable modem的代码造成的(短暂断外网不断局域网)。
先前的日志在HA重启后清除了。今天我会注意保留一下日志。

**Comment by al-one** [comment]
请提供具体的报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by harrywenjie** [comment]
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/8882615/home-assistant.log)
附昨晚4：05分重启之后到今天早上10: 50大约6个半小时的完整log，10点43分我在插件设置里更新过小米设备列表，并重新把问题设备添加回去。

观察到其中这一段关于此开关babai.switch.bb103s的报错
另外，我的log中似乎有大量的超时问题。我家ping "api.io.mi.com" 大约330ms，能不能修改timeout的时间？

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 514, in start
resp, reset = await task
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
await prepare_meth(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
return await self._sendfile(request, fobj, offset, count)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
await loop.sendfile(transport, fobj, offset, count)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
return await self._sendfile_fallback(transport, file,
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
await proto.restore()
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
self._transport.resume_reading()
File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
2022-06-11 10:43:59 ERROR (MainThread) [custom_components.xiaomi_miot.switch] 顶灯(babai.switch.bb103s): Got MiioException while fetching the state: Unable to discover the device 192.168.1.210, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.eco': {'siid': 2, 'piid': 2}, 'switch.off_delay': {'siid': 2, 'piid': 3}, 'switch.mode': {'siid': 2, 'piid': 4}}, max_properties: 7/4
2022-06-11 10:44:20 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
```

**Comment by harrywenjie** [comment]
本日没有再发现掉线，应该不是插件的问题。这个问题我关闭了。
