### ISSUE TITLE
From 06/26/2022 the integration does not load with an error

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#674]
Home Assistant core-2022.6.7
Home Assistant Supervisor 2022.05.3

There are problems with integration. Which socket are we talking about ? How can I check ? What is the problem? Please help.
From 06/26/2022 the integration does not load with an error :

This error appear in custom integration.

Logger: homeassistant.setup
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:421
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:41:53 (1 occurrences)
Last logged: 10:41:53

Error during setup of component xiaomi_miot
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 456, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.9/ssl.py", line 1123, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.9/ssl.py", line 1088, in _check_connected
    self.getpeername()
OSError: [Errno 107] Socket not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 456, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.9/ssl.py", line 1123, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.9/ssl.py", line 1088, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Socket not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 211, in async_setup
    if not await mic.async_login():
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 322, in async_login
    ret = await self.hass.async_add_executor_job(self._login_request, captcha)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 344, in _login_request
    response = self._login_step3(location)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 421, in _login_step3
    response = self.session.get(location)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Socket not connected'))

**Comment by VikeDragon** [comment]
The problem went away after a few hours and after a complete reconnection of the entire integration with a re-download. What was that?
Api malfunction?
