### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by Kiryuumaru** [al-one/hass-xiaomi-miot#725]
I dont know what went wrong:

------------------------ LOGS----------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 467, in connect
    _match_hostname(cert, self.assert_hostname or server_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 540, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
    raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
urllib3.util.ssl_match_hostname.CertificateError: hostname 'tw.business.smartcamera.api.io.mi.com' doesn't match 'home.mi.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tw.business.smartcamera.api.io.mi.com', port=443): Max retries exceeded with url: /common/app/get/eventlist?xxx (Caused by SSLError(CertificateError("hostname 'tw.business.smartcamera.api.io.mi.com' doesn't match 'home.mi.com'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/camera.py", line 295, in async_update
    rdt = await mic.async_request_api(api, rqd, method='GET', crypt=True) or {}
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 160, in async_request_api
    return await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 174, in request_miot_api
    rsp = self.request_rc4_api(api, params, method, **kwargs)
  File "/config/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 578, in request_rc4_api
    response = self.session.get(url, params=params, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tw.business.smartcamera.api.io.mi.com', port=443): Max retries exceeded with url: /common/app/get/eventlist?xxx (Caused by SSLError(CertificateError("hostname 'tw.business.smartcamera.api.io.mi.com' doesn't match 'home.mi.com'")))

**Comment by al-one** [comment]
Please contact MiHome customer service to update the ssl certificate.
