### ISSUE TITLE
登录账号时提示[Errno 2] No such file or directory: 'getprop'

### ISSUE THREAD

**Issue by win741852** [al-one/hass-xiaomi-miot#733]
用的是手机aidlux安装的HA，重装了两次都是报这个问题，求教何解

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/35ad2768b8e7f1481411e2b30534a98e88a630e5/custom_components/xiaomi_miot/config_flow.py#L119

建议修改你的本地文件中的代码为：
```python
    except (MiCloudException, MiCloudAccessDenied) as exc:
```
并重启HA后再试，然后观察[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by win741852** [comment]
> https://github.com/al-one/hass-xiaomi-miot/blob/35ad2768b8e7f1481411e2b30534a98e88a630e5/custom_components/xiaomi_miot/config_flow.py#L119
> 
> 建议修改你的本地文件中的代码为：
> 
> ```python
>     except (MiCloudException, MiCloudAccessDenied) as exc:
> ```
> 
> 并重启HA后再试，然后观察[日志](https://my.home-assistant.io/redirect/logs)。



现在改了以后开始提示 Unknown error occurred
看日志还是那个问题

2022-08-04 01:07:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/root/.homeassistant/custom_components/xiaomi_miot/config_flow.py", line 297, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/root/.homeassistant/custom_components/xiaomi_miot/config_flow.py", line 110, in check_xiaomi_account
    mic = await MiotCloud.from_token(hass, user_input, login=False)
  File "/root/.homeassistant/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 469, in from_token
    mic = MiotCloud(
  File "/root/.homeassistant/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 33, in __init__
    super().__init__(username, password)
  File "/opt/homeassistant/lib/python3.9/site-packages/micloud/micloud.py", line 38, in __init__
    timezone = datetime.datetime.now(tzlocal.get_localzone()).strftime('%z')
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 165, in _get_localzone
    tzname = _get_localzone_name(_root)
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 38, in _get_localzone_name
    subprocess.check_output(["getprop", "persist.sys.timezone"])
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'getprop'

**Comment by al-one** [comment]
请更新至master分支后再试。

**Comment by win741852** [comment]
> 

已经删掉了原版，安装了master，改好配置文件后重启了，看到报错好像跟上面一样么


-08-04 12:26:52 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/root/.homeassistant/custom_components/xiaomi_miot/config_flow.py", line 297, in async_step_cloud
    await check_xiaomi_account(self.hass, user_input, errors, renew_devices=True)
  File "/root/.homeassistant/custom_components/xiaomi_miot/config_flow.py", line 110, in check_xiaomi_account
    mic = await MiotCloud.from_token(hass, user_input, login=False)
  File "/root/.homeassistant/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 469, in from_token
    mic = MiotCloud(
  File "/root/.homeassistant/custom_components/xiaomi_miot/core/xiaomi_cloud.py", line 33, in __init__
    super().__init__(username, password)
  File "/opt/homeassistant/lib/python3.9/site-packages/micloud/micloud.py", line 38, in __init__
    timezone = datetime.datetime.now(tzlocal.get_localzone()).strftime('%z')
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 203, in get_localzone
    _cache_tz = _get_localzone()
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 165, in _get_localzone
    tzname = _get_localzone_name(_root)
  File "/opt/homeassistant/lib/python3.9/site-packages/tzlocal/unix.py", line 38, in _get_localzone_name
    subprocess.check_output(["getprop", "persist.sys.timezone"])
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python-3.9.10/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'getprop'

**Comment by al-one** [comment]
从日志看，你的代码不是最新的master分支，请重新下载。

**Comment by win741852** [comment]
> 从日志看，你的代码不是最新的master分支，请重新下载。

不好意思 费了半天劲终于重新下好了



2022-08-04 13:59:47 ERROR (MainThread) [custom_components.xiaomi_miot.config_flow] Setup xiaomi cloud for user: ********* failed: Login to xiaomi error: &&&START&&&{"result":"error","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","description":"登录验证失败","location":"","securityStatus":0,"pwd":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","desc":"登录验证失败"}

**Comment by programlive** [comment]
我也遇到这个问题了，应该怎么解决呢？
想在github下载复制安装，结果在集成那提示我不能在UI安装.....

**Comment by programlive** [comment]
貌似解决了，在hasc安装[hass-xiaomi-miot]时，选择版本为：”master“安装，重启就没这个错误了
