### ISSUE TITLE
zhimi.heater.na1 climate entity problems

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#75]
for model [`zhimi.heater.na1`](https://gist.github.com/blakadder/3c5a2474487cef7dcda94b9c8308f1f8) 

In Home Assistant when switching the climate entity to mode "Auto" is reverts to empty and the entity state in HA state machine shows as being in mode `fan not swing` or `fan swing`. If a device is recognised as a heater it should have "heat" and "off" modes.

![image](https://user-images.githubusercontent.com/5904370/117278544-2625bc00-ae61-11eb-9105-b82ed66f9fa4.png)
![image](https://user-images.githubusercontent.com/5904370/117278598-30e05100-ae61-11eb-9d24-311a6c449f82.png)

For this specific model the property `urn:miot-spec-v2:property:mode:00000008:zhimi-na1:1` should be reported as swing mode "SWING_x" instead of presets.

There are also errors in HA logs:

```
2021-05-06 11:50:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.bathroom_heater_physical_controls_locked fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1154, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/switch.py", line 138, in update
    super().update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1188, in update
    super().update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1139, in update
    attrs = self._parent.device_state_attributes or {}
  File "/config/custom_components/xiaomi_miot/__init__.py", line 497, in device_state_attributes
    ext = self.state_attributes or {}
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 266, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/xiaomi_miot/climate.py", line 386, in preset_mode
    acm = -1 if acm is None else int(acm or 0)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
2021-05-06 11:50:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.bathroom_heater fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/climate.py", line 173, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 792, in async_update
    self._update_sub_entities(
  File "/config/custom_components/xiaomi_miot/__init__.py", line 988, in _update_sub_entities
    self._subs[fnm].update()
  File "/config/custom_components/xiaomi_miot/switch.py", line 138, in update
    super().update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1188, in update
    super().update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1139, in update
    attrs = self._parent.device_state_attributes or {}
  File "/config/custom_components/xiaomi_miot/__init__.py", line 497, in device_state_attributes
    ext = self.state_attributes or {}
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 266, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/xiaomi_miot/climate.py", line 386, in preset_mode
    acm = -1 if acm is None else int(acm or 0)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by blakadder** [comment]
you're correct, its violating miot spec wherever it can.

```
271440105: false
hvac_modes: heat, off
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes: High, Low
swing_modes: Off, Horizontal
current_temperature: -1
fan_mode: High
swing_mode: Off
model: zhimi.heater.na1
firmware_version: 2.1.8
hardware_version: esp32
heater_fault: No faults
heater_switch_status: false
heater_speed: 1
heater_horizontal_swing: 0
indicator__brightness: 0
switch_switch_status: false
switch_2_switch_status: false
state_value: false
friendly_name: zhimi
supported_features: 40
```

**Comment by blakadder** [comment]
sorry i previously pasted the heater entity supported attributes from the wrong entity
