### ISSUE TITLE
v0.6.12-2022-09-20 更新后无法调用扫地机服务

### ISSUE THREAD

**Issue by atticus-lv** [al-one/hass-xiaomi-miot#804]
![image](https://user-images.githubusercontent.com/64118610/191714771-9ed5aeb6-32ef-4c13-aeb0-6a6e37bf68ef.png)
![image](https://user-images.githubusercontent.com/64118610/191715689-383c90f3-469e-4849-a60e-2603f4d0d4bc.png)

删除后再重新添加集成也不行,所有实体状态都无法访问

**Comment by atticus-lv** [comment]
回退8.29版本可正常使用

**Comment by atticus-lv** [comment]
model
roborock.vacuum.a29

**Comment by al-one** [comment]
[日志](https://my.home-assistant.io/redirect/logs)

**Comment by atticus-lv** [comment]
看了下，应该是这个
Logger: homeassistant.components.vacuum
Source: custom_components/xiaomi_miot/core/miio2miot.py:99
Integration: 扫地机 ([documentation](https://www.home-assistant.io/integrations/vacuum), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
First occurred: 19:14:52 (1 occurrences)
Last logged: 19:14:52

```
xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 274, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/vacuum.py", line 133, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1306, in async_update
    results = await self._miio2miot.async_get_miot_props(self.miot_device, local_mapping)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 113, in async_get_miot_props
    return await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 121, in get_miot_props
    if dic := self.get_miio_props(device):
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 99, in get_miio_props
    dic[k] = vls[i]
KeyError: 0
```

**Comment by al-one** [comment]
已在最新的提交中修复，请更新至master分支后尝试。

**Comment by atticus-lv** [comment]
确认修复，可以正常调服务
