### ISSUE TITLE
石头G10S无法添加

### ISSUE THREAD

**Issue by wdmywm3** [al-one/hass-xiaomi-miot#809]
不知道是不是我的石头G10S更新到了最新固件（4.3.5_1416）的缘故
auto里面所有实体都变为不可用，重新添加也不行，删除设备之后重新添加，可以在设备列表里找到，但实际上无法添加进来
扫地机相关的日志找到这一部分，不知是否能够提供信息：

> Logger: homeassistant.components.vacuum
> Source: custom_components/xiaomi_miot/core/miio2miot.py:99
> Integration: 扫地机 ([documentation](https://www.home-assistant.io/integrations/vacuum), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
> First occurred: 13:04:17 (19 occurrences)
> Last logged: 15:22:48
> 
> xiaomi_miot: Error on device update!
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
>     await task
>   File "/config/custom_components/xiaomi_miot/vacuum.py", line 274, in async_update
>     await super().async_update()
>   File "/config/custom_components/xiaomi_miot/vacuum.py", line 133, in async_update
>     await super().async_update()
>   File "/config/custom_components/xiaomi_miot/__init__.py", line 1306, in async_update
>     results = await self._miio2miot.async_get_miot_props(self.miot_device, local_mapping)
>   File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 113, in async_get_miot_props
>     return await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 121, in get_miot_props
>     if dic := self.get_miio_props(device):
>   File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 99, in get_miio_props
>     dic[k] = vls[i]
> KeyError: 0

**Comment by al-one** [comment]
- #804

master分支已修复。
