### ISSUE TITLE
邦先生晾衣机 mrbond.airer.m33a Homekit异常

### ISSUE THREAD

**Issue by littlehi** [al-one/hass-xiaomi-miot#870]
邦先生晾衣机 mrbond.airer.m33a , 
1.将灯实体添加到homekit之后，所有homekit 设备无响应
2.晾衣架在homekit中无法操作

**Comment by al-one** [comment]
HA中是否正常？并提供操作后的设备相关[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by littlehi** [comment]
HA中操作都正常。

第2个问题，homekit 操作晾衣机升降 无效。
[日志](https://my.home-assistant.io/redirect/logs) 中无相关设备日志，从 HA操作日志中可以看到通过Homekit 操作 显示“HomeKit  send command set_cover_position to 100 for 晾衣机 Airer”

而通过 HA 操作，显示 “晾衣机 Airer  正在关闭 由服务触发 cover.close_cover”

**Comment by littlehi** [comment]
第一个问题：
一旦把 light 实体加入homekit，所有homekit 设备无响应，我打开了homekit debug 等级日志：


2022-11-09 19:35:58.624 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state light.mrbond_m33a_784a_light=off; min_mireds=10000, max_mireds=333, supported_color_modes=['brightness', 'color_temp', 'onoff'], model=mrbond.airer.m33a, lan_ip=192.168.31.151, mac_address=xxxxxx, entity_class=MiotLightEntity, miot_type=urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1, light.on=False, light.brightness.error=-4004 Other internal errors, light.color_temperature.error=-4004 Other internal errors, light.flex_switch.error=-4004 Other internal errors, start_time_hour-4-1.error=-4004 Other internal errors, time_quantum_set.start_time_min.error=-4004 Other internal errors, time_quantum_set.end_time_hour.error=-4004 Other internal errors, time_quantum_set.end_time_min.error=-4004 Other internal errors, headlight_switch-4-5.error=-4004 Other internal errors, airer.fault.error=-4004 Other internal errors, airer.motor_control.error=-4004 Other internal errors, airer.current_position.error=-4004 Other internal errors, airer.status.error=-4004 Other internal errors, airer-2.current_position.error=-4004 Other internal errors, airer-2.current_position-11.error=-4004 Other internal errors, airer.on.error=-4004 Other internal errors, airer.target_position.error=-4004 Other internal errors, state_updater=lan, friendly_name=晾衣机 Light, supported_features=3 @ 2022-11-09T19:35:55.629747+08:00>




2022-11-09 19:35:58.528 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state cover.mrbond_m33a_784a_airer=unknown; model=mrbond.airer.m33a, lan_ip=192.168.31.151, mac_address=xxxxx, entity_class=MiotCoverEntity, miot_type=urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1, airer.fault.error=-4004 Other internal errors, airer.motor_control.error=-4004 Other internal errors, airer.current_position.error=-4004 Other internal errors, airer.status.error=-4004 Other internal errors, airer-2.current_position.error=-4004 Other internal errors, airer-2.current_position-11.error=-4004 Other internal errors, airer.on.error=-4004 Other internal errors, airer.target_position.error=-4004 Other internal errors, start_time_hour-4-1.error=-4004 Other internal errors, time_quantum_set.start_time_min=0, time_quantum_set.end_time_hour.error=-4004 Other internal errors, time_quantum_set.end_time_min.error=-4004 Other internal errors, headlight_switch-4-5.error=-4004 Other internal errors, light.on.error=-4004 Other internal errors, light.brightness.error=-4004 Other internal errors, light.color_temperature.error=-4004 Other internal errors, light.flex_switch.error=-4004 Other internal errors, state_updater=lan, friendly_name=晾衣机 Airer, supported_features=15 @ 2022-11-09T19:35:50.435778+08:00>

**Comment by al-one** [comment]
请更新至master分支后再试。

**Comment by littlehi** [comment]
Homekit 上操作 晾衣机 升降还是无效，并且状态没办法同步到 homekit上，HA上操作正常。

日志如下：

Logger: homeassistant.core
Source: custom_components/xiaomi_miot/cover.py:208 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 14:25:19 (1 occurrences) 
Last logged: 14:25:19

Error executing service: <ServiceCall cover.set_cover_position (c:01GHG3DQM14MG009QGJ8CY4B7A): entity_id=['cover.mrbond_m33a_784a_airer'], position=0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 370, in async_set_cover_position
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/cover.py", line 208, in set_cover_position
    if pos > cur:
TypeError: '>' not supported between instances of 'int' and 'NoneType'

**Comment by al-one** [comment]
已修复，再次更新后重试。

**Comment by littlehi** [comment]
还是有问题，
1.Homekit 上状态显示不正确，设备实际状态 上升到最高（打开状态） 也是显示 关闭 状态
2.Homekit 上可以操作 下降（关闭），但是无法操作 上升（打开）

我怀疑是一些设备状态没获取到

model: mrbond.airer.m33a
lan_ip: 192.168.31.151
mac_address: CC:B5:D1:6C:78:4A
entity_class: MiotCoverEntity
miot_type: urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1
airer.fault.error: -4004 Other internal errors
airer.motor_control.error: -4004 Other internal errors
airer.current_position.error: -4004 Other internal errors
airer.status.error: -4004 Other internal errors
airer-2.current_position.error: -4004 Other internal errors
airer-2.current_position-11.error: -4004 Other internal errors
airer.on.error: -4004 Other internal errors
airer.target_position.error: -4004 Other internal errors
start_time_hour-4-1.error: -4004 Other internal errors
time_quantum_set.start_time_min: 0
time_quantum_set.end_time_hour.error: -4004 Other internal errors
time_quantum_set.end_time_min.error: -4004 Other internal errors
headlight_switch-4-5.error: -4004 Other internal errors
light.on.error: -4004 Other internal errors
light.brightness.error: -4004 Other internal errors
light.color_temperature.error: -4004 Other internal errors
light.flex_switch.error: -4004 Other internal errors
state_updater: lan
airer.target_position: 100
airer.motor_control: 2
airer.status: 2
friendly_name: 晾衣机 Airer
supported_features: 15

**Comment by al-one** [comment]
`-4004 Other internal errors`该错误信息由设备返回，可以尝试云端接入。

**Comment by littlehi** [comment]
Light 实体也是 一样都是 4004，目前 light 实体放进Homekit 还是会导致整个Homekit 设备无响应。

**Comment by littlehi** [comment]
不过有一种可能是不是我设备wifi 强度较弱会导致整个4004 呢？

**Comment by al-one** [comment]
请提供下light实体的实体属性。

------

> 不过有一种可能是不是我设备wifi 强度较弱会导致整个4004 呢？

应该不是，目前发现很多的晾衣架/窗帘电机通过本地获取属性时会返回4004，猜测可能是米家提供的固件sdk有问题。

**Comment by littlehi** [comment]
min_mireds: 10000
max_mireds: 333
supported_color_modes: brightness, color_temp, onoff
model: mrbond.airer.m33a
lan_ip: 192.168.31.151
mac_address: CC:B5:D1:6C:78:4A
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1
light.on: false
light.brightness.error: -4004 Other internal errors
light.color_temperature.error: -4004 Other internal errors
light.flex_switch.error: -4004 Other internal errors
start_time_hour-4-1.error: -4004 Other internal errors
time_quantum_set.start_time_min.error: -4004 Other internal errors
time_quantum_set.end_time_hour.error: -4004 Other internal errors
time_quantum_set.end_time_min.error: -4004 Other internal errors
headlight_switch-4-5.error: -4004 Other internal errors
airer.fault.error: -4004 Other internal errors
airer.motor_control.error: -4004 Other internal errors
airer.current_position.error: -4004 Other internal errors
airer.status.error: -4004 Other internal errors
airer-2.current_position.error: -4004 Other internal errors
airer-2.current_position-11.error: -4004 Other internal errors
airer.on.error: -4004 Other internal errors
airer.target_position.error: -4004 Other internal errors
state_updater: lan
friendly_name: 晾衣机 Light
supported_features: 3

**Comment by al-one** [comment]
请再次更新master分支。

**Comment by littlehi** [comment]
一样，light 还是这些错误信息，可以控制，但无法加入到homekit 里面去。

min_mireds: 10000
max_mireds: 333
supported_color_modes: brightness, color_temp, onoff
model: mrbond.airer.m33a
lan_ip: 192.168.31.151
mac_address: CC:B5:D1:6C:78:4A
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1
light.on: false
light.brightness.error: -4004 Other internal errors
light.color_temperature.error: -4004 Other internal errors
light.flex_switch.error: -4004 Other internal errors
start_time_hour-4-1.error: -4004 Other internal errors
time_quantum_set.start_time_min.error: -4004 Other internal errors
time_quantum_set.end_time_hour.error: -4004 Other internal errors
time_quantum_set.end_time_min.error: -4004 Other internal errors
headlight_switch-4-5.error: -4004 Other internal errors
airer.fault.error: -4004 Other internal errors
airer.motor_control.error: -4004 Other internal errors
airer.current_position.error: -4004 Other internal errors
airer.status.error: -4004 Other internal errors
airer-2.current_position.error: -4004 Other internal errors
airer-2.current_position-11.error: -4004 Other internal errors
airer.on.error: -4004 Other internal errors
airer.target_position.error: -4004 Other internal errors
state_updater: lan
friendly_name: 晾衣机 Light
supported_features: 3

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/fb4258e33c1da7921d0a4e3662067872b42ae8de/custom_components/xiaomi_miot/light.py#L114-L131

检查你的本地文件以确认是否成功更新到master分支。

**Comment by littlehi** [comment]
重新删除添加设备，从light 实体的属性来看，light.brightness: 和
light.color_temperature: 能够显示了。但是 Homekit 问题依旧。


min_mireds: 10000
max_mireds: 333
supported_color_modes: brightness, color_temp, onoff
model: mrbond.airer.m33a
lan_ip: 192.168.31.151
mac_address: CC:B5:D1:6C:78:4A
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:airer:0000A00D:mrbond-m33a:1
light.on: false
light.brightness.error: -4004 Other internal errors
light.color_temperature.error: -4004 Other internal errors
light.flex_switch.error: -4004 Other internal errors
start_time_hour-4-1.error: -4004 Other internal errors
time_quantum_set.start_time_min.error: -4004 Other internal errors
time_quantum_set.end_time_hour.error: -4004 Other internal errors
time_quantum_set.end_time_min.error: -4004 Other internal errors
headlight_switch-4-5.error: -4004 Other internal errors
airer.fault.error: -4004 Other internal errors
airer.motor_control.error: -4004 Other internal errors
airer.current_position.error: -4004 Other internal errors
airer.status.error: -4004 Other internal errors
airer-2.current_position.error: -4004 Other internal errors
airer-2.current_position-11.error: -4004 Other internal errors
airer.on.error: -4004 Other internal errors
airer.target_position.error: -4004 Other internal errors
state_updater: lan
friendly_name: 晾衣机 Light
supported_features: 3
light.brightness: 98
light.color_temperature: 3003

**Comment by latel** [comment]
还真的是，难怪我homekit里homebridge的设备都挂了
