### ISSUE TITLE
遇到以下问题

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#89]
1、载入时间太长了（每次重启HASS，都要等5分钟以上）
2、水浸传感器无法添加
3、震动传钢琴无法添加
4、除湿机可以添加，只能开关，不能调节湿度

**Comment by al-one** [comment]
> 1、载入时间太长了（每次重启HASS，都要等5分钟以上）

你可以进入`信息`[![Info](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)查看组件的安装时长，或者通过观察日志查找具体哪一步比较慢。

无法添加及操作的设备请提供设备型号(Model)。

**Comment by weiyideai520** [comment]
显示 Xiaomi Miot 花了 368.86秒
[https://imgtu.com/i/g7LnNq](url)


Xiaomi Miot Autoxiaomi_miot | 文档 | 问题 | 368.85&nbsp;s


2、水浸传感器
lumi.flood.bmcn01
lumi.weather.v1

3、震动传感器 
lumi.vibration.aq1

4、除湿机
nwt.derh.330ef

**Comment by al-one** [comment]
载入时间过长的问题请检查下日志，是否有安装依赖或其他耗时的操作。
`lumi.weather.v1`之前的版本就已支持，请检查有无实体并查看日志。
`lumi.flood.bmcn01`/`lumi.vibration.aq1`请更新到master分支最新的提交尝试下。
`nwt.derh.330ef`不能设置温度的问题需要提供设置温度后的[调试日志](https://github.com/al-one/hass-xiaomi-miot/blob/master/README_zh.md#%E8%8E%B7%E5%8F%96%E8%B0%83%E8%AF%95%E6%97%A5%E5%BF%97)。

**Comment by weiyideai520** [comment]
新的报错了，日志如下：
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/xiaomi_miot/core/miot_spec.py:71
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 下午2:58:12 (1 occurrences)
Last logged: 下午2:58:12

Error setting up entry MiCloud: 24624327 for xiaomi_miot
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 767, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 711, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/usr/local/lib/python3.8/http/client.py", line 611, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1817 bytes read, 8423 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 793, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(1817 bytes read, 8423 more expected)', IncompleteRead(1817 bytes read, 8423 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/xiaomi_miot/__init__.py", line 236, in async_setup_entry
    await async_setup_xiaomi_cloud(hass, config_entry)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 292, in async_setup_xiaomi_cloud
    urn = await MiotSpec.async_get_model_type(hass, model)
  File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 95, in async_get_model_type
    return await MiotSpec.async_get_model_type(hass, model, True)
  File "/config/custom_components/xiaomi_miot/core/miot_spec.py", line 71, in async_get_model_type
    res = await hass.async_add_executor_job(requests.get, url)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1817 bytes read, 8423 more expected)', IncompleteRead(1817 bytes read, 8423 more expected))

**Comment by weiyideai520** [comment]
lumi.weather.v1 是我搞错了，这个是温度的确实是有个，我有个 ZB协议的 水浸传感器，设备太多找错了，
应该是：水浸传感器：lumi.sensor_wleak.aq1

另外还有：
空气检测器，zhimi.airmonitor.v1
光照传感器：lumi.sen_ill.mgl01
驱蚊器: zimi.mosq.v1
遥控器: chuangmi.ir.v2
网关：lumi.gateway.mgl03
人体传感器：lumi.sensor_motion.v1
无线开关：lumi.sensor_switch.v1；lumi.sensor_switch.v2

**Comment by weiyideai520** [comment]
lumi.weather.v1 确实是有，但是确实 大气压的数据，只有温度和湿度

**Comment by weiyideai520** [comment]
震动传感器的数据有了，但是不是很看得懂
model: lumi.vibration.aq1
lan_ip: ''
mac_address: lumi.158d00031b1cd4
firmware_version: 1.0.0_0008
hardware_version: ''
entity_class: MiotSensorEntity
miot_type: 'urn:miot-spec-v2:device:vibration-sensor:0000A09B:lumi-aq1:1'
state_property: detection_sensitivity
battery.voltage: 3005
detection_sensitivity: 11
state_updater: cloud
sub_entities:
  - battery-3.voltage-2
friendly_name: 书桌椅
supported_features: 0

**Comment by weiyideai520** [comment]
除湿机的主体：
min_humidity: null
max_humidity: null
available_modes:
  - 'Off'
  - Auto
  - Continue
  - Dry Clothes
humidity: 70
mode: 'Off'
model: nwt.derh.330ef
lan_ip: 192.168.199.254
mac_address: '54:48:E6:5D:50:0A'
firmware_version: 2.1.8
hardware_version: ''
entity_class: MiotHumidifierEntity
miot_type: 'urn:miot-spec-v2:device:dehumidifier:0000A02D:nwt-330ef:1'
timer_service.timer: 0
timer_service.timer_setting: 0
pump: false
pump.pump_pipe_installed: true
event_service.coil_temp: 22
event_service.compressor_status: false
event_service.water_tank_status: false
event_service.defrost_status: false
event_service.fall_down_status: false
physical_controls_locked: false
indicator_light.on: true
alarm: true
environment.relative_humidity: 74
environment.temperature: 22
dehumidifier.on: false
dehumidifier.fault.error: -704042011
dehumidifier.mode: 1
dehumidifier.target_humidity: 70
dehumidifier.fan_level: 0
state_updater: cloud
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-7
  - physical_controls_locked-6.physical_controls_locked-1
  - indicator_light-5
  - fan_level
friendly_name: 移动除湿机
supported_features: 1
device_class: dehumidifier

------------设置时报错-------------
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/xiaomi_miot/humidifier.py:126
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 下午4:21:27 (8 occurrences)
Last logged: 下午4:21:32

[140036744533088] Unable to discover the device 192.168.199.254
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 161, in async_set_humidity
    await self.hass.async_add_executor_job(self.set_humidity, humidity)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/humidifier.py", line 126, in set_humidity
    return self._device.set_property(self._prop_target_humi.full_name, num)
  File "/usr/local/lib/python3.8/site-packages/miio/miot_device.py", line 132, in set_property
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 178, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.199.254

**Comment by al-one** [comment]
> lumi.weather.v1 确实是有，但是缺少 大气压的数据，只有温度和湿度

状态属性里应该有个`atmospheric_pressure`相关的属性，如果你想独立出一个实体，可以用[template sensor](https://www.home-assistant.io/integrations/template)

**Comment by al-one** [comment]
> 震动传感器的数据有了，但是不是很看得懂

由于本插件采用轮询的方式获取数据获取设备数据，而该震动传感器的主要数据通过事件(event)推送到米家服务器，因此插件无法获取此类数据。此外人体传感器、门窗传感器、无线开关、魔方控制器也是如此。

**Comment by al-one** [comment]
> 除湿机的主体：
> ------------设置时报错-------------
> Source: custom_components/xiaomi_miot/humidifier.py:126

可能你的除湿机不支持通过局域网控制设备，仅支持局域网读取数据。可以通过配置自定义属性开启云端操作设备：
> [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🖌 自定义 > 🔍 选择实体 > 选择要覆盖的属性 > 添加Other属性

```yaml
# customize.yaml
humidifier.your_entity_id:
  miot_cloud_write:  true # 仅写属性使用云端模式
  miot_cloud_action: true # 仅action使用云端模式
```

**Comment by kingwap99** [comment]
空气检测器，zhimi.airmonitor.v1 
沒有任何実体
