### ISSUE TITLE
小米温湿度计2不可用

### ISSUE THREAD

**Issue by qq562934992** [al-one/hass-xiaomi-miot#914]
### Device model

[miaomiaoce.sensor_ht.t2](https://home.miot-spec.com/s/miaomiaoce.sensor_ht.t2)

### Component version

0.7.2

### HA core version

2022.11.4

### Integrated mode

Automatic (自动模式)

### The problem

小米温湿度计2添加后不可用

### Entity attributes

```yaml
restored: true
friendly_name: 温湿度计 Temperature Humidity Sensor
supported_features: 0
```

### Home Assistant Logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot/sensor.py", line 71, in async_setup_entry
    await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 549, in async_setup_config_entry
    await async_setup_platform(hass, c, async_add_entities)
  File "/config/custom_components/xiaomi_miot/sensor.py", line 123, in async_setup_platform
    entities.append(MiotSensorEntity(config, srv))
  File "/config/custom_components/xiaomi_miot/sensor.py", line 170, in __init__
    self._name = f'{self.device_name} {self._prop_state.friendly_desc}'
AttributeError: 'NoneType' object has no attribute 'friendly_desc'

**Comment by al-one** [comment]
更新至master分支后重试。

**Comment by qq562934992** [comment]
> 更新至master分支后重试。

master分支已正常使用

**Comment by qq562934992** [comment]
> 更新至master分支后重试。

单独添加时温湿度计2时可以正常使用，后续添加其他设备后，温湿度计变为不可用，日志显示相同的错误。与其他设备一起添加时，设备中没有温湿度计设备。并且显示相同的错误日志。

**Comment by qq562934992** [comment]
> 粘贴日志
Logger: homeassistant.components.sensor
Source: custom_components/xiaomi_miot/sensor.py:170
Integration: 传感器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:12:56 (2 occurrences)
Last logged: 15:22:00

Error while setting up xiaomi_miot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot/sensor.py", line 71, in async_setup_entry
    await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 549, in async_setup_config_entry
    await async_setup_platform(hass, c, async_add_entities)
  File "/config/custom_components/xiaomi_miot/sensor.py", line 123, in async_setup_platform
    entities.append(MiotSensorEntity(config, srv))
  File "/config/custom_components/xiaomi_miot/sensor.py", line 170, in __init__
    self._name = f'{self.device_name} {self._prop_state.friendly_desc}'
AttributeError: 'NoneType' object has no attribute 'friendly_desc'

**Comment by al-one** [comment]
master分支没有更新成功，请重新更新。

**Comment by qq562934992** [comment]
> master分支没有更新成功，请重新更新。

hacs选择master版本下载，下载下来mainfest.json的版本还是0.7.2的，是我更新的方式不对吗

**Comment by al-one** [comment]
HACS在选择master版本后，需等待版本下拉框变亮再点击下载。

**Comment by qq562934992** [comment]
> 下拉框变亮再点击下

已正常！！谢谢！！
