### ISSUE TITLE
米家踢脚线电暖器S1在HA中不可用

### ISSUE THREAD

**Issue by rockxsj** [al-one/hass-xiaomi-miot#924]
### Device model / 设备型号

[Mi Smart Baseboard Heater 1S fan](https://home.miot-spec.com/s/leshow.heater.bs1s)

### Component version / 插件版本

latest

### HA core version / HA版本

latest

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在HA中显示不可用，但是米家APP中一切正常

![1670393851278](https://user-images.githubusercontent.com/3021207/206103931-b5b37753-16ff-4d44-aa5e-7c1cd2def473.jpg)

### Entity attributes / 实体属性

![image](https://user-images.githubusercontent.com/3021207/206104231-90742c0c-4d7d-4725-8007-1f8ea6d78ce8.png)

**Comment by al-one** [comment]
请提供[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by jarviszhb** [comment]
> 请提供[日志](https://my.home-assistant.io/redirect/logs)。

我也遇到了这个问题，在HA中显示不可用，但是可以通过点auto键将其唤醒，但是在homekit中就是一直未响应了；

2022-12-06 19:20:14 ERROR (MainThread) [custom_components.xiaomi_miot.climate] 电暖器(zhimi.heater.ma3): Got MiioException while fetching the state: Unable to discover the device 192.168.31.252, mapping: {'heater.on': {'siid': 2, 'piid': 1}, 'heater.fault': {'siid': 2, 'piid': 2}, 'heater.target_temperature': {'siid': 2, 'piid': 5}, 'heater.mode': {'siid': 2, 'piid': 6}, 'private_service.use_time': {'siid': 8, 'piid': 9}, 'indicator_light.brightness': {'siid': 7, 'piid': 3}, 'alarm': {'siid': 6, 'piid': 1}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'countdown.countdown_time': {'siid': 3, 'piid': 1}}, max_properties: 10/10
2022-12-06 19:21:04 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.zhimi_ma3_c431_heater fails

这是我在日志中用zhimi过滤搜索到的信息

**Comment by al-one** [comment]
> Unable to discover the device 192.168.31.252

检查设备IP。
- https://github.com/al-one/hass-xiaomi-miot/issues/500#offline

**Comment by jarviszhb** [comment]
> > Unable to discover the device 192.168.31.252
> 
> 检查设备IP。
> 
> * [登录失败/没有实体等常见问题解决办法 #500 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/500#offline)

设备ip是没问题的，又找了找日志，发现了如下的报错，现状还是开一会就会发现不了设备
2022-12-08 22:36:01 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.zhimi_ma3_c431_heater fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
raise exc
File "/config/custom_components/xiaomi_miot/climate.py", line 203, in async_update
await super().async_update()
File "/config/custom_components/xiaomi_miot/__init__.py", line 1452, in async_update
await self.async_update_for_main_entity()
File "/config/custom_components/xiaomi_miot/__init__.py", line 1467, in async_update_for_main_entity
self._update_sub_entities(pls, '*', domain=d)
File "/config/custom_components/xiaomi_miot/__init__.py", line 2019, in _update_sub_entities
self._subs[fnm].update_from_parent()
File "/config/custom_components/xiaomi_miot/__init__.py", line 2360, in update_from_parent
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 170, in state
return self.value
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 175, in value
return self._attr_value
AttributeError: 'MiotNumberSubEntity' object has no attribute '_attr_value'
2022-12-08 22:36:02 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 740, in _update_entity_states
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 170, in state
return self.value
File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 175, in value
return self._attr_value
AttributeError: 'MiotNumberSubEntity' object has no attribute '_attr_value'

**Comment by al-one** [comment]
> AttributeError: 'MiotNumberSubEntity' object has no attribute '_attr_value'

请升级你的HA至2022.7.0版本及以上，该版本HA对`number`实体做了一个无法向下兼容的修改。
