### ISSUE TITLE
2022-12-16日更新版本后 小米厨下净水器1A/400G实体所有状态无法获取

### ISSUE THREAD

**Issue by RavenKong** [al-one/hass-xiaomi-miot#938]
### Device model / 设备型号

yunmi.waterpuri.lx5

### Component version / 插件版本

0.7.3 可访问米家服务器	ok 可获取MIoT规格	ok

### HA core version / HA版本

Supervisor 2022.11.2 Operating System 9.4 前端版本： 20221213.0 - latest

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

2022-12-16日更新版本后 小米厨下净水器1A/400G实体所有状态无法获取

### Entity attributes / 实体属性

[sensor.yunmi_lx5_6a8c_total_dissolved_solids_for_output_water](http://homeassistant.local:8123/developer-tools/state#)
净水器出水TDS

### Home Assistant Logs / 系统日志

Logger: homeassistant.helpers.entity
Source: helpers/template.py:425
First occurred: 23:54:42 (4 occurrences)
Last logged: 23:56:12

Update for sensor.yunmi_lx5_6a8c_water_purifier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'f3_usedtime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/sensor.py", line 205, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1323, in async_update
    results = await self._miio2miot.async_get_miot_props(self.miot_device, local_mapping)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 115, in async_get_miot_props
    return await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/core/miio2miot.py", line 140, in get_miot_props
    val = tpl.render({
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 395, in render
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 64, in run_callback
    future.set_result(callback(*args))
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 425, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'dict object' has no attribute 'f3_usedtime'

**Comment by al-one** [comment]
该bug已在master分支中修复，请更新master后尝试。

**Comment by RavenKong** [comment]
Fix confirmed, thanks!
