### ISSUE TITLE
suittc.airrtc.wk168的hvac_modes属性缺少heat

### ISSUE THREAD

**Issue by fevenor** [al-one/hass-xiaomi-miot#965]
### Device model / 设备型号

[suittc.airrtc.wk168](https://home.miot-spec.com/s/suittc.airrtc.wk168)

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

智能温控器`suittc.airrtc.wk168`，当前开关状态展示为独立开关`switch.suittc_wk168_xxxx_switch_status`，而`climate.suittc_wk168_xxxx_thermostat`的`hvac_modes`属性仅有`'off'`，缺少`heat`。
这导致对climate只能进行关闭操作，若要开启地暖，需要操作switch。
希望能将switch的`on`状态对应到climate的`heat`模式

### Entity attributes / 实体属性

```
hvac_modes: off
min_temp: 2
max_temp: 85
target_temp_step: 1
fan_modes: 1
preset_modes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, off
current_temperature: 15.3
temperature: 18
fan_mode: 1
hvac_action: idle
preset_mode: null
model: suittc.airrtc.wk168
lan_ip: 10.1.8.51
mac_address: <hided>
entity_class: MiotClimateEntity
home_room: <hided>
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:suittc-wk168:1
thermostat.on: true
thermostat.fan_level: 1
thermostat.mode: 9
thermostat.target_temperature: 18
thermostat.temperature: 15.3
custom_program.mon_pro: 0x01,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.tue_pro: 0x02,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.wed_pro: 0x04,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.thur_pro: 0x08,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.fri_pro: 0x10,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.sat_pro: 0x20,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.sun_pro: 0x40,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
state_updater: lan
sub_entities: thermostat-2.on-1
friendly_name: <hided>
supported_features: 25
```

**Comment by al-one** [comment]
请更新master分支后再试。

**Comment by fevenor** [comment]
> 请更新master分支后再试。

更新后删除设备重新添加测试，注意到实体状态为`heat`，但是`hvac_modes`属性依然只有`off`，同时`hvac_action`属性消失

```
hvac_modes: off
min_temp: 2
max_temp: 85
target_temp_step: 1
fan_modes: 1
preset_modes: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, off
current_temperature: 14.5
temperature: 11
fan_mode: 1
preset_mode: null
model: suittc.airrtc.wk168
lan_ip: 10.1.8.51
mac_address: <hided>
entity_class: MiotClimateEntity
home_room: <hided>
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:suittc-wk168:1
thermostat.on: true
thermostat.fan_level: 1
thermostat.mode: 1
thermostat.target_temperature: 11
thermostat.temperature: 14.5
custom_program.mon_pro: 0x01,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.tue_pro: 0x02,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.wed_pro: 0x04,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.thur_pro: 0x08,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.fri_pro: 0x10,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.sat_pro: 0x20,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
custom_program.sun_pro: 0x40,0x00,0x05,0x10,0x14,0x20,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05,0x30,0x05
state_updater: lan
sub_entities: thermostat-2.on-1
friendly_name: <hided>
supported_features: 25
```

**Comment by fevenor** [comment]
> 同时`hvac_action`属性消失

使用米家APP执行关闭操作后，属性出现了

```
hvac_action: off
```

**Comment by fevenor** [comment]
master分支似乎存在新的问题：
```
2023-01-01 17:22:13.163 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.suittc_wk168_fef9_thermostat fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/xiaomi_miot/climate.py", line 204, in async_update
    await super().async_update()
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1343, in async_update
    results = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 655, in get_properties_for_mapping
    return self.get_properties(
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 240, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 202, in send
    self.__id = payload["id"]
TypeError: byte indices must be integers or slices, not str
```
