### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'full_name'

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#985]
Error in custom integration. Please help, maybe you need to use a different prop now.
HA 2023.1.2
Xiaomi Miot Auto v 0.7.4

Log:

Logger: homeassistant
Source: custom_components/xiaomi_miot/sensor.py:295
Integration: Xiaomi Miot Auto
First occurred: 09:59:48 (119 occurrences)
Last logged: 11:05:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 830, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 543, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 855, in state
    value = self.native_value
  File "/config/custom_components/xiaomi_miot/sensor.py", line 295, in native_value
    key = f'{self._prop_state.full_name}_desc'
AttributeError: 'NoneType' object has no attribute 'full_name'

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/56dfca4dd08f03f76e0ad1b4f123e511ee4c5fe6
